SELECT
TPRD.IDPRD,
TPRD.CODIGOPRD,
TPRD.CODIGOREDUZIDO,
TPRD.NOMEFANTASIA,
TPRD.CODCOLIGADA,
TPRD.CODUNDCONTROLE,
TPRD.CODUNDCOMPRA,
TPRD.CODUNDVENDA,
TPRDCOMPL.PERMITECOMPRANUCLEUS,
TPRD.CAMPOLIVRE,
TPRD.DTCADASTRAMENTO,

(CASE WHEN TPRD.INATIVO = 0 THEN 'ATIVO' ELSE 'INATIVO' END) AS INATIVACAO_COMPLETA,
(CASE WHEN TPRDCOMPL.INATIVO = 'T' THEN 'PARCIALMENTE INATIVO' 
			ELSE 'ATIVO' END) AS INATIVACAO_PARCIAL, 
TTB4.DESCRICAO AS CLASSI_CONTABIL,
tprd.CODTB4FAT,
TPRD.CODTBORCAMENTO, 
TTBORCAMENTO.DESCRICAO AS NATUREZA_FINANCEIRA

FROM TPRD										(NOLOCK)
LEFT JOIN TPRDCOMPL								(NOLOCK) ON TPRD.IDPRD = TPRDCOMPL.IDPRD AND TPRD.CODCOLIGADA = TPRDCOMPL.CODCOLIGADA
LEFT JOIN TTB4									(NOLOCK) ON TPRD.CODTB4FAT = TTB4.CODTB4FAT AND TPRD.CODCOLIGADA = TTB4.CODCOLIGADA
LEFT JOIN TTBORCAMENTO							(NOLOCK) ON TPRD.CODTBORCAMENTO = TTBORCAMENTO.CODTBORCAMENTO


WHERE TPRD.INATIVO = 0
AND TPRD.TIPO = 'P'
AND TPRD.ULTIMONIVEL = 1
AND TPRD.CODCOLIGADA IN (@CODCOLIGADA)
AND LEFT(TPRD.CODIGOPRD,4) IN (@GRUPO)
AND CONVERT(VARCHAR, TPRD.INATIVO) IN (@ATIVACAO_RM) /* PRECISA SER VALOR DE 0 E 1*/ 
AND (CASE WHEN TPRDCOMPL.INATIVO = 'T' THEN 'PARCIALMENTE INATIVO' 
					WHEN TPRDCOMPL.INATIVO = 'F' THEN 'ATIVO'
					ELSE 'ATIVO' END) IN (@ATIVACAO_PARCIAL)
					