SELECT 
PFUNC.NOME, 
PPESSOA.CIDADE,
PPESSOA.ESTADO,
PFUNC.CODFUNCAO, 
PFUNCAO.NOME AS CARGO,
PFUNCAO.DESCRICAO,
PFUNC.CODSITUACAO

FROM PFUNC (NOLOCK)
LEFT JOIN PFUNCAO (NOLOCK) ON PFUNC.CODFUNCAO = PFUNCAO.CODIGO
LEFT JOIN PPESSOA (NOLOCK) ON  PFUNC.NOME = PPESSOA.NOME
WHERE PFUNC.CODSITUACAO = 'A' 
--AND PFUNC.NOME LIKE '%%' 
AND PFUNCAO.NOME LIKE '%SISTEMAS%'

ORDER BY 1,3

