SELECT TUSRTMV.CODCOLIGADA, 
TUSRTMV.CODUSUARIO, 
TUSRTMV.CODTMV, 
CODPERFIL 
FROM GUSRPERFIL 
LEFT JOIN TUSRTMV ON (TUSRTMV.CODUSUARIO = GUSRPERFIL.CODUSUARIO AND GUSRPERFIL.CODCOLIGADA = TUSRTMV.CODCOLIGADA)
LEFT JOIN GUSUARIO ON (GUSRPERFIL.CODUSUARIO= GUSUARIO.CODUSUARIO)
WHERE CODSISTEMA = 'T'
AND GUSUARIO.NOME IN (SELECT NOME FROM PFUNC WHERE CODSECAO NOT IN ('01.500.20','01.500.21','01.500.91') AND CODSITUACAO <> 'D') AND
TUSRTMV.CODCOLIGADA = 1
AND TUSRTMV.CODTMV IN ('1.1.21', '1.1.35');