DECLARE @DATA_BASE_D AS DATETIME, @MULTA AS DECIMAL(10,5), @MORA AS DECIMAL(10,10)

SET @DATA_BASE_D = 20230531
SET @MULTA='0.02'
SET @MORA='0.033333333'

SELECT     
	 'CNPJ_EMPREENDIMENTO' = XEMPREENDIMENTO.CNPJ
	 ,'NOME_COLIGADA' = GCOLIGADA.NOME
     ,'EMPREENDIMENTO'= XEMPREENDIMENTO.COD_PESS_EMPR
     ,'NOME_EMPREENDIMENTO' = XEMPREENDIMENTO.NOME 
	 ,'VENDA' = XVENDA.NUM_VENDA
     ,'BL/QD'=XITEMVENDA.NUM_UNID 
     ,'APTO/LOTE'=XITEMVENDA.NUM_SUB_UNID 
     ,'TIPO_PAGTO'=XTIPOPARCELA.DSC_TIPO_PARC
     ,'PARCELA'=XVENDAPARCELA.NUMPARC
     ,'CLIENTE'=dbo.InitCap(FCFO.NOME)


	 /* CAMPO INCLUIDO ATRAVES DA AUTORIZAÇÃO DO CHAMADO 1022-001057 */
	 ,FCFO.CGCCFO
	 ,FCFO.DTNASCIMENTO
	 ,XCLIENTEPESSOAFISICA.NOM_MAE
     ,FCFO.RUA
     ,FCFO.NUMERO
     ,FCFO.COMPLEMENTO
     ,FCFO.CEP
     ,FCFO.BAIRRO
     ,GMUNICIPIO.NOMEMUNICIPIO +'/'+ FCFO.CODETD AS 'Cidade'
     ,FCFO.EMAIL AS 'EMAIL'
     ,COALESCE(FCFO.TELEX, FCFO.TELEFONE) AS 'TELEFONE'
     ,'VENCIMENTO'=CONVERT(VARCHAR,FLAN.DATAVENCIMENTO,103)
     ,XVENDA.NUM_VENDA
     ,XVENDAPARCELA.CODCOLIGADA 
     ,XVENDAPARCELA.IDLAN 
     ,XVENDAPARCELA.NUMPARC 
     ,XMODALIDADEVENDA.DSC_MOD_VENDA
     
     /* CORRECAO COLIGADA 10 (6 , 13)
	    CORRECAO COLIGADA 11 (4 , 11) */
   					
   ,'CORREÇÃO'= ISNULL((SELECT SUM (VALOR)FROM FLANINTEGRACAO WHERE IDLAN = FLAN.IDLAN AND CODCOLIGADA = FLAN.CODCOLIGADA AND IDCAMPO IN (select IDCAMPO from dbo.RETORNA_IDCAMPO_JUROS(FLAN.CODCOLIGADA,'CM'))),0) 
					-
					/* CORRECAO BAIXADA PARCIALMENTE */ ISNULL((SELECT SUM (VALOR)FROM FLANBAIXAINTEGRACAO 
					INNER JOIN FLANBAIXA (NOLOCK) ON (FLANBAIXA.IDBAIXA = FLANBAIXAINTEGRACAO.IDBAIXA AND FLANBAIXA.IDLAN = FLANBAIXAINTEGRACAO.IDLAN AND FLANBAIXA.CODCOLIGADA = FLANBAIXAINTEGRACAO.CODCOLIGADA)
					WHERE FLANBAIXA.STATUS <> 1 AND FLANBAIXAINTEGRACAO.IDLAN = FLAN.IDLAN AND FLANBAIXAINTEGRACAO.CODCOLIGADA = FLAN.CODCOLIGADA AND FLANBAIXAINTEGRACAO.IDCAMPO IN (select IDCAMPO from dbo.RETORNA_IDCAMPO_JUROS(FLAN.CODCOLIGADA,'CM'))),0)
					
	/* JUROS COLIGADA 10 (5 , 14) 
	   JUROS COLIGADA 11 (*/
					
	,'JUROS'= ISNULL((SELECT SUM (VALOR)FROM FLANINTEGRACAO WHERE IDLAN = FLAN.IDLAN AND CODCOLIGADA = FLAN.CODCOLIGADA AND IDCAMPO IN (select IDCAMPO from dbo.RETORNA_IDCAMPO_JUROS(FLAN.CODCOLIGADA,'JUROS'))),0) 
					-
					/* JUROS BAIXADO PARCIALMENTE */ ISNULL((SELECT SUM (VALOR)FROM FLANBAIXAINTEGRACAO 
					INNER JOIN FLANBAIXA (NOLOCK) ON (FLANBAIXA.IDBAIXA = FLANBAIXAINTEGRACAO.IDBAIXA AND FLANBAIXA.IDLAN = FLANBAIXAINTEGRACAO.IDLAN AND FLANBAIXA.CODCOLIGADA = FLANBAIXAINTEGRACAO.CODCOLIGADA)
					WHERE FLANBAIXA.STATUS <> 1 AND FLANBAIXAINTEGRACAO.IDLAN = FLAN.IDLAN AND FLANBAIXAINTEGRACAO.CODCOLIGADA = FLAN.CODCOLIGADA AND FLANBAIXAINTEGRACAO.IDCAMPO IN (select IDCAMPO from dbo.RETORNA_IDCAMPO_JUROS(FLAN.CODCOLIGADA,'JUROS'))),0)
	
	,'HONORÁRIO' = FLAN.VALOROP8
	,'DESCONTO'=VALORDESCONTO
			
	,(CASE WHEN FLAN.STATUSLAN IN (4) THEN  DBO.SAL_REMANECENTE(XVENDAPARCELA.IDLAN, XVENDAPARCELA.CODCOLIGADA) ELSE FLAN.VALORORIGINAL END) AS VALOR
	,(dbo.MULTA_PARCELAS_SGI (FLAN.CODCOLIGADA,FLAN.IDLAN, @DATA_BASE_D)) as Multa
	,(dbo.JUROS_PARCELAS_SGI (FLAN.CODCOLIGADA,FLAN.IDLAN, @DATA_BASE_D)) as Mora



			,TOTAL=(CASE WHEN FLAN.STATUSLAN IN (4) THEN  DBO.SAL_REMANECENTE(XVENDAPARCELA.IDLAN, XVENDAPARCELA.CODCOLIGADA) ELSE FLAN.VALORORIGINAL END)  +ISNULL((SELECT SUM (VALOR)FROM FLANINTEGRACAO WHERE IDLAN = FLAN.IDLAN AND CODCOLIGADA = FLAN.CODCOLIGADA AND IDCAMPO IN (select IDCAMPO from dbo.RETORNA_IDCAMPO_JUROS(FLAN.CODCOLIGADA,'CM'))),0) +ISNULL((SELECT SUM (VALOR)FROM FLANINTEGRACAO WHERE IDLAN = FLAN.IDLAN AND CODCOLIGADA = FLAN.CODCOLIGADA AND IDCAMPO IN (select IDCAMPO from dbo.RETORNA_IDCAMPO_JUROS(FLAN.CODCOLIGADA,'JUROS'))),0)
			-/* CORRECAO BAIXADA PARCIALMENTE */ ISNULL((SELECT SUM (VALOR)FROM FLANBAIXAINTEGRACAO 
			INNER JOIN FLANBAIXA (NOLOCK) ON (FLANBAIXA.IDBAIXA = FLANBAIXAINTEGRACAO.IDBAIXA AND FLANBAIXA.IDLAN = FLANBAIXAINTEGRACAO.IDLAN AND FLANBAIXA.CODCOLIGADA = FLANBAIXAINTEGRACAO.CODCOLIGADA)
			WHERE FLANBAIXA.STATUS <> 1 AND FLANBAIXAINTEGRACAO.IDLAN = FLAN.IDLAN AND FLANBAIXAINTEGRACAO.CODCOLIGADA = FLAN.CODCOLIGADA AND FLANBAIXAINTEGRACAO.IDCAMPO IN (select IDCAMPO from dbo.RETORNA_IDCAMPO_JUROS(FLAN.CODCOLIGADA,'CM'))),0)
			-/* JUROS BAIXADO PARCIALMENTE */ ISNULL((SELECT SUM (VALOR)FROM FLANBAIXAINTEGRACAO 
			INNER JOIN FLANBAIXA (NOLOCK) ON (FLANBAIXA.IDBAIXA = FLANBAIXAINTEGRACAO.IDBAIXA AND FLANBAIXA.IDLAN = FLANBAIXAINTEGRACAO.IDLAN AND FLANBAIXA.CODCOLIGADA = FLANBAIXAINTEGRACAO.CODCOLIGADA)
			WHERE FLANBAIXA.STATUS <> 1 AND FLANBAIXAINTEGRACAO.IDLAN = FLAN.IDLAN AND FLANBAIXAINTEGRACAO.CODCOLIGADA = FLAN.CODCOLIGADA AND FLANBAIXAINTEGRACAO.IDCAMPO IN (select IDCAMPO from dbo.RETORNA_IDCAMPO_JUROS(FLAN.CODCOLIGADA,'JUROS'))),0)
			
			
			,VALOR_CORRIGIDO=(CASE WHEN FLAN.STATUSLAN IN (4) THEN  DBO.SAL_REMANECENTE(XVENDAPARCELA.IDLAN, XVENDAPARCELA.CODCOLIGADA) ELSE FLAN.VALORORIGINAL END)  +ISNULL((SELECT SUM (VALOR)FROM FLANINTEGRACAO WHERE IDLAN = FLAN.IDLAN AND CODCOLIGADA = FLAN.CODCOLIGADA AND IDCAMPO IN (select IDCAMPO from dbo.RETORNA_IDCAMPO_JUROS(FLAN.CODCOLIGADA,'CM'))),0) +ISNULL((SELECT SUM (VALOR)FROM FLANINTEGRACAO WHERE IDLAN = FLAN.IDLAN AND CODCOLIGADA = FLAN.CODCOLIGADA AND IDCAMPO IN (select IDCAMPO from dbo.RETORNA_IDCAMPO_JUROS(FLAN.CODCOLIGADA,'JUROS'))),0) + FLAN.VALORJUROS
			+(dbo.MULTA_PARCELAS_SGI (FLAN.CODCOLIGADA,FLAN.IDLAN, @DATA_BASE_D))
			+(dbo.JUROS_PARCELAS_SGI (FLAN.CODCOLIGADA,FLAN.IDLAN, @DATA_BASE_D)) 
			-/* CORRECAO BAIXADA PARCIALMENTE */ ISNULL((SELECT SUM (VALOR)FROM FLANBAIXAINTEGRACAO 
			INNER JOIN FLANBAIXA (NOLOCK) ON (FLANBAIXA.IDBAIXA = FLANBAIXAINTEGRACAO.IDBAIXA AND FLANBAIXA.IDLAN = FLANBAIXAINTEGRACAO.IDLAN AND FLANBAIXA.CODCOLIGADA = FLANBAIXAINTEGRACAO.CODCOLIGADA)
			WHERE FLANBAIXA.STATUS <> 1 AND FLANBAIXAINTEGRACAO.IDLAN = FLAN.IDLAN AND FLANBAIXAINTEGRACAO.CODCOLIGADA = FLAN.CODCOLIGADA AND FLANBAIXAINTEGRACAO.IDCAMPO IN (select IDCAMPO from dbo.RETORNA_IDCAMPO_JUROS(FLAN.CODCOLIGADA,'CM'))),0)
			-/* JUROS BAIXADO PARCIALMENTE */ ISNULL((SELECT SUM (VALOR)FROM FLANBAIXAINTEGRACAO 
			INNER JOIN FLANBAIXA (NOLOCK) ON (FLANBAIXA.IDBAIXA = FLANBAIXAINTEGRACAO.IDBAIXA AND FLANBAIXA.IDLAN = FLANBAIXAINTEGRACAO.IDLAN AND FLANBAIXA.CODCOLIGADA = FLANBAIXAINTEGRACAO.CODCOLIGADA)
			WHERE FLANBAIXA.STATUS <> 1 AND FLANBAIXAINTEGRACAO.IDLAN = FLAN.IDLAN AND FLANBAIXAINTEGRACAO.CODCOLIGADA = FLAN.CODCOLIGADA AND FLANBAIXAINTEGRACAO.IDCAMPO IN (select IDCAMPO from dbo.RETORNA_IDCAMPO_JUROS(FLAN.CODCOLIGADA,'JUROS'))),0)
			- VALORDESCONTO
            + FLAN.VALOROP8
   
			,FTB2.DESCRICAO AS CLASS_FIN
			,(CASE	
					WHEN FLAN.STATUSLAN = '0'
						THEN 'EM ABERTO' +' -- '+(CASE
                                                                                                                                                     WHEN FLAN.DATAVENCIMENTO < GETDATE()
										THEN 'LANÇAMENTO VENCIDO'
										ELSE 'NÃO VENCIDO'	
									END)
					WHEN FLAN.STATUSLAN = '1'
						THEN 'BAIXADO'
					WHEN FLAN.STATUSLAN = '2'
						THEN 'CANCELADO'
					WHEN FLAN.STATUSLAN = '3'
						THEN 'BAIXADO POR ACORDO'
					WHEN FLAN.STATUSLAN = '4'
						THEN 'BAIXADO PARCIALMENTE' +' -- '+(CASE
										           WHEN FLAN.DATAVENCIMENTO < GETDATE()
											      THEN 'LANÇAMENTO VENCIDO'
											      ELSE 'NÃO VENCIDO'	
						   				   END)
					WHEN FLAN.STATUSLAN = '5'
						THEN 'BORDERÔ'
					ELSE 'VAZIO'	
				END) AS 'STATUS'
,CONVERT(VARCHAR, XMODALIDADEVENDA.COD_MOD_VENDA) + ' - ' +XMODALIDADEVENDA.DSC_MOD_VENDA AS MODALIDADE_VENDA

     

FROM			    XVENDA (NOLOCK)
					LEFT JOIN  XVENDAPARCELA           (NOLOCK) ON (XVENDAPARCELA.NUMVENDA=XVENDA.NUM_VENDA)
					LEFT JOIN XEMPREENDIMENTO      (NOLOCK) ON (XEMPREENDIMENTO.COD_PESS_EMPR=XVENDA.COD_PESS_EMPR)
					LEFT JOIN GCOLIGADA	          (NOLOCK) ON (GCOLIGADA.CODCOLIGADA = XVENDA.CODCOLIGADA)
					LEFT JOIN FCFO                               (NOLOCK) ON (FCFO.CODCOLIGADA=XVENDA.CODCOLCFO AND FCFO.CODCFO=XVENDA.CODCFO)
					LEFT JOIN XITEMVENDA                  (NOLOCK) ON (XITEMVENDA.NUM_VENDA=XVENDA.NUM_VENDA)
					LEFT JOIN XTIPOPARCELA                (NOLOCK) ON (XVENDAPARCELA.CODTIPOPARC=XTIPOPARCELA.COD_TIPO_PARC)
					LEFT JOIN FLAN                                (NOLOCK) ON (XVENDAPARCELA.CODCOLLAN=FLAN.CODCOLIGADA AND XVENDAPARCELA.IDLAN=FLAN.IDLAN)
					LEFT JOIN FTB2                                 (NOLOCK) ON (FTB2.CODTB2FLX = FLAN.CODTB2FLX AND FTB2.CODCOLIGADA = FLAN.CODCOLIGADA)
					LEFT JOIN XMODALIDADEVENDA   (NOLOCK) ON (XMODALIDADEVENDA.COD_MOD_VENDA=XVENDA.COD_MOD_VENDA)
					LEFT JOIN GMUNICIPIO	          (NOLOCK) ON (FCFO.CODMUNICIPIO = GMUNICIPIO.CODMUNICIPIO AND FCFO.CODETD = GMUNICIPIO.CODETDMUNICIPIO)
					LEFT JOIN XCLIENTEPESSOAFISICA  (NOLOCK) ON (XCLIENTEPESSOAFISICA.CODCFO = FCFO.CODCFO AND XCLIENTEPESSOAFISICA.CODCOLIGADA = FCFO.CODCOLIGADA)

WHERE				XEMPREENDIMENTO.COD_PESS_EMPR IN ('%%')
					AND FLAN.STATUSLAN IN (0,4)
					AND FLAN.DATAVENCIMENTO BETWEEN '19000101' AND '30001231'
					AND FCFO.NOME LIKE '%' + '%%' + '%' 
					AND XTIPOPARCELA.COD_TIPO_PARC IS NOT NULL
					AND XVENDA.COD_SIT_VENDA <> 10
					AND XVENDA.COD_SIT_VENDA NOT IN (60,61,62)
     
order by FCFO.NOME    