USE CORPORE_RESIDENCIAL

SELECT  TOP 100

GCOLIGADA.CODCOLIGADA AS COD_COLIGADA,
GFILIAL.CGC AS CNPJ_EMPREENDIMENTO,
GCOLIGADA.NOME AS NOME_COLIGADA,
FCFO.NOMEFANTASIA AS NOME_CLIENTE,
FCFO.CGCCFO AS 'CNPJ/CPF',
--XCOMPONENTE.DSC_COMPN AS TIPO_PARC,
(	
	SELECT TOP 1 UPPER(FLANINTEGRACAODEF.DESCRICAO)
	FROM FLANINTEGRACAO AS INTEGRA
	LEFT JOIN FLANINTEGRACAODEF					(NOLOCK) ON (INTEGRA.IDCAMPO = FLANINTEGRACAODEF.IDCAMPO AND INTEGRA.CODCOLIGADA = FLANINTEGRACAODEF.CODCOLIGADA)
	WHERE FLAN.IDLAN = INTEGRA.IDLAN
	AND FLAN.CODCOLIGADA = INTEGRA.CODCOLIGADA
	ORDER BY INTEGRA.VALOR DESC
) 
AS 'TIPO DE PARCELA',

FLANBAIXA.IDLAN,
FLAN.DATAVENCIMENTO,
FORMAT(FLAN.DATAVENCIMENTO, 'dd/MM/yyyy') AS DATA_VENCIMENTO,
FORMAT(FLANBAIXA.DATABAIXA, 'dd/MM/yyyy')AS DATA_BAIXA,
CONVERT (DECIMAL(10,2), FLANBAIXA.VALORORIGINAL) AS  VALORORIGINAL,
CONVERT (DECIMAL(10,2), FLANBAIXA.VALORBAIXA)AS VALORBAIXA,
CONVERT (DECIMAL(10,2), FLANBAIXA.VALORJUROS) AS VALORJUROS,
CONVERT (DECIMAL(10,2), FLANBAIXA.VALORDESCONTO) AS VALORDESCONTO, 
CONVERT (DECIMAL(10,2), FLAN.VALORBAIXADO) AS VALORFINAL,
CONVERT (DECIMAL(10,2), FLANBAIXA.VALOROP8) AS HONORARIOS,
CONVERT(VARCHAR,FLANCOMPL.COBRANCA) AS COBRANCA
--CONCAT(XCOMPONENTE.COD_COMPN ,+' - ', + XCOMPONENTE.DSC_COMPN) AS CODCOMPN

FROM FLAN (NOLOCK)

LEFT JOIN GCOLIGADA									(NOLOCK) ON (GCOLIGADA.CODCOLIGADA = FLAN.CODCOLIGADA)
LEFT JOIN FLANBAIXA									(NOLOCK) ON (FLANBAIXA.IDLAN = FLAN.IDLAN AND FLANBAIXA.CODCOLIGADA = FLAN.CODCOLIGADA)
LEFT JOIN FLANCOMPL									(NOLOCK) ON (FLANCOMPL.IDLAN = FLAN.IDLAN AND FLANCOMPL.CODCOLIGADA = GCOLIGADA.CODCOLIGADA )
LEFT JOIN XEMPREENDIMENTO						(NOLOCK) ON (XEMPREENDIMENTO.CODCOLIGADA = GCOLIGADA.CODCOLIGADA)
LEFT JOIN GFILIAL											(NOLOCK) ON (GFILIAL.CODFILIAL = XEMPREENDIMENTO.CODFILIAL AND GFILIAL.CODCOLIGADA = XEMPREENDIMENTO.CODCOLIGADA)
LEFT JOIN XVENDA											(NOLOCK) ON (GCOLIGADA.CODCOLIGADA = XVENDA.CODCOLIGADA)
LEFT JOIN FCFO												(NOLOCK) ON (XVENDA.CODCFO = FCFO.CODCFO AND XVENDA.CODCOLCFO = FCFO.CODCOLIGADA)
LEFT JOIN XVENDAPARCELA							(NOLOCK) ON (XVENDAPARCELA.NUMVENDA = XVENDA.NUM_VENDA AND XVENDAPARCELA.CODCOLIGADA = GCOLIGADA.CODCOLIGADA)
--INNER JOIN XCOMPONENTE						(NOLOCK) ON (XCOMPONENTE.COD_TIPO_COMPN = XVENDAPARCELA.COD_TIPO_COMPN)

WHERE GCOLIGADA.CODCOLIGADA =  33
--AND FCFO.NOMEFANTASIA = 'RONALD%'
AND FCFO.CGCCFO = '427.399.258-24'
--AND FLANBAIXA.DATABAIXA >= '20200101'
AND FLANCOMPL.COBRANCA IS NOT NULL
--AND XCOMPONENTE.DSC_COMPN IN('Adiant.Escritura/ITBI-P.CHAVES', 
--'Adiantamento Escritura/ITBI', 'ADIANTAMENTO REGISTRO', 'Anual', 'Anual Parcelada', 'Bimestral', 'C.CREDITO- ADIANT ESCRIT/ITBI', 'CM ADIANTAMENTO ESCRITURA/ITBI','CM Antes Aditivo', 
--'CM Antes Entrega', 'CM Apos Entrega', 'CM EMOLUMENTOS', 'Complemento de Ato', 'Correção e Juros S/Financ.', 'EMOLUMENTOS - IPCA E JUROS', 'Emolumentos Cartorários', 'Entrada', 
--'Financiamento', 'Financiamento Fixo', 'Financiamento SFH', 'IPTU', 'ITBI/REGISTRO', 'ITBI/REGISTRO PARCELADO', 'Juros Antes Aditivo', 'Juros Atraso', 'Juros Contratuais M.Indexado', 
--'Juros de Acordo M.Indexado', 'Juros de Mora', 'Juros de Mutuários', 'Juros e Multa Contratual', 'Juros Remuneratórios', 'LAUDÊMIO', 'Mensal','Mensal 2','Mensal 3','Mensal 4','MENSAL FIXO',
--'Multa Atraso','Multa Atraso de Mora','Multa e Juros de Mora','Parcela Chaves','Parcela Condominio','Parcela de Acordo','Parcela Fixa','Parcela Intermediária','Parcela Única','Pentamensal',
--'Quadrimestral','Quitação','Recursos proprios','Reneg. Parc. Anual Cobranca','Reparcelamento IPTU','Residuo','Resíduo CM','Semestral','Semestral 2','Sinal','Taxa de Notificação','Taxa de Transferencia',
--'Taxa IPTU','Taxa Juros Antes Entrega','Taxa Juros Apos Entrega','TAXAS E CUSTAS JUDICIAIS','Trimestral','TRIMESTRAL 2','TRIMESTRAL 3','Tx. Agua/Esgoto/Luz/Telefone')

GROUP BY GCOLIGADA.CODCOLIGADA, 
GFILIAL.CGC,
FLANBAIXA.IDLAN,
GCOLIGADA.NOME,
FCFO.NOMEFANTASIA,
FCFO.CGCCFO,
--XCOMPONENTE.DSC_COMPN,
FLAN.IDLAN,
FLAN.CODCOLIGADA,
FLANBAIXA.IDLAN,
FLAN.DATAVENCIMENTO,
FLANBAIXA.DATABAIXA,
FLANBAIXA.VALORORIGINAL,
FLANBAIXA.VALORBAIXA,
FLANBAIXA.VALORJUROS,
FLANBAIXA.VALORDESCONTO, 
FLAN.VALORBAIXADO,
FLANBAIXA.VALOROP8,
CONVERT(VARCHAR,FLANCOMPL.COBRANCA)




--SELECT * FROM XCOMPONENTE
--SELECT * FROM XLOGCOMPONENTE
--where CODCOLIGADA =  33
--SELECT * FROM gdic
--where coluna like '%compn%'

--select * from FLANINTEGRACAO
