SELECT 
XEMPREENDIMENTO.CNPJ AS CNPJ_EMPREENDIMENTO
,GCOLIGADA.NOME AS NOME_COLIGADA				 
,FORMAT (XVENDA.DAT_VENDA, 'dd/MM/yyyy') AS DATA_VENDA
				,SGI.EMP
				,FCFO.CGCCFO
				,CONVERT (VARCHAR,XEMPREENDIMENTO.COD_PESS_EMPR) + ' - ' + XEMPREENDIMENTO.NOME AS NOME_EMPRE
				,SGI.QUADRA AS UND
				,SGI.LOTE
				,SGI.TIPO_PAG
				,SGI.NUMERO
				,SGI.CLIENTE
				,SGI.VENCIMENTO
				,(CASE WHEN SGI.TIPO_PAG = '101' THEN 'CHAVES' ELSE CONVERT(VARCHAR,SGI.VENCIMENTO,103) END) AS VENCIMENTO_NOVO
				,SGI.VALORHIST
				,SGI.CORRECAO
				,SGI.JUROS
				,SGI.MULTA
				,SGI.MORA
				,SGI.DESCONTO
				,SGI.VALOROP8
				,SGI.VALORRECEBIDO
				,SGI.DATADORECEBIMENTO
				,SGI.SITUACAO
				,SGI.IDLAN
				,SGI.DATAORIG
				,SGI.CODCXA
				,SGI.NUM_VENDA
				,XSITUACAOVENDA.DSC_SIT_VENDA
				,FORMAT (SGI.DAT_VENDA, 'dd/MM/yyyy') AS DAT_VENDA
				,SGI.CODCOLIGADA 
				,XMODALIDADEVENDA.DSC_MOD_VENDA
				,CONVERT(VARCHAR, XMODALIDADEVENDA.COD_MOD_VENDA) + ' - ' +XMODALIDADEVENDA.DSC_MOD_VENDA AS MODALIDADE_VENDA
				,(select FTB2.CODTB2FLX + ' - ' + FTB2.DESCRICAO from FTB2 join FLAN F (nolock) ON (F.CODTB2FLX = FTB2.CODTB2FLX AND F.CODCOLIGADA = FTB2.CODCOLIGADA) where F.IDLAN = SGI.IDLAN and f.codcoligada = sgi.codcoligada) AS CLASS_FIN, XVENDA.NUM_CONT



FROM DBO.REL_SGI_RECEBIDAS_VARIOS_EMP_IMOB (11, '%%' ,'%%','19000101','20230531','19000101','29991231') AS SGI
INNER JOIN XVENDA			(NOLOCK) ON (XVENDA.CODCOLIGADA=SGI.CODCOLIGADA AND XVENDA.NUM_VENDA=SGI.NUM_VENDA AND XVENDA.COD_PESS_EMPR=SGI.EMP)
INNER JOIN XEMPREENDIMENTO	(NOLOCK) ON (XEMPREENDIMENTO.COD_PESS_EMPR = SGI.EMP)
INNER JOIN GCOLIGADA		(NOLOCK) ON (GCOLIGADA.CODCOLIGADA = XEMPREENDIMENTO.CODCOLIGADA)
INNER JOIN XMODALIDADEVENDA (NOLOCK) ON (XMODALIDADEVENDA.COD_MOD_VENDA=XVENDA.COD_MOD_VENDA)
INNER JOIN XSITUACAOVENDA   (NOLOCK) ON (XSITUACAOVENDA.COD_SIT_VENDA = XVENDA.COD_SIT_VENDA)
INNER JOIN FCFO				(NOLOCK) ON (XVENDA.CODCFO = FCFO.CODCFO AND XVENDA.CODCOLCFO = FCFO.CODCOLIGADA)


WHERE SGI.VALORHIST IS NOT NULL
AND SGI.VALORRECEBIDO > 0

ORDER BY  CLIENTE