SELECT 
FCFO.CODCOLIGADA,
FCFO.CODCFO,
FCFO.NOME,
FCFO.CGCCFO,
(CASE
WHEN FCFO.ATIVO = 1 THEN 'SIM'
ELSE 'NÃO' END) AS ATIVO,
(CASE
WHEN FCFO.CFOIMOB = 1 THEN 'SIM'
ELSE 'NÃO' END) AS BLOQUEADO,
FCFO.EMAIL,
FCFO.TELEFONE AS TELEFONE,
FCFO.TELEX AS CELULAR

 

 /* JOIN ALTERADO DEVIDO A CONFLITO CHAMADO 0823-000626*/

FROM FCFO														     (NOLOCK)

LEFT JOIN FCFOCOMPL										     (NOLOCK) ON(FCFO.CODCFO = FCFOCOMPL.CODCFO AND FCFO.CODCOLIGADA = FCFOCOMPL.CODCOLIGADA)

 
LEFT JOIN GDINAM    AS GDOCUMENTACAO				 (NOLOCK) ON (GDOCUMENTACAO.CODCOLIGADA = FCFOCOMPL.CODCOLIGADA AND GDOCUMENTACAO.APLICACAO = 'T' AND GDOCUMENTACAO.CODIGO = '1')
LEFT JOIN GCONSIST AS DOCUMENTACAO				 (NOLOCK) ON (DOCUMENTACAO.CODCOLIGADA = GDOCUMENTACAO.CODCOLIGADA AND DOCUMENTACAO.APLICACAO = 'T' AND DOCUMENTACAO.CODTABELA = '1' AND DOCUMENTACAO.CODINTERNO = FCFOCOMPL.STSDOCUMENTACAO )

LEFT JOIN GDINAM    AS GSTSLICENCAAMBIENTAL   (NOLOCK) ON (GSTSLICENCAAMBIENTAL.CODCOLIGADA = FCFOCOMPL.CODCOLIGADA AND GSTSLICENCAAMBIENTAL.APLICACAO = 'T' AND GSTSLICENCAAMBIENTAL.CODIGO = '1')
LEFT JOIN GCONSIST AS STSLICENCAAMBIENTAL		 (NOLOCK) ON (STSLICENCAAMBIENTAL.CODCOLIGADA = GSTSLICENCAAMBIENTAL.CODCOLIGADA AND STSLICENCAAMBIENTAL.APLICACAO = 'T' AND STSLICENCAAMBIENTAL.CODTABELA = '2' AND STSLICENCAAMBIENTAL.CODINTERNO = FCFOCOMPL.STSLICENCAAMBIENTAL )

LEFT JOIN GDINAM    AS GSTSPOLITICASOCIOAMBI  (NOLOCK) ON (GSTSPOLITICASOCIOAMBI.CODCOLIGADA = FCFOCOMPL.CODCOLIGADA AND GSTSPOLITICASOCIOAMBI.APLICACAO = 'T' AND GSTSPOLITICASOCIOAMBI.CODIGO = '3')
LEFT JOIN GCONSIST AS STSPOLITICASOCIOAMBI    (NOLOCK) ON (STSPOLITICASOCIOAMBI.CODCOLIGADA = GSTSPOLITICASOCIOAMBI.CODCOLIGADA AND STSPOLITICASOCIOAMBI.APLICACAO = 'T' AND STSPOLITICASOCIOAMBI.CODTABELA = '3' AND STSPOLITICASOCIOAMBI.CODINTERNO = FCFOCOMPL.STSPOLITICASOCIOAMBI )

 

WHERE		 FCFO.DATACRIACAO BETWEEN  @DATA_INI AND @DATA_FIM 
				 AND FCFO.PESSOAFISOUJUR <> 'F'
      
/* FCFO.CODCOLIGADA IN (@COLIGADA)  CAMPOS REMOVIDO POIS ESTAVA CAUSANDO CONFLITO NA CONSULTA CHAMADO 0623-001011
   AND FCFOCOMPL.STSDOCUMENTACAO <> ''  
   OR FCFOCOMPL.STSLICENCAAMBIENTAL <> ''
   OR FCFOCOMPL.DATAVALIDADE <> ''
   OR FCFOCOMPL.STSPOLITICASOCIOAMBI <> */