SELECT

GCCUSTO.CODCCUSTO,
CONCAT(CODCCUSTO,' - ', NOME)AS 'DESCRICAO'

FROM GCCUSTO (NOLOCK)
WHERE ATIVO = 'T' 
AND GCCUSTO.CODCOLIGADA IN (1)--(@CODCOLIGADA)
AND GCCUSTO.NOME NOT LIKE '%DESATIVADO%'