SELECT * FROM NOTA_FISCAL WHERE NUMERO_NOTA ='002023186' AND EMPREITEIRO_DESCRICAO = '1ª MEDIÇÃO'
SELECT * FROM NOTA_ITEM WHERE ID_NOTA_FISCAL IN ('66980')
SELECT CODUNDCOMPRA, * FROM CORPORE_RESIDENCIAL..TPRODUTODEF WHERE IDPRD ='22411'

--BEGIN TRAN
--UPDATE NOTA_ITEM SET RM_CODUNDCOMPRA = 'MES' WHERE ID_NOTA_FISCAL IN ('62691','64915')
--COMMIT