SELECT TOP 1 TORC1.CODCCUSTO
FROM TORCAMENTO AS TORC1 
WHERE TORC1.IDPERIODO = TMOVORCAMENTO.IDPERIODO 
AND TMOVORCAMENTO.IDORCAMENTO = TORC1.IDORCAMENTO 
AND TMOVORCAMENTO.CODCOLIGADA = TORC1.CODCOLIGADA
AND TORC1 = @CODCCUSTO