SELECT 
ISNULL(TITMMOVRATCCU.CODCCUSTO,SOLICITACAO.CODCCUSTO),
SOLICITACAO.NUMEROMOV,
SOLICITACAO.USUARIOCRIACAO,
SOLICITACAO.DATAEMISSAO,
SOLICITACAO.CODTMV,
CASE	        WHEN SOLICITACAO.STATUS = 'A' THEN 'PENDENTE' 
		WHEN SOLICITACAO.STATUS = 'G' THEN 'PARC. RECEBIDO' 
		WHEN SOLICITACAO.STATUS = 'C' THEN 'CANCELADA'
		WHEN (SOLICITACAO.STATUS = 'F' AND ODC.STATUS IS NULL) THEN 'CONCLUIDA'
		WHEN SOLICITACAO.STATUS = 'F' THEN 'RECEBIDO' 
		END AS STATUS_SOLICI,
PRD_SOLI.CODIGOPRD,
(SELECT T.DESCRICAO FROM TPRD T WHERE T.CODCOLIGADA = PRD_SOLI.CODCOLIGADA AND T.CODIGOPRD = SUBSTRING(PRD_SOLI.CODIGOPRD, 1,4)),
PRD_SOLI.NOMEFANTASIA,
ITM_SOLI.QUANTIDADETOTAL,
ITM_SOLI.DATAENTREGA,
APROV_SOLI.DATAAPROVACAO,
APROV_SOLI.CODUSUARIO,
TCCOTACAO.CODCOTACAO,

ODC.NUMEROMOV,
ODC.USUARIOCRIACAO,
ODC.DATAEMISSAO,
APROV_ODC.DATAAPROVACAO,
APROV_ODC.CODUSUARIO,
CASE	WHEN ODC.STATUS = 'A' THEN 'PENDENTE' 
		WHEN ODC.STATUS = 'F' THEN 'RECEBIDO' 
		WHEN ODC.STATUS = 'G' THEN 'PARC. RECEBIDO' 
		WHEN ODC.STATUS = 'C' THEN 'CANCELADA' 
		END AS STATUS,


ITM_ODC.QUANTIDADETOTAL,
ITM_ODC.QUANTIDADETOTAL - ITM_ODC.QUANTIDADEARECEBER AS QUANTIDADE_RECEBIDA,
ITM_ODC.QUANTIDADEARECEBER,		
ITM_ODC.DATAENTREGA DATA_ENTREGA_ODC,		
FCFO.NOMEFANTASIA,
FCFO.CONTATO,
FCFO.TELEFONE,
REPLACE (REPLACE (CONVERT (VARCHAR(MAX) ,FCFO.EMAIL),char(13) + char(10),' '),';',' ') AS EMAIL,
MTAREFA.NOME,
REPLACE (REPLACE (CONVERT (VARCHAR(MAX),(SELECT TOP 1 TMOVCOMPL.REPROGRAMACAO FROM TMOVCOMPL (NOLOCK) WHERE TMOVCOMPL.IDMOV = ODC.IDMOV AND TMOVCOMPL.CODCOLIGADA = ODC.CODCOLIGADA)),char(13) + char(10),' '),';',' ')AS REPROGRAMACAO,
REPLACE (REPLACE (CONVERT (VARCHAR(MAX),(SELECT TOP 1 TMOVHISTORICO.HISTORICOLONGO FROM TMOVHISTORICO (NOLOCK) WHERE TMOVHISTORICO.IDMOV = ODC.IDMOV AND TMOVHISTORICO.CODCOLIGADA = ODC.CODCOLIGADA)),char(13) + char(10),' '),';',' ')AS HISTORICO_ODC,
SOLICITACAO.CODCOLIGADA,
SOLICITACAO.CODFILIAL,
TVEN.NOME AS COMPRADOR,
ITM_ODC.PRECOUNITARIO AS PRECO_ODC,
ISNULL(GCCUSTO.NOME,NOME_CCUSTO_RAT.NOME),
ITM_SOLI.PRECOUNITARIO AS PRECO_SOLI,
ITM_SOLI.NSEQITMMOV,
CASE WHEN TCCOTACAO.STSCOTACAO = 1 THEN 'EM COMPOSICAO'
     WHEN TCCOTACAO.STSCOTACAO = 2 THEN 'AGUARDANDO RESPOSTA DO FORNECEDOR'
	 WHEN TCCOTACAO.STSCOTACAO = 3 THEN 'PRONTO PARA CÁLCULO (STATUS INTERNO)'
	 WHEN TCCOTACAO.STSCOTACAO = 4 THEN 'PRONTO PARA CALCULAR O QUADRO COMPARATIVO'
	 WHEN TCCOTACAO.STSCOTACAO = 5 THEN 'EM NEGOCIACAO'
	 WHEN TCCOTACAO.STSCOTACAO = 6 THEN 'PEDIDO DE COMPRA GERADO' 
	 WHEN TCCOTACAO.STSCOTACAO = 7 THEN 'CANCELADA'
	 WHEN TCCOTACAO.STSCOTACAO = 8 THEN 'LIBERADA'
	 WHEN TCCOTACAO.STSCOTACAO = 9 THEN 'COTAÇÃO EXPORTADA'
	 END  AS STATUS


FROM TMOV AS SOLICITACAO



LEFT JOIN TITMMOV AS ITM_SOLI		(NOLOCK) ON (ITM_SOLI.IDMOV = SOLICITACAO.IDMOV AND ITM_SOLI.CODCOLIGADA = SOLICITACAO.CODCOLIGADA)
LEFT JOIN TITMMOVRATCCU				(NOLOCK) ON (ITM_SOLI.IDMOV = TITMMOVRATCCU.IDMOV AND ITM_SOLI.CODCOLIGADA = TITMMOVRATCCU.CODCOLIGADA AND TITMMOVRATCCU.NSEQITMMOV = ITM_SOLI.NSEQITMMOV)
LEFT JOIN TMOVAPROVA AS APROV_SOLI	(NOLOCK) ON (APROV_SOLI.IDMOV = SOLICITACAO.IDMOV AND APROV_SOLI.CODCOLIGADA = SOLICITACAO.CODCOLIGADA AND APROV_SOLI.TIPOAPROVACAO = 1)
LEFT JOIN TPRD AS PRD_SOLI			(NOLOCK) ON (PRD_SOLI.IDPRD = ITM_SOLI.IDPRD AND PRD_SOLI.CODCOLIGADA = ITM_SOLI.CODCOLIGADA)
LEFT JOIN TCCOTACAOITMMOV			(NOLOCK) ON (TCCOTACAOITMMOV.IDMOV = ITM_SOLI.IDMOV AND TCCOTACAOITMMOV.NSEQITMMOV = ITM_SOLI.NSEQITMMOV AND TCCOTACAOITMMOV.CODCOLIGADA = ITM_SOLI.CODCOLIGADA)			 
LEFT JOIN TCCOTACAO              	(NOLOCK) ON (TCCOTACAOITMMOV.CODCOLIGADA = TCCOTACAO.CODCOLIGADA AND TCCOTACAOITMMOV.CODCOTACAO = TCCOTACAO.CODCOTACAO AND TCCOTACAO.STSCOTACAO <> 7)
INNER JOIN TVEN						(NOLOCK) ON (TCCOTACAO.CODCOLIGADA = TVEN.CODCOLIGADA AND TCCOTACAO.CODCOMPRADOR = TVEN.CODVEN)

LEFT JOIN TITMMOVRELAC				(NOLOCK) ON (TITMMOVRELAC.IDMOVORIGEM = ITM_SOLI.IDMOV AND TITMMOVRELAC.NSEQITMMOVORIGEM = ITM_SOLI.NSEQITMMOV AND TITMMOVRELAC.CODCOLORIGEM = ITM_SOLI.CODCOLIGADA)
LEFT JOIN TITMMOV AS ITM_ODC		(NOLOCK) ON (TITMMOVRELAC.IDMOVDESTINO = ITM_ODC.IDMOV AND TITMMOVRELAC.NSEQITMMOVDESTINO = ITM_ODC.NSEQITMMOV AND TITMMOVRELAC.CODCOLDESTINO = ITM_ODC.CODCOLIGADA)
LEFT JOIN TMOV AS ODC				(NOLOCK) ON (ITM_ODC.IDMOV = ODC.IDMOV AND ITM_ODC.CODCOLIGADA = ODC.CODCOLIGADA)
LEFT JOIN TMOVAPROVA AS APROV_ODC	(NOLOCK) ON (APROV_ODC.IDMOV = ODC.IDMOV AND APROV_ODC.CODCOLIGADA = ODC.CODCOLIGADA AND APROV_ODC.TIPOAPROVACAO = 1)
LEFT JOIN FCFO						(NOLOCK) ON (FCFO.CODCFO = ODC.CODCFO AND FCFO.CODCOLIGADA = ODC.CODCOLCFO)
LEFT JOIN MTAREFA					(NOLOCK) ON (ITM_ODC.IDPRJ = MTAREFA.IDPRJ AND ITM_ODC.IDTRF = MTAREFA.IDTRF AND ITM_ODC.CODCOLIGADA = MTAREFA.CODCOLIGADA)
LEFT JOIN GCCUSTO					(NOLOCK) ON (SOLICITACAO.CODCCUSTO = GCCUSTO.CODCCUSTO AND SOLICITACAO.CODCOLIGADA = GCCUSTO.CODCOLIGADA)
LEFT JOIN GCCUSTO AS NOME_CCUSTO_RAT	(NOLOCK) ON (TITMMOVRATCCU.CODCCUSTO = NOME_CCUSTO_RAT.CODCCUSTO AND TITMMOVRATCCU.CODCOLIGADA = NOME_CCUSTO_RAT.CODCOLIGADA)

WHERE	SOLICITACAO.CODTMV  IN ('1.1.18', '1.1.20','1.1.25')
AND		(SOLICITACAO.STATUS NOT IN('C','F') OR (SOLICITACAO.STATUS = 'F' AND TCCOTACAO.CODCOTACAO IS NOT NULL))
AND		SOLICITACAO.DATACRIACAO BETWEEN '20230101' AND '20230928'
/*AND   ISNULL(TITMMOVRATCCU.CODCCUSTO,SOLICITACAO.CODCCUSTO) BETWEEN :CCUSTO_INI_S AND :CCUSTO_FIN_S*/
GROUP BY
TITMMOVRATCCU.CODCCUSTO,
SOLICITACAO.CODCCUSTO,
GCCUSTO.NOME,
NOME_CCUSTO_RAT.NOME,
SOLICITACAO.NUMEROMOV,
SOLICITACAO.USUARIOCRIACAO,
SOLICITACAO.DATAEMISSAO,
SOLICITACAO.CODTMV,
SOLICITACAO.STATUS,
PRD_SOLI.CODIGOPRD,
PRD_SOLI.NOMEFANTASIA,
PRD_SOLI.CODCOLIGADA,
SOLICITACAO.CODCOLIGADA,
SOLICITACAO.CODFILIAL,

ITM_SOLI.QUANTIDADETOTAL,
ITM_SOLI.DATAENTREGA,
ITM_SOLI.PRECOUNITARIO,
ITM_SOLI.NSEQITMMOV,
APROV_SOLI.DATAAPROVACAO,
APROV_SOLI.CODUSUARIO,
TCCOTACAO.CODCOTACAO,
TCCOTACAO.STSCOTACAO,

ODC.NUMEROMOV,
ODC.USUARIOCRIACAO,
ODC.DATAEMISSAO,
ODC.IDMOV,
ODC.CODCOLIGADA,
APROV_ODC.DATAAPROVACAO,
APROV_ODC.CODUSUARIO,
ODC.STATUS,

ITM_ODC.QUANTIDADETOTAL,
ITM_ODC.QUANTIDADEARECEBER,		
ITM_ODC.DATAENTREGA,
FCFO.NOMEFANTASIA,
FCFO.CONTATO,
FCFO.TELEFONE,
FCFO.EMAIL,
MTAREFA.NOME,
TVEN.NOME,
ITM_ODC.PRECOUNITARIO


/* INSERIDO POR MARCELO WAGNER PARA TRAZER AS ODCS QUE NÃO POSSUEM SOLICITAÇÃO */


UNION ALL


SELECT 
NULL,NULL,NULL,NULL,NULL,NULL,TPRD.CODIGOPRD,
(SELECT T.DESCRICAO FROM TPRD T WHERE T.CODCOLIGADA = TPRD.CODCOLIGADA AND  T.CODIGOPRD = SUBSTRING(TPRD.CODIGOPRD, 1,4)),
TPRD.NOMEFANTASIA,NULL,NULL,NULL,NULL,NULL,
ODC.NUMEROMOV,
ODC.USUARIOCRIACAO,
ODC.DATAEMISSAO,
APROV_ODC.DATAAPROVACAO,
APROV_ODC.CODUSUARIO,
CASE	WHEN ODC.STATUS = 'A' THEN 'PENDENTE' 
		WHEN ODC.STATUS = 'F' THEN 'RECEBIDO' 
		WHEN ODC.STATUS = 'G' THEN 'PARC. RECEBIDO' 
		WHEN ODC.STATUS = 'C' THEN 'CANCELADA' 
		WHEN ODC.STATUS = 'U' THEN 'EM FATURAMENTO'
		ELSE ODC.STATUS
		END AS STATUS,


ITM_ODC.QUANTIDADETOTAL,
ITM_ODC.QUANTIDADETOTAL - ITM_ODC.QUANTIDADEARECEBER AS QUANTIDADE_RECEBIDA,
ITM_ODC.QUANTIDADEARECEBER,		
ITM_ODC.DATAENTREGA DATA_ENTREGA_ODC,		
FCFO.NOMEFANTASIA,
FCFO.CONTATO,
FCFO.TELEFONE,
REPLACE (REPLACE (CONVERT (VARCHAR(MAX) ,FCFO.EMAIL),char(13) + char(10),' '),';',' ') AS EMAIL,
MTAREFA.NOME,
REPLACE (REPLACE (CONVERT (VARCHAR(MAX),(SELECT TOP 1 TMOVCOMPL.REPROGRAMACAO FROM TMOVCOMPL WHERE TMOVCOMPL.IDMOV = ODC.IDMOV AND TMOVCOMPL.CODCOLIGADA = ODC.CODCOLIGADA)),char(13) + char(10),' '),';',' ')AS REPROGRAMACAO,
REPLACE (REPLACE (CONVERT (VARCHAR(MAX) ,TMOVHISTORICO.HISTORICOLONGO),char(13) + char(10),' '),';',' ') AS HISTORICOLONGO,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL



FROM TMOV AS ODC

LEFT JOIN TITMMOV AS ITM_ODC		(NOLOCK) ON (ITM_ODC.IDMOV = ODC.IDMOV AND ITM_ODC.CODCOLIGADA = ODC.CODCOLIGADA)
LEFT JOIN TPRD						(NOLOCK) ON (TPRD.IDPRD = ITM_ODC.IDPRD AND TPRD.CODCOLIGADA = ITM_ODC.CODCOLIGADA)
LEFT JOIN TMOVAPROVA AS APROV_ODC	(NOLOCK) ON (APROV_ODC.IDMOV = ODC.IDMOV AND APROV_ODC.CODCOLIGADA = ODC.CODCOLIGADA AND APROV_ODC.TIPOAPROVACAO = 1)
LEFT JOIN FCFO						(NOLOCK) ON (FCFO.CODCFO = ODC.CODCFO AND FCFO.CODCOLIGADA = ODC.CODCOLCFO)
LEFT JOIN MTAREFA					(NOLOCK) ON (ITM_ODC.IDPRJ = MTAREFA.IDPRJ AND ITM_ODC.IDTRF = MTAREFA.IDTRF and ITM_ODC.CODCOLIGADA = MTAREFA.CODCOLIGADA)
LEFT JOIN TMOVHISTORICO				(NOLOCK) ON (TMOVHISTORICO.IDMOV = ODC.IDMOV AND TMOVHISTORICO.CODCOLIGADA = ODC.CODCOLIGADA)

WHERE	ODC.IDMOV NOT IN (SELECT IDMOVDESTINO FROM TMOVRELAC)
AND		ODC.CODTMV  IN ('1.1.21','1.1.26')
AND		ODC.STATUS <> 'C'
AND		ODC.DATACRIACAO BETWEEN '20230101' AND '20230928'

/*AND		ODC.CODCCUSTO BETWEEN :CCUSTO_INI_S AND :CCUSTO_FIN_S*/


ORDER BY 2,11