(SELECT 
QUANTIDADEARECEBER,
QUANTIDADETOTAL,
(CASE
	  WHEN ITEM_ODC.QUANTIDADEARECEBER > 0 THEN 'PROGRAMADO' 
	  WHEN ITEM_ODC.QUANTIDADEARECEBER = 0 THEN 'RECEBIDO'
	  WHEN ITEM_ODC.QUANTIDADEARECEBER < ITEM_ODC.QUANTIDADETOTAL THEN 'PARCIALMENTE RECEBIDO'
	  ELSE 'PENDENTE'		
END) AS 'STATUS_ITENS'
FROM TITMMOV as ITEM_ODC
WHERE 
	 (CASE
	  WHEN ITEM_ODC.QUANTIDADEARECEBER >0 THEN 'PROGRAMADO' 
	  WHEN ITEM_ODC.QUANTIDADEARECEBER = 0 THEN 'RECEBIDO'
	  WHEN ITEM_ODC.QUANTIDADEARECEBER < ITEM_ODC.QUANTIDADETOTAL THEN 'PARCIALMENTE RECEBIDO'
	  ELSE 'PENDENTE' END)=(@STATUS)) 
