--CONSULTA COLIGADA COM MOVIMENTAÇÃO
SELECT CODCOLIGADA, MAX(DATACRIACAO) AS DATACRIACAO
FROM TMOV
WHERE (CODCOLIGADA =1 OR CODCOLIGADA >=10)
GROUP BY CODCOLIGADA


select * from psecao where codigo  <= '02.001.05' and codcoligada = 31