DECLARE @ATIVACAO_PARCIAL AS VARCHAR,
				 @ATIVACAO_RM AS VARCHAR;

SET @ATIVACAO_RM = 0
SET @ATIVACAO_PARCIAL = 'T'



SELECT
TPRD.IDPRD,
TPRD.CODIGOPRD,
TPRD.NOMEFANTASIA,
TPRD.CODCOLIGADA,
TPRD.CODUNDCONTROLE,
TPRD.CODUNDCOMPRA,
TPRD.CODUNDVENDA,
TPRDCOMPL.PERMITECOMPRANUCLEUS,
TPRD.CAMPOLIVRE,
TPRD.DTCADASTRAMENTO,
(CASE WHEN TPRD.INATIVO = 0 THEN 'ATIVO' ELSE 'INATIVO' END) AS INATIVACAO_COMPLETA,
(CASE WHEN TPRDCOMPL.INATIVO = 'T' THEN 'PARCIALMENTE INATIVO' 
			ELSE 'ATIVO' END) AS INATIVACAO_PARCIAL

FROM TPRD													(NOLOCK)
LEFT JOIN TPRDCOMPL								(NOLOCK) ON TPRD.IDPRD = TPRDCOMPL.IDPRD AND TPRD.CODCOLIGADA = TPRDCOMPL.CODCOLIGADA

WHERE TPRD.INATIVO = 0
AND TPRD.CODCOLIGADA IN(@CODCOLIGADA)
AND LEFT(TPRD.CODIGOPRD,4) IN(@GRUPO)
AND CONVERT(VARCHAR, TPRD.INATIVO) IN (@ATIVACAO_RM) 
AND CONVERT(VARCHAR, TPRDCOMPL.INATIVO) IN (@ATIVACAO_PARCIAL)
AND TPRD.ULTIMONIVEL = 1
AND TPRD.TIPO = 'P'
