DECLARE @COMANDO VARCHAR(MAX),
        /*@COMANDO2 VARCHAR(50),*/
        @DATA NVARCHAR(10) 

SET @DATA = :ESPELHO#32

SET @DATA = CONVERT(NVARCHAR(10), CONVERT(DATETIME, @DATA, 103), 112)

SET @COMANDO = 'exec zz_pegadata ' + '''' + @DATA + ''''

EXECUTE (@COMANDO)

SELECT @COMANDO AS com
 FROM GCOLIGADA (NOLOCK) WHERE CODCOLIGADA = 0