SELECT 

TMOV.IDMOV ,
TMOV.DATAEMISSAO,
/*(Select  top 1 DATAVENCIMENTO from flan where flan.IDMOV=TMOV.IDMOV and flan.CODCOLIGADA=TMOV.CODCOLIGADA )as VENCIMENTO,*/
(CASE WHEN (Select  top 1 DATAVENCIMENTO from flan where flan.IDMOV=TMOV.IDMOV and flan.CODCOLIGADA=TMOV.CODCOLIGADA) IS NULL THEN F_FATURADO.DATAVENCIMENTO ELSE (Select  top 1 DATAVENCIMENTO from flan where flan.IDMOV=TMOV.IDMOV and flan.CODCOLIGADA=TMOV.CODCOLIGADA)END),
TMOV.CODFILIAL,
TMOV.CODTMV,
FCFO.NOME,
TMOV.CODCCUSTO,
(case when TMOV.VALORLIQUIDO = '0' then RECEBIMENTO.VALORLIQUIDO ELSE TMOV.VALORLIQUIDO END) AS VALORLIQUIDO,
GCCUSTO.NOME,
TMOV.NUMEROMOV,
TMOV.USUARIOCRIACAO ,
GUSUARIO.NOME,
CASE WHEN TMOVHISTORICO.HISTORICOLONGO IS NULL THEN TMOVHISTORICO.HISTORICOCURTO ELSE TMOVHISTORICO.HISTORICOLONGO END AS HISTORICO,
TMOV.CODTB2FLX + ' - ' + (SELECT DESCRICAO FROM FTB2 WHERE TMOV.CODTB2FLX = FTB2.CODTB2FLX AND TMOV.CODCOLIGADA = FTB2.CODCOLIGADA),
CASE WHEN TMOVCOMPL.PRJ_ESTUDO IS NOT NULL THEN 'PROJETO EM ESTUDO: ' + TMOVCOMPL.PRJ_ESTUDO ELSE '' END AS PRJ_ESTUDO,
UPPER(GUSUARIO.NOME) AS EMITENTE,
APROVADOR.NOME AS CHEFE_DE_SECAO

 FROM TMOV (NOLOCK)
LEFT JOIN FCFO (NOLOCK) ON TMOV.CODCOLCFO = FCFO.CODCOLIGADA AND TMOV.CODCFO = FCFO.CODCFO 
LEFT JOIN GUSUARIO (NOLOCK) ON TMOV.USUARIOCRIACAO = GUSUARIO.CODUSUARIO 
LEFT JOIN TMOVHISTORICO (NOLOCK) ON  TMOV.CODCOLIGADA = TMOVHISTORICO.CODCOLIGADA AND TMOV.IDMOV = TMOVHISTORICO.IDMOV
LEFT JOIN GCCUSTO (NOLOCK) ON TMOV.CODCOLIGADA = GCCUSTO.CODCOLIGADA AND TMOV.CODCCUSTO = GCCUSTO.CODCCUSTO
LEFT JOIN TMOVCOMPL (NOLOCK) ON (TMOVCOMPL.CODCOLIGADA = TMOV.CODCOLIGADA AND TMOVCOMPL.IDMOV = TMOV.IDMOV)

/*AJUSTADO PARA ATENDER A DEMANDA DE HOME OFFICE*/

LEFT JOIN TMOVAPROVA (NOLOCK) ON (TMOVAPROVA.IDMOV = TMOV.IDMOV AND TMOVAPROVA.CODCOLIGADA = TMOV.CODCOLIGADA and TMOVAPROVA.TIPOAPROVACAO <> 2)
LEFT JOIN GUSUARIO AS APROVADOR (NOLOCK) ON (APROVADOR.CODUSUARIO = TMOVAPROVA.CODUSUARIO)
LEFT JOIN TMOVRELAC (NOLOCK) ON (TMOVRELAC.IDMOVORIGEM = TMOV.IDMOV  AND TMOVRELAC.CODCOLORIGEM = TMOV.CODCOLIGADA)
LEFT JOIN TMOV AS RECEBIMENTO (NOLOCK) ON (RECEBIMENTO.IDMOV = TMOVRELAC.IDMOVDESTINO AND RECEBIMENTO.CODCOLIGADA = TMOVRELAC.CODCOLDESTINO)
LEFT JOIN FLAN AS F_FATURADO (NOLOCK) ON (F_FATURADO.IDMOV = TMOVRELAC.IDMOVDESTINO AND F_FATURADO.CODCOLIGADA = TMOVRELAC.CODCOLDESTINO)

WHERE 
/*TMOV.CODCOLIGADA =:P_CODCOLIGADA_N*/
TMOV.CODCOLIGADA = :ESPELHO#2
AND TMOV.CODTMV IN ('1.1.15','1.1.19','1.1.23','1.1.42','1.1.60','1.1.61','1.1.62','1.1.51','1.1.81',
                  '1.1.43','1.1.40','1.1.41','1.1.49','1.1.46','1.1.66','1.1.63','1.1.24','1.2.22','1.1.64','1.1.88')

AND TMOV.USUARIOCRIACAO =:USUARIO_S
AND TMOV.IDMOV >=:IDINICIAL_S
AND TMOV.IDMOV <=:IDFINAL_S
/*AJUSTADO HOMEOFFIC*/
AND TMOV.STATUS NOT IN ('C','Q')
/*AND TMOV.STATUS NOT IN ('C','F','Q')*/


ORDER BY 
TMOV.CODFILIAL,
TMOV.CODTMV,
TMOV.CODCCUSTO,
TMOV.USUARIOCRIACAO,
TMOV.IDMOV,
TMOV.DATACRIACAO
