	  SELECT DISTINCT (CASE
	  WHEN ITEM_ODC_2.QUANTIDADEARECEBER > 0 THEN 'PROGRAMADO' 
	  WHEN ITEM_ODC_2.QUANTIDADEARECEBER = 0 THEN 'RECEBIDO'
	  WHEN ITEM_ODC_2.QUANTIDADEARECEBER < ITEM_ODC_2.QUANTIDADETOTAL THEN 'PARCIALMENTE RECEBIDO'
	  ELSE 'PENDENTE'
	  END) 
	  FROM TITMMOV AS ITEM_ODC_2
	  
	  WHERE ITEM_ODC_2.DATAENTREGA BETWEEN '20230101' AND '20230901'
	  AND ITEM_ODC_2.CODCOLIGADA IN ('1')
	  AND 
