SELECT 

CORPORE_RESIDENCIAL.dbo.DIAS_UTEIS(CONVERT (DATE,GRUPO.DATA_CRIACAO),CONVERT (DATE,GRUPO.ULTIMA_DATA_APRV_ENGENHARIA)) AS CRIACAO_ULTIMA_APROV_ENG,
CORPORE_RESIDENCIAL.dbo.DIAS_UTEIS(CONVERT (DATE,GRUPO.DATA_CRIACAO),CONVERT (DATE,GRUPO.PRIMEIRA_DATA_APRV_ENGENHARIA)) AS CRIACAO_PRIMEIRA_APROV_ENG,
CORPORE_RESIDENCIAL.dbo.DIAS_UTEIS(CONVERT (DATE,GRUPO.DATA_CRIACAO),CONVERT (DATE,GRUPO.PRIMEIRA_DATA_CADASTRO)) AS CRIACAO_PRIMEIRO_CADASTRO,
CORPORE_RESIDENCIAL.dbo.DIAS_UTEIS(CONVERT (DATE,GRUPO.PRIMEIRA_DATA_CADASTRO),CONVERT (DATE,GRUPO.PRIMEIRA_DATA_APRV_ENGENHARIA)) AS CADASTRO_PRIMEIRA_APROV_ENG,
CORPORE_RESIDENCIAL.dbo.DIAS_UTEIS(CONVERT (DATE,GRUPO.PRIMEIRA_DATA_APRV_ENGENHARIA),CONVERT (DATE,GRUPO.PRIMEIRA_DATA_DESAPROVACAO)) AS PRIMEIRA_APROV_ENG_PRIMEIRA_DESAPROV,
CORPORE_RESIDENCIAL.dbo.DIAS_UTEIS(CONVERT (DATE,GRUPO.ULTIMA_DATA_APRV_ENGENHARIA),CONVERT (DATE,GRUPO.ULTIMA_DATA_APRV_CONTROLE)) AS ULTIMA_APROV_ENG_ULTIMA_APROV_CONTROLE,
CORPORE_RESIDENCIAL.dbo.DIAS_UTEIS(CONVERT (DATE,GRUPO.DATA_CRIACAO),CONVERT (DATE,GRUPO.ULTIMA_DATA_APRV_CONTROLE)) AS CRIACAO_ULTIMA_APROV_CONTROLE,





(SELECT MIN (FICHA_PREENCHIDA.DAT_INICIO_SERVICO) FROM qualidade.FICHA_PREENCHIDA (NOLOCK)
INNER JOIN qualidade.FICHA_VERIFICACAO_EMPREENDIMENTO	(NOLOCK) ON (FICHA_VERIFICACAO_EMPREENDIMENTO.ID_FICHA_VERIFICACAO_EMPREENDIMENTO = FICHA_PREENCHIDA.ID_FICHA_VERIFICACAO_EMPREENDIMENTO)

WHERE	FICHA_PREENCHIDA.ID_OBRA IN (SELECT ID_OBRA FROM OBRA WHERE OBRA.ID_EMPREENDIMENTO = GRUPO.ID_EMPREENDIMENTO)
AND		FICHA_VERIFICACAO_EMPREENDIMENTO.ID_ITEM_EMPREENDIMENTO = GRUPO.ID_ITEM_EMPREENDIMENTO) AS DATA_INICIO_SERVICO,

(SELECT TOP 1 SUBSTRING(aspnet_Users.UserName,9,100) FROM qualidade.FICHA_PREENCHIDA (NOLOCK)
INNER JOIN qualidade.FICHA_VERIFICACAO_EMPREENDIMENTO (NOLOCK) ON (FICHA_VERIFICACAO_EMPREENDIMENTO.ID_FICHA_VERIFICACAO_EMPREENDIMENTO = FICHA_PREENCHIDA.ID_FICHA_VERIFICACAO_EMPREENDIMENTO)
INNER JOIN aspnet_Users (NOLOCK) ON (aspnet_Users.UserId = FICHA_PREENCHIDA.UserId)
WHERE	FICHA_PREENCHIDA.ID_OBRA IN (SELECT ID_OBRA FROM OBRA WHERE OBRA.ID_EMPREENDIMENTO = GRUPO.ID_EMPREENDIMENTO)
AND		FICHA_VERIFICACAO_EMPREENDIMENTO.ID_ITEM_EMPREENDIMENTO = GRUPO.ID_ITEM_EMPREENDIMENTO ORDER BY FICHA_PREENCHIDA.DAT_INICIO_SERVICO) AS USUARIO_VERIFICADOR,

*

FROM 

(SELECT 

EMPREENDIMENTO.ID_EMPREENDIMENTO,
EMPREENDIMENTO.NOM_EMPREENDIMENTO,
ITEM_EMPREENDIMENTO.CODIGO,
ITEM_EMPREENDIMENTO.NOM_ITEM,
GRUPO_ITEM.ID_GRUPO_ITEM,
GRUPO_ITEM.NOM_GRUPO_ITEM,
UNIDADE_MEDIDA.SIGLA,
ITEM_EMPREENDIMENTO.ID_ITEM_EMPREENDIMENTO,
ITEM_EMPREENDIMENTO.PRECO_UNITARIO,
ITEM_EMPREENDIMENTO.PRECO_ORCADO,
SUM (ITEM_EMPREENDIMENTO_OBRA.QUANTIDADE_MAX) AS QUANTIDADE_MAX, /*QUANTIDADE SOMADA */
ITEM_EMPREENDIMENTO.PRECO_UNITARIO * SUM (ITEM_EMPREENDIMENTO_OBRA.QUANTIDADE_MAX) AS PRECO_TOTAL_REAL,
ITEM_EMPREENDIMENTO.PRECO_ORCADO * SUM (ITEM_EMPREENDIMENTO_OBRA.QUANTIDADE_MAX) AS PRECO_TOTAL_ORCADO,
(SELECT SUBSTRING (ASPNET_USERS.USERNAME,9,100) FROM ASPNET_USERS (NOLOCK) WHERE USERID = USERID_CRIACAO) AS USUARIO_CRIACAO,
(SELECT MIN (DAT_HISTORICO) FROM ITEM_EMPREENDIMENTO_HISTORICO (NOLOCK) WHERE ID_ETAPA = 1 AND ID_ITEM_EMPREENDIMENTO = ITEM_EMPREENDIMENTO.ID_ITEM_EMPREENDIMENTO) AS DATA_CRIACAO,


/* CADASTRO */

(SELECT SUBSTRING (ASPNET_USERS.USERNAME,9,100) FROM ITEM_EMPREENDIMENTO_HISTORICO (NOLOCK) 
INNER JOIN ASPNET_USERS(NOLOCK) ON (ITEM_EMPREENDIMENTO_HISTORICO.USERID = ASPNET_USERS.USERID) WHERE ID_ITEM_EMPREENDIMENTO_HISTORICO = (SELECT MAX(ITEM_EMPREENDIMENTO_HISTORICO.ID_ITEM_EMPREENDIMENTO_HISTORICO) FROM ITEM_EMPREENDIMENTO_HISTORICO (NOLOCK) WHERE ID_ETAPA = 2 AND ID_ITEM_EMPREENDIMENTO = ITEM_EMPREENDIMENTO.ID_ITEM_EMPREENDIMENTO)) AS ULTIMO_USUARIO_CADASTRO,
(SELECT MAX (DAT_HISTORICO) FROM ITEM_EMPREENDIMENTO_HISTORICO WHERE ID_ETAPA = 2 AND ID_ITEM_EMPREENDIMENTO = ITEM_EMPREENDIMENTO.ID_ITEM_EMPREENDIMENTO) AS ULTIMA_DATA_CADASTRO,


(SELECT SUBSTRING (ASPNET_USERS.USERNAME,9,100) FROM ITEM_EMPREENDIMENTO_HISTORICO (NOLOCK) 
INNER JOIN ASPNET_USERS(NOLOCK) ON (ITEM_EMPREENDIMENTO_HISTORICO.USERID = ASPNET_USERS.USERID) WHERE ID_ITEM_EMPREENDIMENTO_HISTORICO = (SELECT MIN(ITEM_EMPREENDIMENTO_HISTORICO.ID_ITEM_EMPREENDIMENTO_HISTORICO) FROM ITEM_EMPREENDIMENTO_HISTORICO (NOLOCK) WHERE ID_ETAPA = 2 AND ID_ITEM_EMPREENDIMENTO = ITEM_EMPREENDIMENTO.ID_ITEM_EMPREENDIMENTO)) AS PRIMEIRO_USUARIO_CADASTRO,
(SELECT MIN (DAT_HISTORICO) FROM ITEM_EMPREENDIMENTO_HISTORICO WHERE ID_ETAPA = 2 AND ID_ITEM_EMPREENDIMENTO = ITEM_EMPREENDIMENTO.ID_ITEM_EMPREENDIMENTO) AS PRIMEIRA_DATA_CADASTRO,




/* ENGENHARIA */
(SELECT SUBSTRING (ASPNET_USERS.USERNAME,9,100) FROM ITEM_EMPREENDIMENTO_HISTORICO (NOLOCK) 
INNER JOIN ASPNET_USERS(NOLOCK) ON (ITEM_EMPREENDIMENTO_HISTORICO.USERID = ASPNET_USERS.USERID) WHERE ID_ITEM_EMPREENDIMENTO_HISTORICO = (SELECT MAX(ITEM_EMPREENDIMENTO_HISTORICO.ID_ITEM_EMPREENDIMENTO_HISTORICO) FROM ITEM_EMPREENDIMENTO_HISTORICO (NOLOCK) WHERE ID_ETAPA = 3 AND ID_ITEM_EMPREENDIMENTO = ITEM_EMPREENDIMENTO.ID_ITEM_EMPREENDIMENTO)) AS ULTIMO_USUARIO_APR_ENGENHARIA,
(SELECT MAX (DAT_HISTORICO) FROM ITEM_EMPREENDIMENTO_HISTORICO WHERE ID_ETAPA = 3 AND ID_ITEM_EMPREENDIMENTO = ITEM_EMPREENDIMENTO.ID_ITEM_EMPREENDIMENTO) AS ULTIMA_DATA_APRV_ENGENHARIA,


(SELECT SUBSTRING (ASPNET_USERS.USERNAME,9,100) FROM ITEM_EMPREENDIMENTO_HISTORICO (NOLOCK) 
INNER JOIN ASPNET_USERS(NOLOCK) ON (ITEM_EMPREENDIMENTO_HISTORICO.USERID = ASPNET_USERS.USERID) WHERE ID_ITEM_EMPREENDIMENTO_HISTORICO = (SELECT MIN(ITEM_EMPREENDIMENTO_HISTORICO.ID_ITEM_EMPREENDIMENTO_HISTORICO) FROM ITEM_EMPREENDIMENTO_HISTORICO (NOLOCK) WHERE ID_ETAPA = 3 AND ID_ITEM_EMPREENDIMENTO = ITEM_EMPREENDIMENTO.ID_ITEM_EMPREENDIMENTO)) AS PRIMEIRO_USUARIO_APR_ENGENHARIA,
(SELECT MIN (DAT_HISTORICO) FROM ITEM_EMPREENDIMENTO_HISTORICO WHERE ID_ETAPA = 3 AND ID_ITEM_EMPREENDIMENTO = ITEM_EMPREENDIMENTO.ID_ITEM_EMPREENDIMENTO) AS PRIMEIRA_DATA_APRV_ENGENHARIA,

/*CONTROLE*/
(SELECT SUBSTRING (ASPNET_USERS.USERNAME,9,100) FROM ITEM_EMPREENDIMENTO_HISTORICO  (NOLOCK)
INNER JOIN ASPNET_USERS(NOLOCK) ON (ITEM_EMPREENDIMENTO_HISTORICO.USERID = ASPNET_USERS.USERID) WHERE ID_ITEM_EMPREENDIMENTO_HISTORICO = (SELECT MAX(ITEM_EMPREENDIMENTO_HISTORICO.ID_ITEM_EMPREENDIMENTO_HISTORICO) FROM ITEM_EMPREENDIMENTO_HISTORICO WHERE ID_ETAPA = 4 AND ID_ITEM_EMPREENDIMENTO = ITEM_EMPREENDIMENTO.ID_ITEM_EMPREENDIMENTO)) AS ULTIMO_USUARIO_APR_CONTROLE,

(SELECT MAX (DAT_HISTORICO) FROM ITEM_EMPREENDIMENTO_HISTORICO (NOLOCK) WHERE ID_ETAPA = 4 AND ID_ITEM_EMPREENDIMENTO = ITEM_EMPREENDIMENTO.ID_ITEM_EMPREENDIMENTO) AS ULTIMA_DATA_APRV_CONTROLE,

(SELECT TOP 1 OBSERVACOES FROM ITEM_EMPREENDIMENTO_HISTORICO (NOLOCK) WHERE ID_ETAPA = 4 AND ID_ITEM_EMPREENDIMENTO = ITEM_EMPREENDIMENTO.ID_ITEM_EMPREENDIMENTO AND DAT_HISTORICO = 
(SELECT MAX (DAT_HISTORICO) FROM ITEM_EMPREENDIMENTO_HISTORICO (NOLOCK) WHERE ID_ETAPA = 4 AND ID_ITEM_EMPREENDIMENTO = ITEM_EMPREENDIMENTO.ID_ITEM_EMPREENDIMENTO) ) AS ULTIMO_HISTORICO_APRV_CONTROLE,

/*DESAPROVAÇÃO*/
(SELECT SUBSTRING (ASPNET_USERS.USERNAME,9,100) FROM ITEM_EMPREENDIMENTO_HISTORICO (NOLOCK)  
INNER JOIN ASPNET_USERS(NOLOCK) ON (ITEM_EMPREENDIMENTO_HISTORICO.USERID = ASPNET_USERS.USERID) WHERE ID_ITEM_EMPREENDIMENTO_HISTORICO = (SELECT MAX(ITEM_EMPREENDIMENTO_HISTORICO.ID_ITEM_EMPREENDIMENTO_HISTORICO) FROM ITEM_EMPREENDIMENTO_HISTORICO (NOLOCK) WHERE ID_ETAPA = 6 AND ID_ITEM_EMPREENDIMENTO = ITEM_EMPREENDIMENTO.ID_ITEM_EMPREENDIMENTO)) AS ULTIMO_USUARIO_DESAPROVAÇAO,

(SELECT MAX (DAT_HISTORICO) FROM ITEM_EMPREENDIMENTO_HISTORICO (NOLOCK) WHERE ID_ETAPA = 6 AND ID_ITEM_EMPREENDIMENTO = ITEM_EMPREENDIMENTO.ID_ITEM_EMPREENDIMENTO) AS ULTIMA_DATA_DESAPROVACAO,


(SELECT SUBSTRING (ASPNET_USERS.USERNAME,9,100) FROM ITEM_EMPREENDIMENTO_HISTORICO (NOLOCK)  
INNER JOIN ASPNET_USERS(NOLOCK) ON (ITEM_EMPREENDIMENTO_HISTORICO.USERID = ASPNET_USERS.USERID) WHERE ID_ITEM_EMPREENDIMENTO_HISTORICO = (SELECT MIN(ITEM_EMPREENDIMENTO_HISTORICO.ID_ITEM_EMPREENDIMENTO_HISTORICO) FROM ITEM_EMPREENDIMENTO_HISTORICO (NOLOCK) WHERE ID_ETAPA = 6 AND ID_ITEM_EMPREENDIMENTO = ITEM_EMPREENDIMENTO.ID_ITEM_EMPREENDIMENTO)) AS PRIMEIRO_USUARIO_DESAPROVAÇAO,
(SELECT MIN (DAT_HISTORICO) FROM ITEM_EMPREENDIMENTO_HISTORICO (NOLOCK) WHERE ID_ETAPA = 6 AND ID_ITEM_EMPREENDIMENTO = ITEM_EMPREENDIMENTO.ID_ITEM_EMPREENDIMENTO) AS PRIMEIRA_DATA_DESAPROVACAO,

(SELECT TOP 1 OBSERVACOES FROM ITEM_EMPREENDIMENTO_HISTORICO (NOLOCK) WHERE ID_ETAPA = 6 AND ID_ITEM_EMPREENDIMENTO = ITEM_EMPREENDIMENTO.ID_ITEM_EMPREENDIMENTO AND DAT_HISTORICO = 
(SELECT MAX (DAT_HISTORICO) FROM ITEM_EMPREENDIMENTO_HISTORICO (NOLOCK) WHERE ID_ETAPA = 6 AND ID_ITEM_EMPREENDIMENTO = ITEM_EMPREENDIMENTO.ID_ITEM_EMPREENDIMENTO) ) AS ULTIMO_HISTORICO_DESAPROVACAO


FROM ITEM_EMPREENDIMENTO (NOLOCK)

INNER JOIN	EMPREENDIMENTO				(NOLOCK) ON (EMPREENDIMENTO.ID_EMPREENDIMENTO = ITEM_EMPREENDIMENTO.ID_EMPREENDIMENTO)
LEFT JOIN	ITEM_EMPREENDIMENTO_OBRA	(NOLOCK) ON (ITEM_EMPREENDIMENTO_OBRA.ID_ITEM_EMPREENDIMENTO = ITEM_EMPREENDIMENTO.ID_ITEM_EMPREENDIMENTO)
LEFT JOIN	OBRA						(NOLOCK) ON (OBRA.ID_OBRA = ITEM_EMPREENDIMENTO_OBRA.ID_OBRA)
INNER JOIN  GRUPO_ITEM					(NOLOCK) ON (GRUPO_ITEM.ID_GRUPO_ITEM = ITEM_EMPREENDIMENTO.ID_GRUPO_ITEM)
INNER JOIN  UNIDADE_MEDIDA				(NOLOCK) ON (UNIDADE_MEDIDA.ID_UNIDADE_MEDIDA = ITEM_EMPREENDIMENTO.ID_UNIDADE_MEDIDA)

where (SELECT MAX (DAT_HISTORICO) FROM ITEM_EMPREENDIMENTO_HISTORICO (NOLOCK) WHERE ID_ETAPA = 4 AND ID_ITEM_EMPREENDIMENTO = ITEM_EMPREENDIMENTO.ID_ITEM_EMPREENDIMENTO) BETWEEN '01-05-2023' AND '01-09-2023'


GROUP BY 

EMPREENDIMENTO.ID_EMPREENDIMENTO,
EMPREENDIMENTO.NOM_EMPREENDIMENTO,
ITEM_EMPREENDIMENTO.CODIGO,
ITEM_EMPREENDIMENTO.NOM_ITEM,
GRUPO_ITEM.ID_GRUPO_ITEM,
GRUPO_ITEM.NOM_GRUPO_ITEM,
UNIDADE_MEDIDA.SIGLA,
ITEM_EMPREENDIMENTO.ID_ITEM_EMPREENDIMENTO,
ITEM_EMPREENDIMENTO.PRECO_UNITARIO,
ITEM_EMPREENDIMENTO.PRECO_ORCADO,
ITEM_EMPREENDIMENTO.UserId_CRIACAO

) AS GRUPO

where		GRUPO.ID_EMPREENDIMENTO IS NOT NULL -- (@EMPREENDIMENTO)
AND		GRUPO.ID_GRUPO_ITEM IS NOT NULL -- (@GRUPO_ITEM)

ORDER BY GRUPO.ULTIMA_DATA_APRV_CONTROLE	