USE CORPORE_RESIDENCIAL
SELECT DISTINCT
PFUNC.NOME							AS 'NOME',
--PFUNC.CODSITUACAO					AS 'SITUAÇÃO',
TUSRTMV.CODUSUARIO					AS 'USUARIO', 
PFUNCAO.NOME						AS 'FUNCAO',
GCCUSTO.NOME						AS 'DEPARTAMENTO',
--GUSRPERFIL.CODSISTEMA				AS 'SISTEMA',
GUSRPERFIL.CODPERFIL				AS 'PERFIL'
--TUSRTMV.CODCOLIGADA					AS 'COLIGADA'
--TUSRTMV.CODTMV

FROM GUSRPERFIL						(NOLOCK)
LEFT JOIN TUSRTMV					(NOLOCK)			ON			(TUSRTMV.CODUSUARIO = GUSRPERFIL.CODUSUARIO AND GUSRPERFIL.CODCOLIGADA = TUSRTMV.CODCOLIGADA)
LEFT JOIN GUSUARIO					(NOLOCK)			ON			(GUSRPERFIL.CODUSUARIO= GUSUARIO.CODUSUARIO)
LEFT JOIN PFUNC						(NOLOCK)			ON			(PFUNC.NOME = GUSUARIO.NOME) 
LEFT JOIN PFUNCAO					(NOLOCK)			ON			(PFUNC.CODFUNCAO = PFUNCAO.CODIGO AND PFUNC.CODCOLIGADA = PFUNCAO.CODCOLIGADA)
LEFT JOIN PSECAO						(NOLOCK)			ON			(PFUNC.CODSECAO = PSECAO.CODIGO AND PFUNC.CODCOLIGADA = PSECAO.CODCOLIGADA)
LEFT JOIN GCCUSTO				    (NOLOCK)			ON			(PSECAO.NROCENCUSTOCONT = GCCUSTO.CODCCUSTO AND PSECAO.CODCOLIGADA = GCCUSTO.CODCOLIGADA)
LEFT JOIN GSISTEMA					(NOLOCK)			ON			(GSISTEMA.CODSISTEMA = GUSRPERFIL.CODSISTEMA)

WHERE TUSRTMV.CODUSUARIO NOT IN ('yan.alves', 'wendell.pinto', 'marcelo.silva', 'marcos.vinicius', 'luiz.viana', 'gabriel.ferreira', 'arthur.cordeiro', 'cassio.lapertosa')
 AND GUSRPERFIL.CODSISTEMA = 'T'
AND PFUNC.CODSITUACAO =  'A'
--AND TUSRTMV.CODCOLIGADA = '1'
--GUSUARIO.NOME LIKE '%Eduardo%Lacerda%Ribeiro%'    
--AND PFUNCAO.NOME LIKE '%seguranca%'
--AND TUSRTMV.CODUSUARIO '%ALINE%'   
--AND GCCUSTO.NOME LIKE '%OSASCO%'
AND GUSRPERFIL.CODPERFIL IN ('Acesso',
'APROV.AST.MG'
,'APROV.AST.RJ'
,'APROV.AST.SP'
,'APROV.OBRA'
,'ASSIST.SUPRI'
,'AUX.ALMOXARIFAD'
,'AuxContabil'
,'COMPRADOR1'
,'COMPRADOR2'
,'Compras'
,'Comum'
,'COOR.COMPRAS'
,'COOR.PLANEJAMEN'
,'COOR.SUPRIMENTO'
,'COORD.PROCESSOS'
,'DBA'
,'DIRETOR'
,'ENC.ALMOXARIFAD'
,'ENG.PRODUCAO'
,'ESTOQUE.CENTRAL'
,'ESTOQUE.SECRET'
,'FISCAL'
,'G.ALMOXARIFADO'
,'GERAL.COMPRAS'
,'GERAL.COMPRAS01'
,'GERAL.CONTABIL'
,'GERAL.CONTROL'
,'GERAL.IMOB'
,'GERAL.ORÇAMENTO'
,'GERAL.PLANEJ'
,'GERAL.PROJETOS'
,'GERENTE.COMPRA'
,'Obra'
,'ParmGlb'
,'PROCESSOS'
,'seguranca'
,'TEST.COOR.COMPR')	
ORDER BY PFUNC.NOME DESC