SELECT			
(			
			
	SELECT TOP 1 NUMEROCHEQUE 		
	FROM FLANBAIXA (NOLOCK) 		
	WHERE FLANBAIXA.IDLAN = FLAN.IDLAN		
	AND FLANBAIXA.CODCOLIGADA = FLAN.CODCOLIGADA		
                AND FLANBAIXA.STATUS<> 1			
) AS NUMEROCHEQUE,			
			
FCFOCONT.CODCONTA CONTA_FORNECEDOR,			
DBO.TRAZ_STATUSLAN(FLAN.STATUSLAN) AS 'Imagem - Status',			
FLAN.CODCOLIGADA AS 'Coligada da Conta/Caixa',			
FLAN.CODCXA AS 'Conta/Caixa',			
FTDO.DESCRICAO AS 'Classificação',			
FLAN.IDLAN 'Ref. Lançamento',			
GCCUSTO.NOME AS 'Descrição Centro de Custo',			
FTB2.CODTB2FLX AS 'Classif. Financeira',			
FCFO.NOME AS 'Nome',			
FCFO.NOMEFANTASIA AS 'Nome Fantasia',			
FCFO.CGCCFO AS 'CNPJ/CPF',			
FLAN.NUMERODOCUMENTO AS 'Número do Documento',			
CONVERT(VARCHAR,FLAN.DATAEMISSAO,103) AS 'Data de Emissão',			
FLAN.DATACRIACAO AS 'Dt_Lanc_Criado',			
CONVERT(VARCHAR,FLAN.DATAVENCIMENTO,103) AS 'Data de Vencimento',			
CAST(FLAN.VALORORIGINAL AS MONEY) AS 'Valor Original',			
			
(CASE WHEN DBO.VALOR_LIQUIDO_FLUXUS(FLAN.CODCOLIGADA,FLAN.IDLAN,FLAN.CODCCUSTO) IS NULL			
	THEN DBO.VALOR_LIQUIDO_FLUXUS_SEM_RATEIO(FLAN.CODCOLIGADA, FLAN.IDLAN) 		
	ELSE CAST(DBO.VALOR_LIQUIDO_FLUXUS(FLAN.CODCOLIGADA,FLAN.IDLAN,FLAN.CODCCUSTO)AS MONEY) 		
END) AS 'Valor Líquido',			
			
CONVERT(VARCHAR,FLAN.DATAPAG,103) AS 'Data de Pagamento',			
FLAN.RECMODIFIEDBY AS 'Usuário de Alteração',			
CONVERT(VARCHAR,FLAN.DATAALTERACAO,103) AS 'Data de Alteração',			
FLAN.RECCREATEDBY AS 'Usuário de Criação',			
CONVERT(VARCHAR,TMOV.RECCREATEDON,103) AS 'Data de Criação',			
FLAN.VALORBAIXADO 'Valor Baixado',			
CONVERT(VARCHAR,FLAN.DATABAIXA,103) AS 'Data de baixa',			
GCCUSTO.CODCCUSTO 'Centro de Custo',			
FCXA.DESCRICAO AS 'Descrição Conta/Caixa',			
FTB2.DESCRICAO AS 'Nome Class. Financeira',			
FCXA.CODMOEDA as 'Moeda',			
CAST(FLAN.VALORORIGINAL  AS MONEY) AS 'Original Baixa',			
CONVERT(VARCHAR,FLAN.DATACRIAÇÃO,103) AS 'Data Entrada',			
FTDO.CODTDO + ' - ' + FTDO.DESCRICAO AS 'Tipo de Documento',			
(CASE WHEN TMOVHISTORICO.HISTORICOCURTO IS NULL THEN TMOVHISTORICO.HISTORICOLONGO ELSE '' END) AS HISTORICO,			
'BANCO: ' + FDADOSPGTO.NUMEROBANCO + ' / AGENCIA: ' + FDADOSPGTO.CODIGOAGENCIA + ' CONTA: ' + FDADOSPGTO.CONTACORRENTE AS 'DADOS BANCARIOS',			
(			
	CASE FLAN.TIPOCONTABILLAN 		
	WHEN 0 THEN 'NÃO CONTÁBIL' 		
	WHEN 1 THEN 'CONTÁBIL' 		
	WHEN 2 THEN 'BAIXA CONTÁBIL' 		
	WHEN 1 THEN 'A CONTABILIZAR'		
	ELSE '' 		
	END		
) AS 'STATUS CONTÁBIL DA BAIXA',			
			
			
/*ADICIONADO POR MARCELO SILVA DIA 18-01-2023 A PEDIDO DE JULIO LAMPERT E JANAINA SOBRINHO */			
/*MODIFICADO DIA 04/04/2023 A PEDIDO DE JULIO LAMPERT */			
CAST(FLAN.VALOROP1 AS MONEY) + ISNULL(FLAN.VALORIRRF,0) AS 'VALOR IRRF',			
CAST(FLAN.VALOROP3 AS MONEY) AS 'VALOR INSS',			
CAST(FLAN.VALOROP5 AS MONEY) AS 'AJUSTE A MENOR',			
CAST(FLAN.VALOROP7 AS MONEY) AS 'JUROS CONTATUAL',			
			
CAST(FLAN.VALOROP2 AS MONEY) AS  'VALOR ISSQN',			
CAST(FLAN.VALOROP4 AS MONEY) AS 'AJUSTE A MAIOR',			
CAST(FLAN.VALOROP6 AS MONEY) AS 'CORRECAO MONETARIA',			
CAST(FLAN.VALOROP8 AS MONEY) AS 'HONORARIO',			
			
CAST(ISNULL((			
		SELECT 	
		SUM(FRELLAN.VALORVINCULO)	
		FROM FRELLAN (NOLOCK)	
		WHERE FRELLAN.CODCOLIGADA = FLAN.CODCOLIGADA 	
		AND FRELLAN.IDLAN = FLAN.IDLAN	
		AND FRELLAN.TIPOREL = 28	
),0) AS MONEY) 'VALOR VINCULO',			
CONVERT(VARCHAR,TMOV.DATASAIDA,103) AS DATAENTRADA,			
			
/*MODIFICADO DIA 04/04/2023 A PEDIDO DE JULIO LAMPERT */			
			
CAST(ISNULL((			
		SELECT SUM (FTRBLAN.VALOR) 	
		FROM FTRBLAN (NOLOCK) 	
		WHERE FTRBLAN.IDLAN = FLAN.IDLAN	
		AND FTRBLAN.CODCOLIGADA = FLAN.CODCOLIGADA	
		AND FTRBLAN.CODTRB = 'RTOTAL' 	
),0)AS MONEY) AS RETENCOES			
--CAST(ISNULL((			
			
--	SELECT SUM(FLANBAIXA.VALORRETENCOES)		
--	FROM FLANBAIXA (NOLOCK) 		
--	WHERE FLANBAIXA.IDLAN = FLAN.IDLAN		
--	AND FLANBAIXA.CODCOLIGADA = FLAN.CODCOLIGADA		
--),0)AS MONEY) AS RETENCOES			
			
			
			
FROM FLAN (NOLOCK)			
LEFT JOIN FDADOSPGTO	(NOLOCK) ON (FLAN.CODCOLPGTO = FDADOSPGTO.CODCOLIGADA AND FLAN.CODCOLCFO = FDADOSPGTO.CODCOLCFO AND FLAN.CODCFO = FDADOSPGTO.CODCFO AND FLAN.IDPGTO = FDADOSPGTO.IDPGTO)		
LEFT JOIN FXCX			(NOLOCK) ON (FLAN.CODCOLXCX = FXCX.CODCOLIGADA AND FLAN.IDXCX = FXCX.IDXCX)
LEFT JOIN FCXA			(NOLOCK ) ON (FLAN.CODCOLCXA= FCXA.CODCOLIGADA AND FLAN.CODCXA = FCXA.CODCXA)
LEFT JOIN GCCUSTO		(NOLOCK) ON (FLAN.CODCOLIGADA = GCCUSTO.CODCOLIGADA AND FLAN.CODCCUSTO = GCCUSTO.CODCCUSTO)	
LEFT JOIN TFORMAPAGTO	(NOLOCK) ON (FLAN.CODCOLIGADA = TFORMAPAGTO.CODCOLIGADA AND FLAN.IDFORMAPAGTO = TFORMAPAGTO.IDFORMAPAGTO)		
LEFT JOIN TMOVLAN		(NOLOCK) ON (FLAN.IDLAN = TMOVLAN.IDLAN AND FLAN.CODCOLIGADA = TMOVLAN.CODCOLIGADA)	
LEFT JOIN TMOV			(NOLOCK) ON (FLAN.CODCOLIGADA = TMOV.CODCOLIGADA AND FLAN.IDMOV = TMOV.IDMOV)
LEFT JOIN TMOVHISTORICO (NOLOCK) ON (TMOVHISTORICO.CODCOLIGADA = TMOV.CODCOLIGADA AND TMOVHISTORICO.IDMOV = TMOV.IDMOV)			
LEFT JOIN FCFO			(NOLOCK) ON (FCFO.CODCOLIGADA = FLAN.CODCOLCFO AND FCFO.CODCFO = FLAN.CODCFO)
LEFT JOIN FTDO			(NOLOCK) ON (FLAN.CODCOLIGADA = FTDO.CODCOLIGADA AND FLAN.CODTDO = FTDO.CODTDO)
LEFT JOIN FTB2			(NOLOCK) ON (FLAN.CODCOLIGADA = FTB2.CODCOLIGADA AND FLAN.CODTB2FLX = FTB2.CODTB2FLX)
LEFT JOIN FTB5			(NOLOCK) ON (FLAN.CODCOLIGADA = FTB5.CODCOLIGADA AND FLAN.CODTB5FLX = FTB5.CODTB5FLX)
LEFT JOIN GCOLIGADA		(NOLOCK) ON (FLAN.CODCOLIGADA = GCOLIGADA.CODCOLIGADA)	
LEFT JOIN FCFOCONT		(NOLOCK) ON (FCFO.CODCFO = FCFOCONT.CODCFO AND FCFO.CODCOLIGADA = FCFOCONT.CODCOLCFO AND FLAN.CODCOLIGADA = FCFOCONT.CODCOLIGADA AND FCFOCONT.PAGREC = 2 AND FCFOCONT.TIPO = 2)	
			
WHERE FLAN.PAGREC = 2			
AND (FLAN.STATUSLAN in (0,4) OR (FLAN.STATUSLAN in (1) and FLAN.DATABAIXA >= '20230501') OR (FLAN.STATUSLAN = 2 AND FLAN.DATAEMISSAO < '20230501' AND FLAN.DATACANCELAMENTO>='20230501'))			
and flan.CODTDO <> '0025'			
AND FLAN.NFOUDUP <> 2			
and (flan.codcoligada = 1 or flan.codcoligada >= 10)			
			
ORDER BY FLAN.DATAEMISSAO, FLAN.CODCOLIGADA, FLAN.CODFILIAL			
