SELECT DISTINCT TUSRTMV.CODCOLIGADA, 
TUSRTMV.CODUSUARIO, 
TUSRTMV.CODTMV, 
(CASE WHEN CONSULTAR = 1 THEN 'PODE CONSULTAR' ELSE 'NÃO PODE' END) CONSULTAR,
(CASE WHEN TUSRTMV.IMPRIMIR = 1 THEN 'PODE ENVIAR EMAIL' ELSE 'NÃO PODE' END) IMPRIMIR
FROM GUSRPERFIL 
LEFT JOIN TUSRTMV ON (TUSRTMV.CODUSUARIO = GUSRPERFIL.CODUSUARIO AND GUSRPERFIL.CODCOLIGADA = TUSRTMV.CODCOLIGADA)
LEFT JOIN GUSUARIO ON (GUSRPERFIL.CODUSUARIO= GUSUARIO.CODUSUARIO)
WHERE CODSISTEMA = 'T'
AND GUSUARIO.NOME IN (SELECT NOME FROM PFUNC WHERE CODSECAO NOT IN ('01.500.20','01.500.21','01.500.91') AND CODSITUACAO <> 'D') 
AND TUSRTMV.CODTMV IN ('1.1.21', '1.1.35')




SELECT * FROM FLAN  WHERE IDLAN = 3770119