--SELECT TOP 100 * FROM XEMPREENDIMENTO    where XEMPREENDIMENTO.codcoligada = 22

SELECT * FROM [dbo].[XCOMPONENTEMODALIDADEVENDA]

SELECT TOP 10* FROM [dbo].[XPARCELACOMPONENTE_1219]

SELECT TOP 10* FROM xcomponente

SELECT TOP 10 * FROM XVENDAPARCELA

SELECT TOP 100 * FROM XVENDA

SELECT * FROM [dbo].[XCOMPONENTEVRINTEGRACAO]



SELECT TOP 100 * FROM FLANBAIXA

SELECT TOP 100 * FROM FLANCOMPL





--SELECT * FROM FTDO WHERE DESCRICAO LIKE 'MEN'