SELECT * FROM NOTA_FISCAL WHERE NUMERO_NOTA ='000202341' AND EMPREITEIRO_DESCRICAO = '5ª MEDIÇÃO'

SELECT * FROM NOTA_ITEM WHERE ID_NOTA_FISCAL IN ('62691','64915')

SELECT CODUNDCOMPRA, * FROM CORPORE_RESIDENCIAL..TPRODUTODEF WHERE IDPRD ='59912'

--BEGIN TRAN
--UPDATE NOTA_ITEM SET RM_CODUNDCOMPRA = 'MES' WHERE ID_NOTA_FISCAL IN ('62691','64915')
--COMMIT

