SELECT 

/*UNIMED SEGUROS*/

(SELECT TOP 1 VALACRESCENTAR FROM PCALCVLR WHERE CODTABCALC = 'UNISG1' AND NROFAIXA = 1 ORDER BY INICIOVIGENCIA DESC) AS '0 A 18  UNISG1',
(SELECT TOP 1 VALACRESCENTAR FROM PCALCVLR WHERE CODTABCALC = 'UNISG2' AND NROFAIXA = 1 ORDER BY INICIOVIGENCIA DESC) AS '0 A 18  UNISG2',
(SELECT TOP 1 VALACRESCENTAR FROM PCALCVLR WHERE CODTABCALC = 'UNISG3' AND NROFAIXA = 1 ORDER BY INICIOVIGENCIA DESC) AS '0 A 18  UNISG3',
(SELECT TOP 1 VALACRESCENTAR FROM PCALCVLR WHERE CODTABCALC = 'UNISG4' AND NROFAIXA = 1 ORDER BY INICIOVIGENCIA DESC) AS '0 A 18  UNISG4',

(SELECT TOP 1 VALACRESCENTAR FROM PCALCVLR WHERE CODTABCALC = 'UNISG1' AND NROFAIXA = 2 ORDER BY INICIOVIGENCIA DESC) AS '19 A 23  UNISG1',
(SELECT TOP 1 VALACRESCENTAR FROM PCALCVLR WHERE CODTABCALC = 'UNISG2' AND NROFAIXA = 2 ORDER BY INICIOVIGENCIA DESC) AS '19 A 23  UNISG2',
(SELECT TOP 1 VALACRESCENTAR FROM PCALCVLR WHERE CODTABCALC = 'UNISG3' AND NROFAIXA = 2 ORDER BY INICIOVIGENCIA DESC) AS '19 A 23  UNISG3',
(SELECT TOP 1 VALACRESCENTAR FROM PCALCVLR WHERE CODTABCALC = 'UNISG4' AND NROFAIXA = 2 ORDER BY INICIOVIGENCIA DESC) AS '19 A 23  UNISG4',

(SELECT TOP 1 VALACRESCENTAR FROM PCALCVLR WHERE CODTABCALC = 'UNISG1' AND NROFAIXA = 3 ORDER BY INICIOVIGENCIA DESC) AS '24 A 28  UNISG1',
(SELECT TOP 1 VALACRESCENTAR FROM PCALCVLR WHERE CODTABCALC = 'UNISG2' AND NROFAIXA = 3 ORDER BY INICIOVIGENCIA DESC) AS '24 A 28  UNISG2',
(SELECT TOP 1 VALACRESCENTAR FROM PCALCVLR WHERE CODTABCALC = 'UNISG3' AND NROFAIXA = 3 ORDER BY INICIOVIGENCIA DESC) AS '24 A 28  UNISG3',
(SELECT TOP 1 VALACRESCENTAR FROM PCALCVLR WHERE CODTABCALC = 'UNISG4' AND NROFAIXA = 3 ORDER BY INICIOVIGENCIA DESC) AS '24 A 28  UNISG4',

(SELECT TOP 1 VALACRESCENTAR FROM PCALCVLR WHERE CODTABCALC = 'UNISG1' AND NROFAIXA = 4 ORDER BY INICIOVIGENCIA DESC) AS '29 A 33  UNISG1',
(SELECT TOP 1 VALACRESCENTAR FROM PCALCVLR WHERE CODTABCALC = 'UNISG2' AND NROFAIXA = 4 ORDER BY INICIOVIGENCIA DESC) AS '29 A 33  UNISG2',
(SELECT TOP 1 VALACRESCENTAR FROM PCALCVLR WHERE CODTABCALC = 'UNISG3' AND NROFAIXA = 4 ORDER BY INICIOVIGENCIA DESC) AS '29 A 33  UNISG3',
(SELECT TOP 1 VALACRESCENTAR FROM PCALCVLR WHERE CODTABCALC = 'UNISG4' AND NROFAIXA = 4 ORDER BY INICIOVIGENCIA DESC) AS '29 A 33  UNISG4',

(SELECT TOP 1 VALACRESCENTAR FROM PCALCVLR WHERE CODTABCALC = 'UNISG1' AND NROFAIXA = 5 ORDER BY INICIOVIGENCIA DESC) AS '34 A 38  UNISG1',
(SELECT TOP 1 VALACRESCENTAR FROM PCALCVLR WHERE CODTABCALC = 'UNISG2' AND NROFAIXA = 5 ORDER BY INICIOVIGENCIA DESC) AS '34 A 38  UNISG2',
(SELECT TOP 1 VALACRESCENTAR FROM PCALCVLR WHERE CODTABCALC = 'UNISG3' AND NROFAIXA = 5 ORDER BY INICIOVIGENCIA DESC) AS '34 A 38  UNISG3',
(SELECT TOP 1 VALACRESCENTAR FROM PCALCVLR WHERE CODTABCALC = 'UNISG4' AND NROFAIXA = 5 ORDER BY INICIOVIGENCIA DESC) AS '34 A 38  UNISG4',

(SELECT TOP 1 VALACRESCENTAR FROM PCALCVLR WHERE CODTABCALC = 'UNISG1' AND NROFAIXA = 6 ORDER BY INICIOVIGENCIA DESC) AS '39 A 43  UNISG1',
(SELECT TOP 1 VALACRESCENTAR FROM PCALCVLR WHERE CODTABCALC = 'UNISG2' AND NROFAIXA = 6 ORDER BY INICIOVIGENCIA DESC) AS '39 A 43  UNISG2',
(SELECT TOP 1 VALACRESCENTAR FROM PCALCVLR WHERE CODTABCALC = 'UNISG3' AND NROFAIXA = 6 ORDER BY INICIOVIGENCIA DESC) AS '39 A 43  UNISG3',
(SELECT TOP 1 VALACRESCENTAR FROM PCALCVLR WHERE CODTABCALC = 'UNISG4' AND NROFAIXA = 6 ORDER BY INICIOVIGENCIA DESC) AS '39 A 43  UNISG4',

(SELECT TOP 1 VALACRESCENTAR FROM PCALCVLR WHERE CODTABCALC = 'UNISG1' AND NROFAIXA = 7 ORDER BY INICIOVIGENCIA DESC) AS '44 A 48  UNISG1',
(SELECT TOP 1 VALACRESCENTAR FROM PCALCVLR WHERE CODTABCALC = 'UNISG2' AND NROFAIXA = 7 ORDER BY INICIOVIGENCIA DESC) AS '44 A 48  UNISG2',
(SELECT TOP 1 VALACRESCENTAR FROM PCALCVLR WHERE CODTABCALC = 'UNISG3' AND NROFAIXA = 7 ORDER BY INICIOVIGENCIA DESC) AS '44 A 48  UNISG3',
(SELECT TOP 1 VALACRESCENTAR FROM PCALCVLR WHERE CODTABCALC = 'UNISG4' AND NROFAIXA = 7 ORDER BY INICIOVIGENCIA DESC) AS '44 A 48  UNISG4',

(SELECT TOP 1 VALACRESCENTAR FROM PCALCVLR WHERE CODTABCALC = 'UNISG1' AND NROFAIXA = 8 ORDER BY INICIOVIGENCIA DESC) AS '49 A 53  UNISG1',
(SELECT TOP 1 VALACRESCENTAR FROM PCALCVLR WHERE CODTABCALC = 'UNISG2' AND NROFAIXA = 8 ORDER BY INICIOVIGENCIA DESC) AS '49 A 53  UNISG2',
(SELECT TOP 1 VALACRESCENTAR FROM PCALCVLR WHERE CODTABCALC = 'UNISG3' AND NROFAIXA = 8 ORDER BY INICIOVIGENCIA DESC) AS '49 A 53  UNISG3',
(SELECT TOP 1 VALACRESCENTAR FROM PCALCVLR WHERE CODTABCALC = 'UNISG4' AND NROFAIXA = 8 ORDER BY INICIOVIGENCIA DESC) AS '49 A 53  UNISG4',

(SELECT TOP 1 VALACRESCENTAR FROM PCALCVLR WHERE CODTABCALC = 'UNISG1' AND NROFAIXA = 9 ORDER BY INICIOVIGENCIA DESC) AS '54 A 58  UNISG1',
(SELECT TOP 1 VALACRESCENTAR FROM PCALCVLR WHERE CODTABCALC = 'UNISG2' AND NROFAIXA = 9 ORDER BY INICIOVIGENCIA DESC) AS '54 A 58  UNISG2',
(SELECT TOP 1 VALACRESCENTAR FROM PCALCVLR WHERE CODTABCALC = 'UNISG3' AND NROFAIXA = 9 ORDER BY INICIOVIGENCIA DESC) AS '54 A 58  UNISG3',
(SELECT TOP 1 VALACRESCENTAR FROM PCALCVLR WHERE CODTABCALC = 'UNISG4' AND NROFAIXA = 9 ORDER BY INICIOVIGENCIA DESC) AS '54 A 58  UNISG4',

(SELECT TOP 1 VALACRESCENTAR FROM PCALCVLR WHERE CODTABCALC = 'UNISG1' AND NROFAIXA = 10 ORDER BY INICIOVIGENCIA DESC) AS '59 ACIMA  UNISG1',
(SELECT TOP 1 VALACRESCENTAR FROM PCALCVLR WHERE CODTABCALC = 'UNISG2' AND NROFAIXA = 10 ORDER BY INICIOVIGENCIA DESC) AS '59 ACIMA  UNISG2',
(SELECT TOP 1 VALACRESCENTAR FROM PCALCVLR WHERE CODTABCALC = 'UNISG3' AND NROFAIXA = 10 ORDER BY INICIOVIGENCIA DESC) AS '59 ACIMA  UNISG3',
(SELECT TOP 1 VALACRESCENTAR FROM PCALCVLR WHERE CODTABCALC = 'UNISG4' AND NROFAIXA = 10 ORDER BY INICIOVIGENCIA DESC) AS '59 ACIMA  UNISG4',

/*ODONTO*/
(SELECT TOP 1 VALACRESCENTAR FROM PCALCVLR WHERE CODTABCALC = 'ODONT1' AND NROFAIXA = 1 ORDER BY INICIOVIGENCIA DESC) AS 'ODONT1',
(SELECT TOP 1 VALACRESCENTAR FROM PCALCVLR WHERE CODTABCALC = 'ODONT2' AND NROFAIXA = 1 ORDER BY INICIOVIGENCIA DESC) AS 'ODONT2'




FROM GCOLIGADA WHERE CODCOLIGADA =:ESPELHO#2



