SELECT 

EMPREENDIMENTO.NOM_EMPREENDIMENTO,
OBRA.RM_NOME,
FICHA_PREENCHIDA.ID_FICHA_PREENCHIDA,
ficha_verificacao.ID_FICHA_VERIFICACAO,
FICHA_VERIFICACAO.COD_FICHA_VERIFICACAO AS COD_FDV,
FICHA_VERIFICACAO.NOM_FICHA_VERIFICACAO AS NOME_FDV,
PERIODICIDADE.NOM_PERIODICIDADE,
INSTRUCAO_SERVICO.COD_INSTRUCAO_SERVICO + ' - ' + INSTRUCAO_SERVICO.NOM_INSTRUCAO_SERVICO AS IDS,
CONVERT (VARCHAR,GRUPO_ITEM.ID_GRUPO_ITEM) + ' - ' + GRUPO_ITEM.NOM_GRUPO_ITEM AS GRUPO_ITEM,
LOCAL_BLOCO.ID_LOCAL_BLOCO,
LOCAL_BLOCO.NOM_LOCAL_BLOCO,
LOCAL_PAVIMENTO.NUMERO AS PVTO, 
LOCAL_APARTAMENTO.NOM_LOCAL_APARTAMENTO,
LOCAL_ESCADA.NUMERO AS ESCADA,
LOCAL_HALL.NUMERO AS HALL,
FICHA_PREENCHIDA.NOM_LOCAL,
CONVERT (VARCHAR,FICHA_PREENCHIDA.DAT_PREENCHIMENTO,103) AS DAT_PREENCHIMENTO,
FICHA_PREENCHIDA.DAT_PREENCHIMENTO AS HORA,
SUBSTRING (aspnet_Users.UserName,9,100) AS UserName,

(CASE WHEN FICHA_PREENCHIDA.UserId in (SELECT PERFIL_USUARIO_OBRA.UserId FROM PERFIL_USUARIO_OBRA WHERE UserId = FICHA_PREENCHIDA.UserId AND PERFIL_USUARIO_OBRA.ID_OBRA = FICHA_PREENCHIDA.ID_OBRA AND PERFIL_USUARIO_OBRA.ID_PERFIL IN (13,10))
		THEN 'ATIVO'
		ELSE 'INATIVO'
END) AS SITUACAO_USUARIO_VERIFICADOR,

(CASE	WHEN MEDICAO.ID_MEDICAO IS NOT NULL AND MEDICAO_FICHA_PREENCHIDA.QTD_MEDIDA < 0 THEN 'NÃO'
		WHEN FICHA_PREENCHIDA.FLG_LIBERADA = 1 THEN 'SIM'
		ELSE 'NÃO'
END) AS LIBERADA,
EMPREITEIRO.NOM_EMPREITEIRO,
FUNCIONARIO.NOM_FUNCIONARIO,
CONVERT (VARCHAR,FICHA_PREENCHIDA.DAT_INICIO_SERVICO,103) AS DAT_INICIO_SERVICO,
CONVERT (VARCHAR,FICHA_PREENCHIDA.DAT_FIM_SERVICO,103) AS DAT_FIM_SERVICO,
DATEDIFF(DAY,DAT_FIM_SERVICO,FICHA_PREENCHIDA.DAT_LIBERACAO)  AS DESEMPENHO_POR_USUARIO,

CONVERT (VARCHAR,FICHA_PREENCHIDA.DAT_LIBERACAO,103) AS DAT_LIBERACAO,


MEDICAO.COD_MEDICAO AS MEDICAO,
ETAPA.NOM_ETAPA AS ETAPA,
MEDICAO.EXCLUIDO,
EMPREITEIRO_MEDICAO.NOM_EMPREITEIRO AS EMPREITEIRO_MEDICAO,

CONVERT (VARCHAR,MEDICAO.DAT_CRIACAO,103) AS DAT_CRIACAO,
CONVERT (VARCHAR,MEDICAO.DAT_CADASTRO,103) AS DAT_CADASTRO,
CONVERT (VARCHAR,MEDICAO.DAT_VENCIMENTO,103) AS DAT_VENCIMENTO,

CONVERT (VARCHAR,NOTA_FISCAL.DATA_EXPORTACAO,103) DATA_ENVIO_RM,
NOTA_FISCAL.NUMERO_NOTA,

(SELECT TOP 1 CONVERT (VARCHAR,TMOV.DATACRIACAO,103) FROM CORPORE_RESIDENCIAL.DBO.TMOVRELAC AS TMOVRELAC
LEFT JOIN CORPORE_RESIDENCIAL.dbo.TMOV AS TMOV (NOLOCK) ON (TMOV.IDMOV = TMOVRELAC.IDMOVDESTINO AND TMOV.CODCOLIGADA = TMOVRELAC.CODCOLDESTINO)
LEFT JOIN CORPORE_RESIDENCIAL.DBO.FLAN AS FLAN(NOLOCK) ON (FLAN.IDMOV = TMOV.IDMOV AND FLAN.CODCOLIGADA = TMOV.CODCOLIGADA)
WHERE	FLAN.CODTB2FLX IN ('062','063')
AND		TMOV.STATUS <> 'C'
AND		TMOVRELAC.IDMOVORIGEM = NOTA_FISCAL.RM_IDMOV) AS PROCESSAMENTO_CANTABILIDADE,

(SELECT TOP 1 CONVERT (VARCHAR,FLAN.DATABAIXA,103)  FROM CORPORE_RESIDENCIAL.DBO.TMOVRELAC AS TMOVRELAC
LEFT JOIN CORPORE_RESIDENCIAL.dbo.TMOV AS TMOV (NOLOCK) ON (TMOV.IDMOV = TMOVRELAC.IDMOVDESTINO AND TMOV.CODCOLIGADA = TMOVRELAC.CODCOLDESTINO)
LEFT JOIN CORPORE_RESIDENCIAL.DBO.FLAN AS FLAN(NOLOCK) ON (FLAN.IDMOV = TMOV.IDMOV AND FLAN.CODCOLIGADA = TMOV.CODCOLIGADA)
WHERE	FLAN.CODTB2FLX IN ('062','063')
AND		TMOV.STATUS <> 'C'
AND		TMOVRELAC.IDMOVORIGEM = NOTA_FISCAL.RM_IDMOV) AS PAGAMENTO_NOTA,

CONVERT (VARCHAR,(SELECT MAX (DAT_HISTORICO) FROM MEDICAO_HISTORICO WHERE MEDICAO.ID_MEDICAO = MEDICAO_HISTORICO.ID_MEDICAO AND MEDICAO_HISTORICO.ID_ETAPA = 3),103) AS DATA_APRV_ENGE,

MEDICAO_FICHA_PREENCHIDA.QTD_MEDIDA,

ITEM_EMPREENDIMENTO.CODIGO + ' - ' + ITEM_EMPREENDIMENTO.NOM_ITEM AS ITEM_EMPREENDIMENTO,


/* RETIRADO DEVIDO A PERFORMANCE DO RELATORIO 
(SELECT MIN (DAT_HISTORICO) FROM ITEM_EMPREENDIMENTO_HISTORICO WHERE ID_ETAPA = 4 AND ID_ITEM_EMPREENDIMENTO IN (
SELECT ITM_INTERNO.ID_ITEM_EMPREENDIMENTO FROM ITEM_EMPREENDIMENTO AS ITM_INTERNO WHERE ITM_INTERNO.ID_EMPREENDIMENTO = ITEM_EMPREENDIMENTO.ID_EMPREENDIMENTO AND ITM_INTERNO.CODIGO = ITEM_EMPREENDIMENTO.CODIGO)) AS APROVACAO_ITEM_CONTROLE,

*/

(SELECT MAX (IE.PRECO_UNITARIO) * FICHA_VERIFICACAO_EMPREENDIMENTO.QUANTIDADE_MEDICAO

FROM QUALIDADE.MEDICAO_FICHA_PREENCHIDA AS MFP_INTERNO
LEFT JOIN MEDICAO_ITEM_EMPREENDIMENTO AS MIE	(NOLOCK) ON (MIE.ID_MEDICAO_ITEM_EMPREENDIMENTO = MFP_INTERNO.ID_MEDICAO_ITEM_EMPREENDIMENTO)
LEFT JOIN MEDICAO AS M								(NOLOCK) ON (M.ID_MEDICAO = MIE.ID_MEDICAO)
LEFT JOIN ITEM_EMPREENDIMENTO AS IE				(NOLOCK) ON (IE.ID_ITEM_EMPREENDIMENTO = MIE.ID_ITEM_EMPREENDIMENTO)
WHERE	MFP_INTERNO.ID_FICHA_PREENCHIDA = FICHA_PREENCHIDA.ID_FICHA_PREENCHIDA
AND		M.EXCLUIDO = 0
) AS PRECO_ITEN_MEDICAO,

/* TRAZ O USUARIO QUE PREENCHEU O PRIMEIRO METODO DA FICHA ATRAVÉS DA FUNÇÃO ABAIXO, PASSANDO O MENOR ID DE HISTÓRICO, 
FOI FEITO DESTA FORMA POIS TRAZENDO DIRETAMENTE NO RELATORIO ESTAVA MUITO LENTO */

ISNULL (dbo.USUARIO_ABERTURA_FICHA_PREENCHIDA((SELECT MIN (FPDH.ID_FICHA_PREENCHIDA_DETALHE_HISTORICO) 
FROM qualidade.FICHA_PREENCHIDA_DETALHE_HISTORICO AS FPDH
INNER JOIN qualidade.FICHA_PREENCHIDA_DETALHE AS FPD		(NOLOCK) ON (FPD.ID_FICHA_PREENCHIDA_DETALHE = FPDH.ID_FICHA_PREENCHIDA_DETALHE)
WHERE	FPD.ID_FICHA_PREENCHIDA = FICHA_PREENCHIDA.ID_FICHA_PREENCHIDA)),SUBSTRING (aspnet_Users.UserName,9,100)) AS USUARIO_PRIMEIRO_PREENCHIMENTO,

/* TRAZ A DATA DO PRIMEIRO METODO PREENCHIDO DA FICHA*/

(SELECT  MIN (FPDH.DAT_HISTORICO)
FROM qualidade.FICHA_PREENCHIDA_DETALHE_HISTORICO AS FPDH
INNER JOIN qualidade.FICHA_PREENCHIDA_DETALHE AS FPD		(NOLOCK) ON (FPD.ID_FICHA_PREENCHIDA_DETALHE = FPDH.ID_FICHA_PREENCHIDA_DETALHE)
WHERE	FPD.ID_FICHA_PREENCHIDA = FICHA_PREENCHIDA.ID_FICHA_PREENCHIDA) AS DATA_ABERTURA,

(SELECT  MAX (FPDH.DAT_HISTORICO)
FROM qualidade.FICHA_PREENCHIDA_DETALHE_HISTORICO AS FPDH
INNER JOIN qualidade.FICHA_PREENCHIDA_DETALHE AS FPD		(NOLOCK) ON (FPD.ID_FICHA_PREENCHIDA_DETALHE = FPDH.ID_FICHA_PREENCHIDA_DETALHE)
WHERE	FPD.ID_FICHA_PREENCHIDA = FICHA_PREENCHIDA.ID_FICHA_PREENCHIDA) AS DATA_ULTIMO_METODO,


(SELECT TOP 1 LOGIN_RM_ENGENHEIRO 
FROM PERFIL_USUARIO_OBRA 
WHERE PERFIL_USUARIO_OBRA.ID_PERFIL IN (10,13)
AND PERFIL_USUARIO_OBRA.ID_OBRA = FICHA_PREENCHIDA.ID_OBRA 
AND PERFIL_USUARIO_OBRA.UserId =

								ISNULL((SELECT TOP 1 FPDH.UserId
								FROM qualidade.FICHA_PREENCHIDA_DETALHE_HISTORICO AS FPDH
								INNER JOIN qualidade.FICHA_PREENCHIDA_DETALHE AS FPD		(NOLOCK) ON (FPD.ID_FICHA_PREENCHIDA_DETALHE = FPDH.ID_FICHA_PREENCHIDA_DETALHE)
								WHERE	FPD.ID_FICHA_PREENCHIDA = FICHA_PREENCHIDA.ID_FICHA_PREENCHIDA ORDER BY FPDH.DAT_HISTORICO),aspnet_Users.UserId) ORDER BY PERFIL_USUARIO_OBRA.ID_PERFIL

) AS SERVICOS_INSPENCIONADOS,

/* TRAZ O PRECO UNITARIO DA ULTIMA REVISAO DO ITEM */
(SELECT TOP 1 ITEM_ULTIMA_REVISAO.PRECO_UNITARIO FROM ITEM_EMPREENDIMENTO AS ITEM_ULTIMA_REVISAO  WHERE ITEM_ULTIMA_REVISAO.CODIGO = ITEM_EMPREENDIMENTO.CODIGO AND ITEM_ULTIMA_REVISAO.ID_EMPREENDIMENTO = ITEM_EMPREENDIMENTO.ID_EMPREENDIMENTO ORDER BY ITEM_ULTIMA_REVISAO.ID_ITEM_EMPREENDIMENTO DESC) AS PRC_ULTIMA_REVISAO,



/* TRAZ USUARIO QUE PREENCHEU ULTIMO MÉTODO OBRIGATÓRIO CASO A FICHA ESTEJA LIBERADA */

(CASE WHEN FICHA_PREENCHIDA.FLG_LIBERADA = 1 THEN 
													dbo.USUARIO_ABERTURA_FICHA_PREENCHIDA((SELECT MAX (FPDH.ID_FICHA_PREENCHIDA_DETALHE_HISTORICO) 
													FROM qualidade.FICHA_PREENCHIDA_DETALHE_HISTORICO AS FPDH
													INNER JOIN qualidade.FICHA_PREENCHIDA_DETALHE AS FPD		(NOLOCK) ON (FPD.ID_FICHA_PREENCHIDA_DETALHE = FPDH.ID_FICHA_PREENCHIDA_DETALHE)
													INNER JOIN qualidade.FICHA_VERIFICACAO_METODO AS METODO		(NOLOCK) ON (METODO.ID_FICHA_VERIFICACAO_METODO = FPD.ID_FICHA_VERIFICACAO_METODO)
													WHERE	FPD.ID_FICHA_PREENCHIDA = FICHA_PREENCHIDA.ID_FICHA_PREENCHIDA
													AND		METODO.FLG_OBRIGATORIO = 1)) 
													
END) USUARIO_LIBERACAO,


(SELECT TOP 1 FVR.REVISAO
FROM qualidade.FICHA_PREENCHIDA_DETALHE AS FPD	
INNER JOIN qualidade.FICHA_VERIFICACAO_METODO AS FVM	(NOLOCK) ON (FPD.ID_FICHA_VERIFICACAO_METODO = FVM.ID_FICHA_VERIFICACAO_METODO)
INNER JOIN qualidade.FICHA_VERIFICACAO_REVISAO AS FVR	(NOLOCK) ON (FVR.ID_FICHA_VERIFICACAO_REVISAO = FVM.ID_FICHA_VERIFICACAO_REVISAO)
WHERE	FPD.ID_FICHA_PREENCHIDA = FICHA_PREENCHIDA.ID_FICHA_PREENCHIDA ORDER BY FPD.ID_FICHA_PREENCHIDA_DETALHE) AS REVISAO_PREENCHIMENTO
FROM DBCONTROLEMP.qualidade.FICHA_PREENCHIDA AS FICHA_PREENCHIDA

LEFT JOIN DBCONTROLEMP.DBO.OBRA AS OBRA																	(NOLOCK) ON (OBRA.ID_OBRA = FICHA_PREENCHIDA.ID_OBRA)
LEFT JOIN DBCONTROLEMP.DBO.EMPREENDIMENTO AS EMPREENDIMENTO												(NOLOCK) ON (EMPREENDIMENTO.ID_EMPREENDIMENTO = OBRA.ID_EMPREENDIMENTO)
LEFT JOIN DBCONTROLEMP.qualidade.LOCAL_BLOCO AS LOCAL_BLOCO												(NOLOCK) ON (LOCAL_BLOCO.ID_LOCAL_BLOCO = FICHA_PREENCHIDA.ID_LOCAL_BLOCO and LOCAL_BLOCO.ID_OBRA = FICHA_PREENCHIDA.ID_OBRA)
LEFT JOIN DBCONTROLEMP.qualidade.LOCAL_PAVIMENTO AS LOCAL_PAVIMENTO 									(NOLOCK) ON (LOCAL_PAVIMENTO.ID_LOCAL_PAVIMENTO = FICHA_PREENCHIDA.ID_LOCAL_PAVIMENTO and LOCAL_PAVIMENTO.ID_LOCAL_BLOCO  = FICHA_PREENCHIDA.ID_LOCAL_BLOCO)
LEFT JOIN DBCONTROLEMP.qualidade.LOCAL_APARTAMENTO AS LOCAL_APARTAMENTO									(NOLOCK) ON (LOCAL_APARTAMENTO.ID_LOCAL_APARTAMENTO = FICHA_PREENCHIDA.ID_LOCAL_APARTAMENTO and LOCAL_APARTAMENTO.ID_LOCAL_PAVIMENTO  = FICHA_PREENCHIDA.ID_LOCAL_PAVIMENTO)
LEFT JOIN DBCONTROLEMP.qualidade.LOCAL_ESCADA AS LOCAL_ESCADA											(NOLOCK) ON (LOCAL_ESCADA.ID_LOCAL_ESCADA = FICHA_PREENCHIDA.ID_LOCAL_ESCADA and LOCAL_ESCADA.ID_LOCAL_PAVIMENTO  = FICHA_PREENCHIDA.ID_LOCAL_PAVIMENTO)
LEFT JOIN DBCONTROLEMP.qualidade.LOCAL_HALL	AS LOCAL_HALL												(NOLOCK) ON (LOCAL_HALL.ID_LOCAL_HALL = FICHA_PREENCHIDA.ID_LOCAL_HALL and LOCAL_HALL.ID_LOCAL_PAVIMENTO  = FICHA_PREENCHIDA.ID_LOCAL_PAVIMENTO)
LEFT JOIN DBCONTROLEMP.DBO.aspnet_Users	AS aspnet_Users													(NOLOCK) ON (aspnet_Users.UserId = FICHA_PREENCHIDA.UserId)
LEFT JOIN DBCONTROLEMP.DBO.EMPREITEIRO AS EMPREITEIRO													(NOLOCK) ON (EMPREITEIRO.ID_EMPREITEIRO = FICHA_PREENCHIDA.ID_EMPREITEIRO) 
LEFT JOIN DBCONTROLEMP.DBO.FUNCIONARIO AS FUNCIONARIO													(NOLOCK) ON (FUNCIONARIO.ID_FUNCIONARIO = FICHA_PREENCHIDA.ID_FUNCIONARIO)
LEFT JOIN DBCONTROLEMP.qualidade.FICHA_VERIFICACAO_EMPREENDIMENTO AS FICHA_VERIFICACAO_EMPREENDIMENTO	(NOLOCK) ON (FICHA_VERIFICACAO_EMPREENDIMENTO.ID_FICHA_VERIFICACAO_EMPREENDIMENTO = FICHA_PREENCHIDA.ID_FICHA_VERIFICACAO_EMPREENDIMENTO)
LEFT JOIN DBCONTROLEMP.qualidade.FICHA_VERIFICACAO_REVISAO AS FICHA_VERIFICACAO_REVISAO					(NOLOCK) ON (FICHA_VERIFICACAO_REVISAO.ID_FICHA_VERIFICACAO_REVISAO = FICHA_VERIFICACAO_EMPREENDIMENTO.ID_FICHA_VERIFICACAO_REVISAO)
LEFT JOIN DBCONTROLEMP.qualidade.PERIODICIDADE AS PERIODICIDADE											(NOLOCK) ON (PERIODICIDADE.ID_PERIODICIDADE = FICHA_VERIFICACAO_REVISAO.ID_PERIODICIDADE)
LEFT JOIN DBCONTROLEMP.qualidade.FICHA_VERIFICACAO AS FICHA_VERIFICACAO									(NOLOCK) ON (FICHA_VERIFICACAO.ID_FICHA_VERIFICACAO = FICHA_VERIFICACAO_REVISAO.ID_FICHA_VERIFICACAO)
LEFT JOIN DBCONTROLEMP.qualidade.INSTRUCAO_SERVICO AS INSTRUCAO_SERVICO									(NOLOCK) ON (FICHA_VERIFICACAO.ID_INSTRUCAO_SERVICO = INSTRUCAO_SERVICO.ID_INSTRUCAO_SERVICO)
LEFT JOIN DBCONTROLEMP.dbo.ITEM_EMPREENDIMENTO AS ITEM_EMPREENDIMENTO									(NOLOCK) ON (ITEM_EMPREENDIMENTO.ID_ITEM_EMPREENDIMENTO = FICHA_VERIFICACAO_EMPREENDIMENTO.ID_ITEM_EMPREENDIMENTO)
LEFT JOIN DBCONTROLEMP.dbo.GRUPO_ITEM AS GRUPO_ITEM														(NOLOCK) ON (ITEM_EMPREENDIMENTO.ID_GRUPO_ITEM = GRUPO_ITEM.ID_GRUPO_ITEM)
LEFT JOIN DBCONTROLEMP.qualidade.MEDICAO_FICHA_PREENCHIDA as MEDICAO_FICHA_PREENCHIDA					(NOLOCK) ON (MEDICAO_FICHA_PREENCHIDA.ID_FICHA_PREENCHIDA = FICHA_PREENCHIDA.ID_FICHA_PREENCHIDA AND MEDICAO_FICHA_PREENCHIDA.ID_MEDICAO_FICHA_PREENCHIDA NOT IN (
																																																																			SELECT MFP.ID_MEDICAO_FICHA_PREENCHIDA FROM qualidade.MEDICAO_FICHA_PREENCHIDA AS MFP
																																																																			INNER JOIN MEDICAO_ITEM_EMPREENDIMENTO AS MIE				(NOLOCK) ON (MIE.ID_MEDICAO_ITEM_EMPREENDIMENTO = MFP.ID_MEDICAO_ITEM_EMPREENDIMENTO)
																																																																			INNER JOIN MEDICAO AS M															(NOLOCK) ON (M.ID_MEDICAO = MIE.ID_MEDICAO)
																																																																			WHERE	M.EXCLUIDO = 1
																																																																		  )) /*ELIMINA MEDICAOES EXCLUIDAS */
LEFT JOIN DBCONTROLEMP.dbo.MEDICAO_ITEM_EMPREENDIMENTO AS MEDICAO_ITEM_EMPREENDIMENTO					(NOLOCK) ON (MEDICAO_ITEM_EMPREENDIMENTO.ID_MEDICAO_ITEM_EMPREENDIMENTO = MEDICAO_FICHA_PREENCHIDA.ID_MEDICAO_ITEM_EMPREENDIMENTO)
LEFT JOIN DBCONTROLEMP.dbo.MEDICAO AS MEDICAO															(NOLOCK) ON (MEDICAO.ID_MEDICAO = MEDICAO_ITEM_EMPREENDIMENTO.ID_MEDICAO AND MEDICAO.EXCLUIDO <> 1)
LEFT JOIN DBCONTROLEMP.dbo.NOTA_FISCAL AS NOTA_FISCAL													(NOLOCK) ON (NOTA_FISCAL.ID_MEDICAO =MEDICAO.ID_MEDICAO AND NOTA_FISCAL.FLAG_CANCELADO = 0)
LEFT JOIN DBCONTROLEMP.dbo.ETAPA AS ETAPA																(NOLOCK) ON (ETAPA.ID_ETAPA = MEDICAO.ID_ETAPA)		
LEFT JOIN DBCONTROLEMP.dbo.CONTRATO AS CONTRATO															(NOLOCK) ON (CONTRATO.ID_CONTRATO = MEDICAO.ID_CONTRATO)
LEFT JOIN DBCONTROLEMP.dbo.EMPREITEIRO AS EMPREITEIRO_MEDICAO											(NOLOCK) ON (EMPREITEIRO_MEDICAO.ID_EMPREITEIRO = CONTRATO.ID_EMPREITEIRO)


/* DATEADD POIS A DATA POSSUI HORAS */
where DAT_PREENCHIMENTO >= @DATA_PREENCIMENTO_INI 
AND DAT_PREENCHIMENTO <=  DATEADD (DAY,1,@DATA_PREENCIMENTO_FIN)
AND OBRA.ID_OBRA IN (@OBRA)
AND FICHA_PREENCHIDA.FLG_LIBERADA IN (@LIBERADA)