
SELECT 
CONTRATO_HISTORICO.ID_CONTRATO,
CONTRATO_HISTORICO.ID_ETAPA,
CONTRATO.ID_CONTRATO,
CONTRATO.COD_CONTRATO,
CONTRATO.ID_OBRA,
CONTRATO.ID_EMPREITEIRO,
CONTRATO.OBSERVACOES,
CONTRATO.ID_OBRA
FROM CONTRATO_HISTORICO
JOIN CONTRATO (NOLOCK) ON CONTRATO.ID_CONTRATO = CONTRATO_HISTORICO.ID_CONTRATO
WHERE CONTRATO_HISTORICO.ID_ETAPA = 2 
AND CONTRATO.ID_OBRA = 190


SELECT * FROM [dbo].[ETAPA]