DECLARE @COLIGADA				INT;
DECLARE @CHAPA					INT;
DECLARE @MES_INI					NVARCHAR(10);
DECLARE @MES_FIM					NVARCHAR(10);
DECLARE @ANO						INT;
DECLARE @PERIODO					INT;

SET @COLIGADA						= :COLIGADA	
SET @CHAPA								= :CHAPA	
SET @MES_INI								= :MES_INI
SET @MES_FIM								= :MES_FIM
SET @ANO									= :ANO
SET @PERIODO							= :PERIODO

SELECT LIQUIDO FROM PFPERFF
WHERE CODCOLIGADA = @COLIGADA
AND CHAPA = @CHAPA
AND MESCOMP BETWEEN @MES_INI AND @MES_FIM
AND ANOCOMP = @ANO
AND NROPERIODO = @PERIODO