SELECT DISTINCT (CASE
	  WHEN ITEM_ODC.QUANTIDADEARECEBER >0 THEN 'PROGRAMADO' 
	  WHEN ITEM_ODC.QUANTIDADEARECEBER = 0 THEN 'RECEBIDO'
	  WHEN ITEM_ODC.QUANTIDADEARECEBER < ITEM_ODC.QUANTIDADETOTAL THEN 'PARCIALMENTE RECEBIDO'
	  ELSE 'PENDENTE'
	  END) STATUS_ITEM_ODC
	  FROM TITMMOV AS ITEM_ODC
	  
