SELECT
TUSRTMV.CODCOLIGADA, 
TUSRTMV.CODUSUARIO, 
TUSRTMV.CODTMV, 
CODPERFIL, 
(CASE WHEN CONTABILIZAR = 1 THEN 'PODE CONTABILIZAR' ELSE 'NÃO PODE' END) CONTABILIZAR, 
(CASE WHEN INCLUIR = 1 THEN 'PODE INCLUIR' ELSE 'NÃO PODE' END) INCLUIR,
(CASE WHEN ALTERAR = 1 THEN 'PODE ALTERAR' ELSE 'NÃO PODE' END) ALTERAR,
(CASE WHEN EXCLUIR = 1 THEN 'PODE EXCLUIR' ELSE 'NÃO PODE' END) EXCLUIR,
(CASE WHEN CANCELAR = 1 THEN 'PODE CANCELAR' ELSE 'NÃO PODE' END) CANCELAR,
(CASE WHEN LANCAR = 1 THEN 'PODE LANCAR' ELSE 'NÃO PODE' END) LANCAR,
(CASE WHEN FATURAR = 1 THEN 'PODE FATURAR' ELSE 'NÃO PODE' END) FATURAR,
(CASE WHEN ATIVAR = 1 THEN 'PODE ATIVAR' ELSE 'NÃO PODE' END) ATIVAR,
(CASE WHEN REABRIR = 1 THEN 'PODE REABRIR' ELSE 'NÃO PODE' END) REABRIR,
(CASE WHEN CONSULTAR = 1 THEN 'PODE CONSULTAR' ELSE 'NÃO PODE' END) CONSULTAR,
(CASE WHEN COPIAR = 1 THEN 'PODE COPIAR' ELSE 'NÃO PODE' END) COPIAR,
(CASE WHEN COTAR = 1 THEN 'PODE COTAR' ELSE 'NÃO PODE' END) COTAR
FROM GUSRPERFIL 
LEFT JOIN TUSRTMV ON (TUSRTMV.CODUSUARIO = GUSRPERFIL.CODUSUARIO AND GUSRPERFIL.CODCOLIGADA = TUSRTMV.CODCOLIGADA)
LEFT JOIN GUSUARIO ON (GUSRPERFIL.CODUSUARIO= GUSUARIO.CODUSUARIO)
WHERE CODSISTEMA = 'T'
AND GUSUARIO.NOME IN (SELECT NOME FROM PFUNC WHERE CODSECAO NOT IN ('01.500.20','01.500.21','01.500.91') AND CODSITUACAO <> 'D') 
AND TUSRTMV.CODTMV IN ('1.1.21', '1.1.35')


SELECT * 
FROM GUSRPERFIL