SELECT
CODCOLIGADA,
(CONVERT(VARCHAR,GCOLIGADA.CODCOLIGADA) + ' - ' + GCOLIGADA.NOME) AS NOME

FROM GCOLIGADA (NOLOCK)
WHERE (GCOLIGADA.CODCOLIGADA =1 OR GCOLIGADA.CODCOLIGADA >=10)
AND GCOLIGADA.CODCOLIGADA NOT IN (54,61)