  SELECT  DISTINCT  obra.RM_NOME, aspnet_Users.UserName, perfil.NOM_PERFIL, RM_CODCOLIGADA, RM_CODFILIAL
  FROM PERFIL_USUARIO_OBRA 
  
  LEFT JOIN OBRA ON obra.ID_OBRA = PERFIL_USUARIO_OBRA.ID_OBRA
  LEFT JOIN aspnet_Users ON aspnet_Users.UserId = PERFIL_USUARIO_OBRA.UserId
  LEFT JOIN PERFIL ON perfil.ID_PERFIL = PERFIL_USUARIO_OBRA.ID_PERFIL
  
  WHERE aspnet_Users.UserName like '%wagner.fortes%'
