--ERRO AO QUITAR CONTRATO
ERRO: Contrato não foi quitado, existe FDV não liberada ou ficha liberada e não medida
**USAR SCRIP = "CONTRATO- FICHAS NÃO MEDIDAS"

VALIDAR SE TEM FICHA LIBERADA MAS SEM MEDIÇÃO E VERIFICAR QUAL A ETAPA QUE A MEDIÇÃO ESTÁ(PRECISA ESTAR NA ETAPA 4 = 'APROVADO PELO CONTROLE')