
DECLARE 
@DATA_CRIACAO_FIN AS DATE,
@DATA_CRIACAO_INI AS DATE,
@OBRA INT;

SET @DATA_CRIACAO_FIN = '20231010'
SET @DATA_CRIACAO_INI ='20230101'
SET @OBRA = (SELECT ID_OBRA FROM OBRA WHERE ID_OBRA = 190)

SELECT 

EMPREENDIMENTO.NOM_EMPREENDIMENTO,
OBRA.RM_NOME,
UPPER( EMPREITEIRO.NOM_EMPREITEIRO) AS NOM_EMPREITEIRO,


/* ENDEREÇO EMPREITEIRO */
UPPER (EMPREITEIRO.RM_DESCRICAO_TIPO_RUA + ': ' + 
REPLACE(REPLACE (REPLACE (EMPREITEIRO.RM_RUA,'RUA',''),'PRAÇA',''),'BECO','') + ', ' + 
EMPREITEIRO.RM_NUMERO +
(CASE WHEN EMPREITEIRO.RM_COMPLEMENTO IS NOT NULL  THEN REPLACE(REPLACE (REPLACE (EMPREITEIRO.RM_COMPLEMENTO,'RUA',''),'PRAÇA',''),'BECO','') ELSE '' END) + ' - ' +
EMPREITEIRO.RM_DESCRICAO_TIPO_BAIRRO + ': ' + 
EMPREITEIRO.RM_BAIRRO + ' - ' + 
EMPREITEIRO.RM_NOMEMUNICIPIO + ' / ' + EMPREITEIRO.RM_CODETD) AS ENDERECO,

EMPREITEIRO.RM_CEP,


CONTRATO.ID_CONTRATO,
REPLACE(CONTRATO.COD_CONTRATO,'/','-') AS COD_CONTRATO,
CONTRATO.DAT_INICIO_CONTRATO,
CONTRATO.DAT_FIM_CONTRATO,
CONTRATO.NUM_ADITAMENTO,
CASE WHEN CONTRATO.NUM_ADITAMENTO IS NULL THEN 'CONTRATO' ELSE 'ADITAMENTO' END AS 'TIPO DE CONTRATO',
/*
ALTERADO POR MARCELO SILVA 26/04/2023

(
SELECT COUNT(ID_CONTRATO_HISTORICO) FROM CONTRATO_HISTORICO WHERE CONTRATO.ID_CONTRATO = ID_CONTRATO AND ID_ETAPA = 6 AND USERID IN (
'97F6A256-4E47-4D57-BC82-166570D9F065', /*claudia*/
'57EFC58F-7771-420C-B64F-05B019D11ADB', /*silvana*/
'7AA22F18-6098-4292-86F5-4F9780DC5EBA', /*roxane*/
'1F538565-32FE-4E1D-BC79-2E9175D0C531', /*natalia*/
'1A2A9D5E-E45D-42D5-BB12-31C32B730505', /*thais*/
'507135AC-2CAB-48E6-8E5F-DD281262A0DA' /*marielen*/
)) AS DESAPROVACOES_SECRETARIA, */

(
SELECT COUNT(ID_CONTRATO_HISTORICO) FROM CONTRATO_HISTORICO WHERE CONTRATO.ID_CONTRATO = ID_CONTRATO AND ID_ETAPA = 6 AND USERID IN (
SELECT DISTINCT PERFIL_USUARIO_OBRA.UserId FROM PERFIL_USUARIO_OBRA WHERE ID_PERFIL = 5 /*SECRETARIA*/
)) DESAPROVACOES_SECRETARIA,


ISNULL(convert(datetime,(CONTRATO.DAT_CRIACAO),103),'NULL') AS DATA_CRIACAO,

RIGHT (CONVERT (VARCHAR,CONTRATO.DAT_CADASTRO,103),7) AS PERIODO,

ISNULL((SELECT MIN (convert(datetime,(CONTRATO_HISTORICO.DAT_HISTORICO),103)) FROM CONTRATO_HISTORICO WHERE CONTRATO_HISTORICO.ID_CONTRATO = CONTRATO.ID_CONTRATO AND CONTRATO_HISTORICO.ID_ETAPA =2),NULL) AS 'DATA DO PRIMEIRO CADASTRO',
ISNULL((SELECT TOP 1  CONTRATO_HISTORICO.OBSERVACOES FROM CONTRATO_HISTORICO WHERE ID_CONTRATO = CONTRATO.ID_CONTRATO AND ID_ETAPA =2 ORDER BY CONTRATO_HISTORICO.ID_CONTRATO_HISTORICO),'NULL')  AS 'OBS DATA DO PRIMEIRO CADASTRO',

ISNULL((SELECT MAX (convert(datetime,(CONTRATO_HISTORICO.DAT_HISTORICO),103)) FROM CONTRATO_HISTORICO WHERE CONTRATO_HISTORICO.ID_CONTRATO = CONTRATO.ID_CONTRATO AND CONTRATO_HISTORICO.ID_ETAPA =2),NULL) AS 'DATA DO ULTIMO CADASTRO',
ISNULL((SELECT TOP 1  CONTRATO_HISTORICO.OBSERVACOES FROM CONTRATO_HISTORICO WHERE ID_CONTRATO = CONTRATO.ID_CONTRATO AND ID_ETAPA =2 ORDER BY CONTRATO_HISTORICO.ID_CONTRATO_HISTORICO DESC),'NULL')  AS 'OBS DATA DO ULTIMO CADASTRO',

ISNULL((SELECT MIN (convert(datetime,(CONTRATO_HISTORICO.DAT_HISTORICO),103)) FROM CONTRATO_HISTORICO WHERE CONTRATO_HISTORICO.ID_CONTRATO = CONTRATO.ID_CONTRATO AND CONTRATO_HISTORICO.ID_ETAPA =3),NULL) AS 'DATA PRIMEIRA APROVAÇÃO ENGENHARIA',
ISNULL((SELECT TOP 1  CONTRATO_HISTORICO.OBSERVACOES FROM CONTRATO_HISTORICO WHERE ID_CONTRATO = CONTRATO.ID_CONTRATO AND ID_ETAPA =3 ORDER BY CONTRATO_HISTORICO.ID_CONTRATO_HISTORICO),'NULL')  AS 'OBS DATA PRIMEIRA APROVAÇÃO ENGENHARIA',

ISNULL((SELECT MAX (convert(datetime,(CONTRATO_HISTORICO.DAT_HISTORICO),103)) FROM CONTRATO_HISTORICO WHERE CONTRATO_HISTORICO.ID_CONTRATO = CONTRATO.ID_CONTRATO AND CONTRATO_HISTORICO.ID_ETAPA =3),NULL) AS 'DATA ULTIMA APROVAÇÃO ENGENHARIA',
ISNULL((SELECT TOP 1  CONTRATO_HISTORICO.OBSERVACOES FROM CONTRATO_HISTORICO WHERE ID_CONTRATO = CONTRATO.ID_CONTRATO AND ID_ETAPA =3 ORDER BY CONTRATO_HISTORICO.ID_CONTRATO_HISTORICO DESC),'NULL')   AS 'OBS DATA ULTIMA APROVAÇÃO ENGENHARIA',

ISNULL((SELECT MAX (convert(datetime,(CONTRATO_HISTORICO.DAT_HISTORICO),103)) FROM CONTRATO_HISTORICO WHERE CONTRATO_HISTORICO.ID_CONTRATO = CONTRATO.ID_CONTRATO AND CONTRATO_HISTORICO.ID_ETAPA =5),NULL) AS 'DATA ULTIMO APROVAÇÃO SECRETARIA',
ISNULL((SELECT TOP 1  dbo.TRAZ_USERNAME(CONTRATO_HISTORICO.UserId) FROM CONTRATO_HISTORICO WHERE ID_CONTRATO = CONTRATO.ID_CONTRATO AND ID_ETAPA =5 ORDER BY CONTRATO_HISTORICO.ID_CONTRATO_HISTORICO DESC),'NULL')  AS 'USUARIO ULTIMO APROVAÇÃO SECRETARIA',
ISNULL((SELECT TOP 1  CONTRATO_HISTORICO.OBSERVACOES FROM CONTRATO_HISTORICO WHERE ID_CONTRATO = CONTRATO.ID_CONTRATO AND ID_ETAPA =5 ORDER BY CONTRATO_HISTORICO.ID_CONTRATO_HISTORICO DESC),'NULL')  AS 'OBS DATA ULTIMO APROVAÇÃO SECRETARIA',

ISNULL((SELECT MAX (convert(datetime,(CONTRATO_HISTORICO.DAT_HISTORICO),103)) FROM CONTRATO_HISTORICO WHERE CONTRATO_HISTORICO.ID_CONTRATO = CONTRATO.ID_CONTRATO AND CONTRATO_HISTORICO.ID_ETAPA =7),NULL) AS 'DATA ULTIMA ASSINATURA DIRETORIA 1',
ISNULL((SELECT TOP 1  CONTRATO_HISTORICO.OBSERVACOES FROM CONTRATO_HISTORICO WHERE ID_CONTRATO = CONTRATO.ID_CONTRATO AND ID_ETAPA =7 ORDER BY CONTRATO_HISTORICO.ID_CONTRATO_HISTORICO DESC),'NULL')  AS 'OBS DATA ULTIMA ASSINATURA DIRETORIA 1',

ISNULL((SELECT MAX (convert(date,convert(varchar(4),year(CONTRATO_HISTORICO.DAT_HISTORICO)) + '-' + convert(varchar(2),month(CONTRATO_HISTORICO.DAT_HISTORICO)) + '-' +  convert(varchar(2),day(CONTRATO_HISTORICO.DAT_HISTORICO)))) FROM CONTRATO_HISTORICO WHERE CONTRATO_HISTORICO.ID_CONTRATO = CONTRATO.ID_CONTRATO AND CONTRATO_HISTORICO.ID_ETAPA =8),NULL) AS 'DATA ULTIMA ASSINATURA DIRETORIA 2',
ISNULL((SELECT TOP 1  CONTRATO_HISTORICO.OBSERVACOES FROM CONTRATO_HISTORICO WHERE ID_CONTRATO = CONTRATO.ID_CONTRATO AND ID_ETAPA =8 ORDER BY CONTRATO_HISTORICO.ID_CONTRATO_HISTORICO DESC),'NULL')  AS 'OBS DATA ULTIMA ASSINATURA DIRETORIA 2',
CONTRATO.DATA_PRIMEIRA_INTEGRACAO,



ISNULL((SELECT MAX (convert(datetime,(CONTRATO_HISTORICO.DAT_HISTORICO),103)) FROM CONTRATO_HISTORICO WHERE CONTRATO_HISTORICO.ID_CONTRATO = CONTRATO.ID_CONTRATO AND CONTRATO_HISTORICO.ID_ETAPA =9),NULL) AS 'DATA ULTIMO ENVIO PARA OBRA',
ISNULL((SELECT TOP 1  CONTRATO_HISTORICO.OBSERVACOES FROM CONTRATO_HISTORICO WHERE ID_CONTRATO = CONTRATO.ID_CONTRATO AND ID_ETAPA =9 ORDER BY CONTRATO_HISTORICO.ID_CONTRATO_HISTORICO DESC),'NULL')  AS 'OBS DATA ULTIMO ENVIO PARA OBRA',

ISNULL((SELECT MAX (convert(datetime,(CONTRATO_HISTORICO.DAT_HISTORICO),103)) FROM CONTRATO_HISTORICO WHERE CONTRATO_HISTORICO.ID_CONTRATO = CONTRATO.ID_CONTRATO AND CONTRATO_HISTORICO.ID_ETAPA =10),NULL) AS 'DATA ULTIMO RETORNO DA OBRA',
ISNULL((SELECT TOP 1  CONTRATO_HISTORICO.OBSERVACOES FROM CONTRATO_HISTORICO WHERE ID_CONTRATO = CONTRATO.ID_CONTRATO AND ID_ETAPA =10 ORDER BY CONTRATO_HISTORICO.ID_CONTRATO_HISTORICO DESC),'NULL')  AS 'OBS DATA ULTIMO RETORNO DA OBRA',

ISNULL((SELECT MAX (convert(datetime,(CONTRATO_HISTORICO.DAT_HISTORICO),103)) FROM CONTRATO_HISTORICO WHERE CONTRATO_HISTORICO.ID_CONTRATO = CONTRATO.ID_CONTRATO AND CONTRATO_HISTORICO.ID_ETAPA =12),NULL) AS 'DATA ULTIMO TERMO DE QUITAÇÃO ASSINADO',
ISNULL((SELECT TOP 1  CONTRATO_HISTORICO.OBSERVACOES FROM CONTRATO_HISTORICO WHERE ID_CONTRATO = CONTRATO.ID_CONTRATO AND ID_ETAPA =12 ORDER BY CONTRATO_HISTORICO.ID_CONTRATO_HISTORICO DESC),'NULL')  AS 'OBS DATA ULTIMO TERMO DE QUITAÇÃO ASSINADO',

ISNULL((SELECT MAX (convert(datetime,(CONTRATO_HISTORICO.DAT_HISTORICO),103)) FROM CONTRATO_HISTORICO WHERE CONTRATO_HISTORICO.ID_CONTRATO = CONTRATO.ID_CONTRATO AND CONTRATO_HISTORICO.ID_ETAPA =13),NULL) AS 'DATA ULTIMA NOTIFICAÇÃO VIA AR',
ISNULL((SELECT TOP 1  CONTRATO_HISTORICO.OBSERVACOES FROM CONTRATO_HISTORICO WHERE ID_CONTRATO = CONTRATO.ID_CONTRATO AND ID_ETAPA =13 ORDER BY CONTRATO_HISTORICO.ID_CONTRATO_HISTORICO DESC),'NULL')  AS 'OBS DATA ULTIMA NOTIFICAÇÃO VIA AR',

ISNULL((SELECT MAX (convert(datetime,(CONTRATO_HISTORICO.DAT_HISTORICO),103)) FROM CONTRATO_HISTORICO WHERE CONTRATO_HISTORICO.ID_CONTRATO = CONTRATO.ID_CONTRATO AND CONTRATO_HISTORICO.ID_ETAPA =14),NULL) AS 'DATA ULTIMA PENDENCIA',
ISNULL((SELECT TOP 1  CONTRATO_HISTORICO.OBSERVACOES FROM CONTRATO_HISTORICO WHERE ID_CONTRATO = CONTRATO.ID_CONTRATO AND ID_ETAPA =14 ORDER BY CONTRATO_HISTORICO.ID_CONTRATO_HISTORICO DESC),'NULL')  AS 'OBS DATA ULTIMA PENDENCIA',

ISNULL((SELECT MAX (convert(datetime,(CONTRATO_HISTORICO.DAT_HISTORICO),103)) FROM CONTRATO_HISTORICO WHERE CONTRATO_HISTORICO.ID_CONTRATO = CONTRATO.ID_CONTRATO AND CONTRATO_HISTORICO.ID_ETAPA =15),NULL) AS 'CONTRATO MODELO FORNECEDOR ENVIADO PARA APROVAÇÃO DO JURÍDICO',
ISNULL((SELECT TOP 1  CONTRATO_HISTORICO.OBSERVACOES FROM CONTRATO_HISTORICO WHERE ID_CONTRATO = CONTRATO.ID_CONTRATO AND ID_ETAPA =15 ORDER BY CONTRATO_HISTORICO.ID_CONTRATO_HISTORICO DESC),'NULL')  AS 'OBS CONTRATO MODELO FORNECEDOR ENVIADO PARA APROVAÇÃO DO JURÍDICO',

ISNULL((SELECT MAX (convert(datetime,(CONTRATO_HISTORICO.DAT_HISTORICO),103)) FROM CONTRATO_HISTORICO WHERE CONTRATO_HISTORICO.ID_CONTRATO = CONTRATO.ID_CONTRATO AND CONTRATO_HISTORICO.ID_ETAPA =16),null) AS 'CONTRATO MODELO FORNECEDOR APROVADO PELO JURÍDICO',
ISNULL((SELECT TOP 1  CONTRATO_HISTORICO.OBSERVACOES FROM CONTRATO_HISTORICO WHERE ID_CONTRATO = CONTRATO.ID_CONTRATO AND ID_ETAPA =16 ORDER BY CONTRATO_HISTORICO.ID_CONTRATO_HISTORICO DESC),'NULL')  AS 'OBS CONTRATO MODELO FORNECEDOR APROVADO PELO JURÍDICO',


ISNULL(CONTRATO.DAT_QUITACAO,null) AS DATA_QUITACAO,

(
	CORPORE_RESIDENCIAL.DBO.DIAS_UTEIS (
	(SELECT MIN (CONVERT (DATETIME,LEFT (CONTRATO_HISTORICO.DAT_HISTORICO,11))) 
	FROM CONTRATO_HISTORICO WHERE CONTRATO_HISTORICO.ID_CONTRATO = CONTRATO.ID_CONTRATO AND CONTRATO_HISTORICO.ID_ETAPA =2),
	(SELECT MAX (CONVERT (DATETIME,LEFT (DAT_HISTORICO,11))) FROM CONTRATO_HISTORICO WHERE ID_CONTRATO = CONTRATO.ID_CONTRATO AND ID_ETAPA =5)) 
)AS 'PRIMEIRA DATA DE CADASTRO X ULTIMA APROVACAO SECRETARIA',

(
	CORPORE_RESIDENCIAL.DBO.DIAS_UTEIS (
	(SELECT MIN (CONVERT (DATETIME,LEFT (CONTRATO_HISTORICO.DAT_HISTORICO,11))) 
	FROM CONTRATO_HISTORICO WHERE CONTRATO_HISTORICO.ID_CONTRATO = CONTRATO.ID_CONTRATO AND CONTRATO_HISTORICO.ID_ETAPA =3),
	(SELECT MAX (CONVERT (DATETIME,LEFT (DAT_HISTORICO,11))) 
	FROM CONTRATO_HISTORICO WHERE ID_CONTRATO = CONTRATO.ID_CONTRATO AND ID_ETAPA =5)) 
)AS 'PRIMEIRA APROVAÇÃO ENGENHARIA X ULTIMA APROVACAO SECRETARIA',


(
	CORPORE_RESIDENCIAL.DBO.DIAS_UTEIS (
	(SELECT MIN (CONVERT (DATETIME,LEFT (CONTRATO_HISTORICO.DAT_HISTORICO,11))) 
	FROM CONTRATO_HISTORICO WHERE CONTRATO_HISTORICO.ID_CONTRATO = CONTRATO.ID_CONTRATO AND CONTRATO_HISTORICO.ID_ETAPA =2),
	(SELECT MAX (CONVERT (DATETIME,LEFT (DAT_HISTORICO,11))) 
	FROM CONTRATO_HISTORICO WHERE ID_CONTRATO = CONTRATO.ID_CONTRATO AND ID_ETAPA =8))

)AS 'PRIMEIRA DATA DE CADASTRO X ULTIMA DATA DE ASS. DIRETORIA 2',

DATEDIFF(DAY,ISNULL((SELECT MAX (CONVERT (DATETIME,LEFT (DAT_HISTORICO,11))) FROM CONTRATO_HISTORICO WHERE ID_CONTRATO = CONTRATO.ID_CONTRATO AND ID_ETAPA =8), @DATA_CRIACAO_FIN),CONTRATO.DATA_PRIMEIRA_INTEGRACAO) AS 'ULTIMA DATA DE ASS. DIRETORIA 2 X DATA INTEGRACAO',


CORPORE_RESIDENCIAL.DBO.DIAS_UTEIS ((SELECT MAX (CONVERT (DATETIME,LEFT (CONTRATO_HISTORICO.DAT_HISTORICO,11)))
FROM CONTRATO_HISTORICO WHERE CONTRATO_HISTORICO.ID_CONTRATO = CONTRATO.ID_CONTRATO AND CONTRATO_HISTORICO.ID_ETAPA =2),
(SELECT MAX (CONVERT (DATETIME,LEFT (DAT_HISTORICO,11))) FROM CONTRATO_HISTORICO WHERE ID_CONTRATO = CONTRATO.ID_CONTRATO AND ID_ETAPA = 3))
AS 'ULTIMA_DATA_DE_CADASTRO_X_ULTIMA_APROVAÇÃO_ENGENHARIA',

CORPORE_RESIDENCIAL.DBO.DIAS_UTEIS ((SELECT MAX (CONVERT (DATETIME,LEFT (CONTRATO_HISTORICO.DAT_HISTORICO,11)))
FROM CONTRATO_HISTORICO WHERE CONTRATO_HISTORICO.ID_CONTRATO = CONTRATO.ID_CONTRATO AND CONTRATO_HISTORICO.ID_ETAPA = 3)
,(SELECT MAX (CONVERT (DATETIME,LEFT (DAT_HISTORICO,11))) FROM CONTRATO_HISTORICO WHERE ID_CONTRATO = CONTRATO.ID_CONTRATO AND ID_ETAPA = 5))
AS 'ULTIMA_APROVAÇÃO_ENGENHARIA_X_ULTIMA_APROVAÇÃO_SECRETARIA',

CORPORE_RESIDENCIAL.DBO.DIAS_UTEIS ((SELECT MAX (CONVERT (DATETIME,LEFT (CONTRATO_HISTORICO.DAT_HISTORICO,11)))
FROM CONTRATO_HISTORICO WHERE CONTRATO_HISTORICO.ID_CONTRATO = CONTRATO.ID_CONTRATO AND CONTRATO_HISTORICO.ID_ETAPA = 3)
,(SELECT MAX (CONVERT (DATETIME,LEFT (DAT_HISTORICO,11))) FROM CONTRATO_HISTORICO WHERE ID_CONTRATO = CONTRATO.ID_CONTRATO AND ID_ETAPA = 8))
AS 'ULTIMA_APROVAÇÃO_SECRETARIA_X_ULTIMA_ASSINATURA_DIRETORIA_2',

CORPORE_RESIDENCIAL.DBO.DIAS_UTEIS ((SELECT MAX (CONVERT (DATETIME,LEFT (CONTRATO_HISTORICO.DAT_HISTORICO,11)))
FROM CONTRATO_HISTORICO WHERE CONTRATO_HISTORICO.ID_CONTRATO = CONTRATO.ID_CONTRATO AND CONTRATO_HISTORICO.ID_ETAPA = 2)
,(SELECT MAX (CONVERT (DATETIME,LEFT (DAT_HISTORICO,11))) FROM CONTRATO_HISTORICO WHERE ID_CONTRATO = CONTRATO.ID_CONTRATO AND ID_ETAPA = 5))
AS 'ULTIMA_DATA_DE_CADASTRO_X_ULTIMA_APROVAÇÃO_SECRETARIA',

CORPORE_RESIDENCIAL.DBO.DIAS_UTEIS ((SELECT MAX (CONVERT (DATETIME,LEFT (CONTRATO_HISTORICO.DAT_HISTORICO,11)))
FROM CONTRATO_HISTORICO WHERE CONTRATO_HISTORICO.ID_CONTRATO = CONTRATO.ID_CONTRATO AND CONTRATO_HISTORICO.ID_ETAPA = 8)
,(SELECT (CONVERT (DATETIME,LEFT (DAT_HISTORICO,11))) FROM CONTRATO_HISTORICO WHERE ID_CONTRATO = CONTRATO.ID_CONTRATO AND ID_ETAPA = 1))
AS 'ULTIMA_ASSINATURA_DIRETORIA_2_X_DATA_INTEGRAÇÃO',

CORPORE_RESIDENCIAL.DBO.DIAS_UTEIS ((SELECT MIN (CONVERT (DATETIME,LEFT (CONTRATO_HISTORICO.DAT_HISTORICO,11)))
FROM CONTRATO_HISTORICO WHERE CONTRATO_HISTORICO.ID_CONTRATO = CONTRATO.ID_CONTRATO AND CONTRATO_HISTORICO.ID_ETAPA = 2)
,(SELECT MAX (CONVERT (DATETIME,LEFT (DAT_HISTORICO,11))) FROM CONTRATO_HISTORICO WHERE ID_CONTRATO = CONTRATO.ID_CONTRATO AND ID_ETAPA = 8))
AS 'PRIMEIRA_DATA_DE_CADASTRO_X_ULTIMA_ASSINATURA_DIRETORIA_2',

CORPORE_RESIDENCIAL.DBO.DIAS_UTEIS ((SELECT MAX (CONVERT (DATETIME,LEFT (CONTRATO_HISTORICO.DAT_HISTORICO,11)))
FROM CONTRATO_HISTORICO WHERE CONTRATO_HISTORICO.ID_CONTRATO = CONTRATO.ID_CONTRATO AND CONTRATO_HISTORICO.ID_ETAPA = 2)
,(SELECT MAX (CONVERT (DATETIME,LEFT (DAT_HISTORICO,11))) FROM CONTRATO_HISTORICO WHERE ID_CONTRATO = CONTRATO.ID_CONTRATO AND ID_ETAPA = 8))
AS 'ULTIMA_ASSINATURA_DIRETORIA_2_X_ULTIMA_ASSINATURA_DIRETORIA_2',

OBJETO_CONTRATO.ID_OBJETO_CONTRATO,
OBJETO_CONTRATO.NOM_OBJETO_CONTRATO,
EMPREITEIRO.RM_CNPJ,

CASE WHEN 

(SELECT MAX (CONTRATO_HISTORICO.DAT_HISTORICO) FROM CONTRATO_HISTORICO WHERE CONTRATO_HISTORICO.ID_CONTRATO = CONTRATO.ID_CONTRATO AND CONTRATO_HISTORICO.ID_ETAPA =5) IS NULL
AND (SELECT MAX (CONTRATO_HISTORICO.DAT_HISTORICO) FROM CONTRATO_HISTORICO WHERE CONTRATO_HISTORICO.ID_CONTRATO = CONTRATO.ID_CONTRATO AND CONTRATO_HISTORICO.ID_ETAPA =8) IS NULL 

THEN 'NULL' 

WHEN (SELECT MAX (CONTRATO_HISTORICO.DAT_HISTORICO) FROM CONTRATO_HISTORICO WHERE CONTRATO_HISTORICO.ID_CONTRATO = CONTRATO.ID_CONTRATO AND CONTRATO_HISTORICO.ID_ETAPA =5) IS NOT NULL
AND (SELECT MAX (CONTRATO_HISTORICO.DAT_HISTORICO) FROM CONTRATO_HISTORICO WHERE CONTRATO_HISTORICO.ID_CONTRATO = CONTRATO.ID_CONTRATO AND CONTRATO_HISTORICO.ID_ETAPA =8) IS NULL 

THEN 'ASSINATURA PENDENTE'

ELSE 'CONTRATO ASSINADO' END AS 'RESULTADO',

CASE WHEN DATEDIFF(DAY,(SELECT MIN (CONTRATO_HISTORICO.DAT_HISTORICO) FROM CONTRATO_HISTORICO WHERE CONTRATO_HISTORICO.ID_CONTRATO = CONTRATO.ID_CONTRATO AND CONTRATO_HISTORICO.ID_ETAPA =2),
ISNULL((SELECT MAX (CONTRATO_HISTORICO.DAT_HISTORICO) FROM CONTRATO_HISTORICO WHERE CONTRATO_HISTORICO.ID_CONTRATO = CONTRATO.ID_CONTRATO AND CONTRATO_HISTORICO.ID_ETAPA =8),'20191114')) <= 4
THEN 'Faixa 1 - de 0 a 4 dias'
WHEN DATEDIFF(DAY,(SELECT MIN (CONTRATO_HISTORICO.DAT_HISTORICO) FROM CONTRATO_HISTORICO WHERE CONTRATO_HISTORICO.ID_CONTRATO = CONTRATO.ID_CONTRATO AND CONTRATO_HISTORICO.ID_ETAPA =2),
ISNULL((SELECT MAX (CONTRATO_HISTORICO.DAT_HISTORICO) FROM CONTRATO_HISTORICO WHERE CONTRATO_HISTORICO.ID_CONTRATO = CONTRATO.ID_CONTRATO AND CONTRATO_HISTORICO.ID_ETAPA =8),'20191114')) <= 6
THEN 'Faixa 2 - de 5 a 6 dias'
WHEN DATEDIFF(DAY,(SELECT MIN (CONTRATO_HISTORICO.DAT_HISTORICO) FROM CONTRATO_HISTORICO WHERE CONTRATO_HISTORICO.ID_CONTRATO = CONTRATO.ID_CONTRATO AND CONTRATO_HISTORICO.ID_ETAPA =2),
ISNULL((SELECT MAX (CONTRATO_HISTORICO.DAT_HISTORICO) FROM CONTRATO_HISTORICO WHERE CONTRATO_HISTORICO.ID_CONTRATO = CONTRATO.ID_CONTRATO AND CONTRATO_HISTORICO.ID_ETAPA =8),'20191114')) <= 9
THEN 'Faixa 3 - de 7 a 9 dias'
WHEN DATEDIFF(DAY,(SELECT MIN (CONTRATO_HISTORICO.DAT_HISTORICO) FROM CONTRATO_HISTORICO WHERE CONTRATO_HISTORICO.ID_CONTRATO = CONTRATO.ID_CONTRATO AND CONTRATO_HISTORICO.ID_ETAPA =2),
ISNULL((SELECT MAX (CONTRATO_HISTORICO.DAT_HISTORICO) FROM CONTRATO_HISTORICO WHERE CONTRATO_HISTORICO.ID_CONTRATO = CONTRATO.ID_CONTRATO AND CONTRATO_HISTORICO.ID_ETAPA =8),'20191114')) >= 9
THEN 'Faixa 4 - maior que 10 dias'

ELSE  NULL
END AS FAIXA,


CORPORE_RESIDENCIAL.DBO.DIAS_UTEIS (ISNULL((SELECT MAX (convert(datetime,(CONTRATO_HISTORICO.DAT_HISTORICO),103)) FROM CONTRATO_HISTORICO WHERE CONTRATO_HISTORICO.ID_CONTRATO = CONTRATO.ID_CONTRATO AND CONTRATO_HISTORICO.ID_ETAPA =5),NULL),
ISNULL((SELECT MAX (convert(date,convert(varchar(4),year(CONTRATO_HISTORICO.DAT_HISTORICO)) + '-' + convert(varchar(2),month(CONTRATO_HISTORICO.DAT_HISTORICO)) + '-' +  convert(varchar(2),day(CONTRATO_HISTORICO.DAT_HISTORICO)))) FROM CONTRATO_HISTORICO WHERE CONTRATO_HISTORICO.ID_CONTRATO = CONTRATO.ID_CONTRATO AND CONTRATO_HISTORICO.ID_ETAPA =8),NULL) )AS 'DATA ULTIMO APROVAÇÃO SECRETARIA X DATA ULTIMA ASSINATURA DIRETORIA 2',

CORPORE_RESIDENCIAL.DBO.DIAS_UTEIS (ISNULL((SELECT MIN (convert(datetime,(CONTRATO_HISTORICO.DAT_HISTORICO),103)) FROM CONTRATO_HISTORICO WHERE CONTRATO_HISTORICO.ID_CONTRATO = CONTRATO.ID_CONTRATO AND CONTRATO_HISTORICO.ID_ETAPA =3),NULL),
ISNULL((SELECT MIN (convert(datetime,(CONTRATO_HISTORICO.DAT_HISTORICO),103)) FROM CONTRATO_HISTORICO WHERE CONTRATO_HISTORICO.ID_CONTRATO = CONTRATO.ID_CONTRATO AND CONTRATO_HISTORICO.ID_ETAPA =2),NULL)) AS 'PRIMEIRA DATA DE CADASTRO X PRIMEIRAAPROVAÇÃO ENGENHARIA'

FROM CONTRATO 

INNER JOIN OBRA				(NOLOCK) ON (OBRA.ID_OBRA = CONTRATO.ID_OBRA)
INNER JOIN EMPREENDIMENTO	(NOLOCK) ON (EMPREENDIMENTO.ID_EMPREENDIMENTO = OBRA.ID_EMPREENDIMENTO)
INNER JOIN EMPREITEIRO		(NOLOCK) ON (EMPREITEIRO.ID_EMPREITEIRO = CONTRATO.ID_EMPREITEIRO)	
INNER JOIN OBJETO_CONTRATO	(NOLOCK) ON (OBJETO_CONTRATO.ID_OBJETO_CONTRATO = CONTRATO.ID_OBJETO_CONTRATO)


WHERE	EXCLUIDO <> 1
AND		((CONTRATO.FLAG_GLOBAL = 1
AND		OBRA.FLG_OBRA_BASE = 1)
OR		CONTRATO.FLAG_GLOBAL = 0)


AND CONTRATO.DAT_CRIACAO BETWEEN @DATA_CRIACAO_INI AND @DATA_CRIACAO_FIN
AND OBRA.ID_OBRA IN (@OBRA)
AND CONTRATO.ID_CONTRATO NOT IN (6007,11709,14860,16299)