SELECT
(CASE
	  WHEN ITEM_ODC.QUANTIDADEARECEBER >0 THEN 'PROGRAMADO' 
	  WHEN ITEM_ODC.QUANTIDADEARECEBER = 0 THEN 'RECEBIDO'
	  WHEN ITEM_ODC.QUANTIDADEARECEBER < ITEM_ODC.QUANTIDADETOTAL THEN 'PARCIALMENTE RECEBIDO'
	  WHEN ITEM_ODC.QUANTIDADEARECEBER = ITEM_ODC.QUANTIDADETOTAL THEN 'PENDENTE'		
END) AS [STATUS_NOVO]
FROM TITMMOV AS ITEM_ODC
WHERE (SELECT 'PROGRAMADO') IN ('PROGRAMADO', 'PENDENTE', 'PARCIALMENTE RECEBIDO', 'PENDENTE');
