SELECT  
GJOBX.CODCOLIGADA,
GJOBX.NOME,
GJOBXEXECUCAO.* 
FROM GJOBXEXECUCAO 
INNER JOIN GJOBX (NOLOCK) on (GJOBX.IDJOB = GJOBXEXECUCAO.IDJOB)
WHERE 
GJOBXEXECUCAO.IDJOB in (select idjob from gjobx where nome like '%saldos%' and codusuario = 'job') 
AND PERCPROGRESSO < 100
AND DATAINIEXEC >= '20230807'
ORDER BY 
GJOBX.CODCOLIGADA


SELECT * FROM PFUNC WHERE CODCOLIGADA = 1