DECLARE @ID_CONTRATO INT = 54511
DECLARE @ID_EMPREITEIRO INT = 4093
DECLARE @ID_OBRA INT = 153

 

SELECT ITEM_EMPREENDIMENTO.ID_ITEM_EMPREENDIMENTO
    , ITEM_EMPREENDIMENTO.CODIGO
    , ITEM_EMPREENDIMENTO.REVISAO
    , MEDICAO.ID_MEDICAO


 

 

FROM MEDICAO_ITEM_EMPREENDIMENTO
INNER JOIN ITEM_EMPREENDIMENTO ON ITEM_EMPREENDIMENTO.ID_ITEM_EMPREENDIMENTO = MEDICAO_ITEM_EMPREENDIMENTO.ID_ITEM_EMPREENDIMENTO
INNER JOIN MEDICAO ON MEDICAO.ID_MEDICAO = MEDICAO_ITEM_EMPREENDIMENTO.ID_MEDICAO
WHERE
         MEDICAO.ID_CONTRATO = @ID_CONTRATO    
    AND MEDICAO_ITEM_EMPREENDIMENTO.ID_ITEM_EMPREENDIMENTO NOT IN (
        SELECT ID_ITEM_EMPREENDIMENTO
        FROM CONTRATO_ITEM_EMPREENDIMENTO
        WHERE ID_CONTRATO IN (
                SELECT DISTINCT (CONTRATO.ID_CONTRATO)
                FROM CONTRATO
                INNER JOIN CONTRATO_ITEM_EMPREENDIMENTO ON CONTRATO.ID_CONTRATO = CONTRATO_ITEM_EMPREENDIMENTO.ID_CONTRATO
                WHERE CONTRATO.ID_EMPREITEIRO = @ID_EMPREITEIRO
                    AND ID_OBRA = @ID_OBRA
                )
        )
GROUP BY ITEM_EMPREENDIMENTO.CODIGO
    , ITEM_EMPREENDIMENTO.REVISAO
    , ITEM_EMPREENDIMENTO.ID_ITEM_EMPREENDIMENTO
    , MEDICAO.ID_MEDICAO

 