

SELECT 
ID_KIT_MATERIAL,
RMO.KIT .ID_KIT,
RMO.KIT_MATERIAL.RM_CODCOLIGADA,
RMO.KIT_MATERIAL.RM_NOMEFANTASIA,
RMO.KIT_MATERIAL.RM_CODIGOPRD, 
RMO.KIT_MATERIAL.QUANTIDADE,
RMO.KIT.NOME AS KIT_NOME,
RMO.KIT.ID_CLASSE,
RMO.KIT.LOCAL_APLICACAO,
RMO.KIT.ID_EMPREENDIMENTO
 
FROM [RMO].[KIT] 
JOIN [RMO].[KIT_MATERIAL] ON [RMO].[KIT_MATERIAL].ID_KIT = [RMO].[KIT] .ID_KIT

WHERE RM_NOMEFANTASIA like ' %FCK%' 
--RM_CODIGOPRD = 'MCON.002.001.0004'
--AND [RMO].[KIT] .ID_EMPREENDIMENTO = 100
--AND RM_CODCOLIGADA = 22




