SELECT DISTINCT 
TPRODUTO.CODCOLPRD,
TPRODUTO.CODIGOPRD,
TPRODUTO.NOMEFANTASIA,
TPRODUTO.DTCADASTRAMENTO,
TPRODUTO.USUARIOCRIACAO,
TPRODUTODEF.CODUNDCOMPRA,
(CASE WHEN TPRODUTO.INATIVO = 0 THEN 'ATIVO' ELSE 'INATIVO' END) AS INATIVACAO_COMPLETA,
(CASE WHEN TPRDCOMPL.INATIVO = 'T' THEN 'PARCIALMENTE INATIVO' 
			/*WHEN TPRDCOMPL.INATIVO = 'F' THEN 'ATIVO'
			WHEN TPRDCOMPL.INATIVO IS NULL THEN 'ATIVO'*/
			ELSE 'ATIVO' END) AS INATIVACAO_PARCIAL
FROM TPRODUTO
JOIN TPRODUTODEF ON TPRODUTODEF.NUMNOFABRIC = TPRODUTO.CODIGOPRD
JOIN TPRDCOMPL ON TPRDCOMPL.IDPRD = TPRODUTO.IDPRD

WHERE CONVERT(VARCHAR, TPRODUTO.INATIVO) IN (@ATIVACAO_RM) 
AND CONVERT(VARCHAR, TPRDCOMPL.INATIVO) IN (@ATIVACAO_PARCIAL)

ORDER BY 
TPRODUTO.NOMEFANTASIA