SELECT 
FCFO.CODCOLIGADA,
FCFO.CODCFO,
FCFO.NOME,
FCFO.CGCCFO,
FCFO.USUARIOCRIACAO,
CONVERT(VARCHAR, FCFO.DATACRIACAO, 103) AS 'DATA_CRIAÇÃO', /*CAMPO INSERIDO DEVIDO AO CHAMADO 0623-001011*/
(
	CASE WHEN FCFO.ATIVO = 1 THEN 'SIM'
	ELSE 'NÃO' END) AS ATIVO,
(
	CASE
	WHEN FCFO.CFOIMOB = 1 THEN 'SIM'
	ELSE 'NÃO' END
) AS BLOQUEADO,
FCFO.TELEFONE AS TELEFONE,
(
	CASE WHEN FCFODEF.CODTB2FLX IS NOT NULL THEN CODTB2FLX
	ELSE 'NAO PREENCHIDO'
	END
) AS 'CLASSIFICAÇÃO FINANCEIRA'

FROM FCFO (NOLOCK)

LEFT JOIN FCFODEF (NOLOCK) ON (FCFODEF.CODCFO = FCFO.CODCFO AND  FCFODEF.CODCOLCFO = FCFO.CODCOLIGADA)
 
WHERE 
FCFO.DATACRIACAO BETWEEN  @DATA_INI AND @DATA_FIM AND
FCFODEF.CODTB2FLX IN (@CLASSIFI_FINANC)


FCFO.DATACRIACAO BETWEEN  '2023-01-01' AND '2023-03-01'