SELECT 
GRUPO.CODCOLIGADA,
GRUPO.NOME AS NOME_COLIGADA,
GRUPO.ESTADO_EMP,
GRUPO.NOME AS NOME_EMP, 
GRUPO.COD_PESS_EMPR AS COD_EMP,
GRUPO.COMPRADOR1,
GRUPO.CGCCFO,
GRUPO.NOME_SEGUNDO_COMPRADOR,
GRUPO.CPF_SEGUNDO_COMPRADOR,
GRUPO.NUM_UNID,
GRUPO.NUM_SUB_UNID,
GRUPO.DSC_SIT_VENDA AS SITUACAO_VENDA,
GRUPO.DAT_VENDA,  
GRUPO.DAT_CANCELA,
(SELECT COUNT(*) FROM XSUBUNIDADE (NOLOCK) WHERE XSUBUNIDADE.COD_PESS_EMPR = GRUPO.COD_PESS_EMPR) AS NUM_UNIDADES,
GRUPO.NUM_VENDA, 
GRUPO.VALOR_VENDA , 


SUM(GRUPO.CEF) AS TOTAL_CEF,

SUM(GRUPO.FGTS) AS TOTAL_FGTS,


(
	GRUPO.VALOR_VENDA - 

		SUM(GRUPO.CEF) - 
		SUM(GRUPO.FGTS)
) TOTAL_PROPRIO,
		
SUM(CASE WHEN GRUPO.CODTIPOPARC = 101 AND GRUPO.STATUSLAN <> 2THEN ISNULL(GRUPO.VALORORIGINAL,0)  ELSE 0 END)  VALOR_DESCONTO,
SUM(CASE WHEN GRUPO.CODTIPOPARC = 1 AND GRUPO.STATUSLAN <> 2 THEN ISNULL(GRUPO.VALORORIGINAL,0)  ELSE 0 END)  VALOR_SINAL,
GRUPO.DSC_MOD_VENDA,
GRUPO.PROPOSTA_HYPNOBOX


FROM 


(
		SELECT 
		GCOLIGADA.CODCOLIGADA,
		GCOLIGADA.NOME AS NOME_COLIGADA,
		XEMPREENDIMENTO.UF AS ESTADO_EMP,
		XEMPREENDIMENTO.NOME,
		XEMPREENDIMENTO.COD_PESS_EMPR,
		FCFO.NOME AS COMPRADOR1,
		(SELECT TOP 1 FCFO.NOME  FROM XCOMPRADOR AS COMPRADOR2
		INNER JOIN FCFO (NOLOCK) ON COMPRADOR2.CODCFO = FCFO.CODCFO AND COMPRADOR2.CODCOLCFO = FCFO.CODCOLIGADA
		WHERE COMPRADOR2.PRINCIPAL = 0
		AND COMPRADOR2.NUM_VENDA = XVENDA.NUM_VENDA
		AND COMPRADOR2.CODCOLIGADA = XVENDA.CODCOLIGADA
 
		) AS NOME_SEGUNDO_COMPRADOR,

		(SELECT TOP 1 FCFO.CGCCFO  FROM XCOMPRADOR AS COMPRADOR2
		INNER JOIN FCFO (NOLOCK) ON COMPRADOR2.CODCFO = FCFO.CODCFO AND COMPRADOR2.CODCOLCFO = FCFO.CODCOLIGADA
		WHERE COMPRADOR2.PRINCIPAL = 0
		AND COMPRADOR2.NUM_VENDA = XVENDA.NUM_VENDA
		AND COMPRADOR2.CODCOLIGADA = XVENDA.CODCOLIGADA
 
		) AS CPF_SEGUNDO_COMPRADOR,

		XITEMVENDA.NUM_UNID,
		XITEMVENDA.NUM_SUB_UNID,
		UPPER (XSITUACAOVENDA.DSC_SIT_VENDA) AS DSC_SIT_VENDA,
		XVENDA.DAT_VENDA,  
        XVENDA.DAT_CANCELA,
		XVENDA.VALOR_VENDA , 
		XVENDA.NUM_VENDA AS NUM_VENDA, 
		XMODALIDADEVENDA.DSC_MOD_VENDA,
		
		FCFO.CGCCFO,
		XVENDAPARCELA.CODTIPOPARC,

		FLAN.VALORORIGINAL,
		FLAN.STATUSLAN,

		0 AS CEF,

		0 AS FGTS,
		XVENDA.IDINTEGRACAO AS PROPOSTA_HYPNOBOX

		FROM XVENDAPARCELA (NOLOCK)  

		INNER JOIN FLAN					(NOLOCK) ON (FLAN.IDLAN = XVENDAPARCELA.IDLAN AND FLAN.CODCOLIGADA = XVENDAPARCELA.CODCOLIGADA)
		INNER JOIN XVENDA				(NOLOCK) ON (XVENDA.CODCOLIGADA = XVENDAPARCELA.CODCOLIGADA AND XVENDA.NUM_VENDA = XVENDAPARCELA.NUMVENDA)

		INNER JOIN XITEMVENDA           (NOLOCK) ON (XITEMVENDA.COD_PESS_EMPR = XVENDA.COD_PESS_EMPR  AND XITEMVENDA.NUM_VENDA = XVENDA.NUM_VENDA)													
		INNER JOIN GCOLIGADA			(NOLOCK) ON (XVENDA.CODCOLIGADA = GCOLIGADA.CODCOLIGADA AND XVENDAPARCELA.CODCOLIGADA = GCOLIGADA.CODCOLIGADA)
		INNER JOIN XCOMPRADOR			(NOLOCK) ON (XCOMPRADOR.NUM_VENDA = XVENDA.NUM_VENDA AND XVENDA.CODCOLIGADA = XCOMPRADOR.CODCOLIGADA AND XCOMPRADOR.PRINCIPAL = '1')
		INNER JOIN FCFO					(NOLOCK) ON (XCOMPRADOR.CODCFO = FCFO.CODCFO AND XCOMPRADOR.CODCOLCFO = FCFO.CODCOLIGADA)
		INNER JOIN XSITUACAOVENDA		(NOLOCK) ON (XSITUACAOVENDA.COD_SIT_VENDA = XVENDA.COD_SIT_VENDA)
		INNER JOIN XEMPREENDIMENTO		(NOLOCK) ON (XEMPREENDIMENTO.COD_PESS_EMPR = XVENDA.COD_PESS_EMPR AND XVENDA.CODCOLIGADA = XEMPREENDIMENTO.CODCOLIGADA)
		INNER JOIN XMODALIDADEVENDA		(NOLOCK) ON (XVENDA.COD_MOD_VENDA = XMODALIDADEVENDA.COD_MOD_VENDA)
		
WHERE	XVENDA.COD_SIT_VENDA IN (@SITUACAO_VENDA)
AND		XVENDA.COD_PESS_EMPR IN (@EMPREENDIMENTO)
AND		XVENDA.CODCOLIGADA IN (@COLIGADA)
AND		(
			(XVENDA.DAT_VENDA >= @DATA_VENDA_INI AND XVENDA.DAT_VENDA < DATEADD(DAY,1,@DATA_VENDA_FIN) AND 1 = (CASE WHEN XVENDA.COD_SIT_VENDA IN (60,61,62) THEN 0 ELSE 1 END) )
			OR 
			(XVENDA.DAT_CANCELA >= @DATA_VENDA_INI AND XVENDA.DAT_CANCELA < DATEADD(DAY,1,@DATA_VENDA_FIN) AND 1 = (CASE WHEN XVENDA.COD_SIT_VENDA IN (60,61,62) THEN 1 ELSE 0 END) )
		)






) AS GRUPO

GROUP BY 
GRUPO.CODCOLIGADA,
GRUPO.COD_PESS_EMPR,
GRUPO.ESTADO_EMP,
GRUPO.NOME, 
GRUPO.COMPRADOR1,
GRUPO.CGCCFO,
GRUPO.NOME_SEGUNDO_COMPRADOR,
GRUPO.CPF_SEGUNDO_COMPRADOR,
GRUPO.NUM_UNID,
GRUPO.NUM_SUB_UNID,
GRUPO.DSC_SIT_VENDA,
GRUPO.DAT_VENDA,  
GRUPO.VALOR_VENDA , 
GRUPO.NUM_VENDA,
GRUPO.DAT_CANCELA,
GRUPO.DSC_MOD_VENDA,
GRUPO.PROPOSTA_HYPNOBOX