DECLARE @DATA_BASE_D AS DATETIME, @MULTA AS DECIMAL(10,5), @MORA AS DECIMAL(10,10)

SET @DATA_BASE_D = GETDATE()
SET @MULTA='0.02'
SET @MORA='0.033333333'

SELECT  

	   'COD. COLIGADA' = GCOLIGADA.CODCOLIGADA	
	 , 'NOME COLIGADA' = GCOLIGADA.NOME
	 ,'CLIENTE'=dbo.InitCap(FCFO.NOME)
	 ,'CPF' = FCFO.CGCCFO 
	 ,'COMPRADOR2' = 	 
	 (
		SELECT RESULT.NOMEFANTASIA FROM
			(
				SELECT FCFO.NOMEFANTASIA,
				row_number() over (order by XCOMPRADOR.NUM_VENDA)
				AS CONT
				FROM XCOMPRADOR
				INNER JOIN FCFO ON FCFO.CODCFO = XCOMPRADOR.CODCFO
				AND FCFO.CODCOLIGADA = XCOMPRADOR.CODCOLCFO
				WHERE XCOMPRADOR.NUM_VENDA = XVENDA.NUM_VENDA
				AND XCOMPRADOR.PRINCIPAL = 0
			) AS RESULT
			WHERE RESULT.CONT = 1
		) 

	 ,'CPF_COMPRADOR2' = 
	  (
		SELECT RESULT.CGCCFO FROM
			(
				SELECT FCFO.CGCCFO,
				row_number() over (order by XCOMPRADOR.NUM_VENDA)
				AS CONT
				FROM XCOMPRADOR
				INNER JOIN FCFO ON FCFO.CODCFO = XCOMPRADOR.CODCFO
				AND FCFO.CODCOLIGADA = XCOMPRADOR.CODCOLCFO
				WHERE XCOMPRADOR.NUM_VENDA = XVENDA.NUM_VENDA
				AND XCOMPRADOR.PRINCIPAL = 0
			) AS RESULT
			WHERE RESULT.CONT = 1
		)
	
	 ,XVENDA.NUM_VENDA
     ,'NOME_EMPREENDIMENTO' = XEMPREENDIMENTO.NOME 
	 ,'BL/QD'=XITEMVENDA.NUM_UNID 
     ,'APTO/LOTE'=XITEMVENDA.NUM_SUB_UNID 
	 ,'UF' = XEMPREENDIMENTO.UF
     ,'TIPO_PAGTO'=XTIPOPARCELA.DSC_TIPO_PARC
	 , 'REF DE LANCAMENTO'= FLAN.IDLAN
     ,'PARCELA'=XVENDAPARCELA.NUMPARC
     ,'VENCIMENTO'=CONVERT(VARCHAR,FLAN.DATAVENCIMENTO,103)
	 ,'VALOR_ORIGINAL' = CAST((CASE WHEN FLAN.STATUSLAN IN (4) THEN  DBO.SAL_REMANECENTE(XVENDAPARCELA.IDLAN, XVENDAPARCELA.CODCOLIGADA) ELSE FLAN.VALORORIGINAL END) AS money)
		
   ,'CORREÇÃO'= CAST(ISNULL((SELECT SUM (VALOR)FROM FLANINTEGRACAO WHERE IDLAN = FLAN.IDLAN AND CODCOLIGADA = FLAN.CODCOLIGADA AND IDCAMPO IN (select IDCAMPO from dbo.RETORNA_IDCAMPO_JUROS(FLAN.CODCOLIGADA,'CM'))),0) 
					-
					/* CORRECAO BAIXADA PARCIALMENTE */ ISNULL((SELECT SUM (VALOR)FROM FLANBAIXAINTEGRACAO 
					INNER JOIN FLANBAIXA (NOLOCK) ON (FLANBAIXA.IDBAIXA = FLANBAIXAINTEGRACAO.IDBAIXA AND FLANBAIXA.IDLAN = FLANBAIXAINTEGRACAO.IDLAN AND FLANBAIXA.CODCOLIGADA = FLANBAIXAINTEGRACAO.CODCOLIGADA)
					WHERE FLANBAIXA.STATUS <> 1 AND FLANBAIXAINTEGRACAO.IDLAN = FLAN.IDLAN AND FLANBAIXAINTEGRACAO.CODCOLIGADA = FLAN.CODCOLIGADA AND FLANBAIXAINTEGRACAO.IDCAMPO IN (select IDCAMPO from dbo.RETORNA_IDCAMPO_JUROS(FLAN.CODCOLIGADA,'CM'))),0)as money)
	
	,'JUROS'= CAST(ISNULL((SELECT SUM (VALOR)FROM FLANINTEGRACAO WHERE IDLAN = FLAN.IDLAN AND CODCOLIGADA = FLAN.CODCOLIGADA AND IDCAMPO IN (select IDCAMPO from dbo.RETORNA_IDCAMPO_JUROS(FLAN.CODCOLIGADA,'JUROS'))),0)  
					-
					/* JUROS BAIXADO PARCIALMENTE */ ISNULL((SELECT SUM (VALOR)FROM FLANBAIXAINTEGRACAO 
					INNER JOIN FLANBAIXA (NOLOCK) ON (FLANBAIXA.IDBAIXA = FLANBAIXAINTEGRACAO.IDBAIXA AND FLANBAIXA.IDLAN = FLANBAIXAINTEGRACAO.IDLAN AND FLANBAIXA.CODCOLIGADA = FLANBAIXAINTEGRACAO.CODCOLIGADA)
					WHERE FLANBAIXA.STATUS <> 1 AND FLANBAIXAINTEGRACAO.IDLAN = FLAN.IDLAN AND FLANBAIXAINTEGRACAO.CODCOLIGADA = FLAN.CODCOLIGADA AND FLANBAIXAINTEGRACAO.IDCAMPO IN (select IDCAMPO from dbo.RETORNA_IDCAMPO_JUROS(FLAN.CODCOLIGADA,'JUROS'))),0)  as money)
	
	,'DESCONTO'=CAST(VALORDESCONTO AS money) 
			
	
	,'MULTA' = CAST((dbo.MULTA_PARCELAS_SGI (FLAN.CODCOLIGADA,FLAN.IDLAN, @DATA_BASE_D))  AS money)
	,'MORA' = CAST((dbo.JUROS_PARCELAS_SGI (FLAN.CODCOLIGADA,FLAN.IDLAN, @DATA_BASE_D)) as money)
				
			,VALOR_ATUALIZADO=CAST((CASE WHEN FLAN.STATUSLAN IN (4) THEN  DBO.SAL_REMANECENTE(XVENDAPARCELA.IDLAN, XVENDAPARCELA.CODCOLIGADA) ELSE FLAN.VALORORIGINAL END)  +ISNULL((SELECT SUM (VALOR)FROM FLANINTEGRACAO WHERE IDLAN = FLAN.IDLAN AND CODCOLIGADA = FLAN.CODCOLIGADA AND IDCAMPO IN (select IDCAMPO from dbo.RETORNA_IDCAMPO_JUROS(FLAN.CODCOLIGADA,'CM'))),0) +ISNULL((SELECT SUM (VALOR)FROM FLANINTEGRACAO WHERE IDLAN = FLAN.IDLAN AND CODCOLIGADA = FLAN.CODCOLIGADA AND IDCAMPO IN (select IDCAMPO from dbo.RETORNA_IDCAMPO_JUROS(FLAN.CODCOLIGADA,'JUROS'))),0) + FLAN.VALORJUROS
			+(dbo.MULTA_PARCELAS_SGI (FLAN.CODCOLIGADA,FLAN.IDLAN, @DATA_BASE_D))
			+(dbo.JUROS_PARCELAS_SGI (FLAN.CODCOLIGADA,FLAN.IDLAN, @DATA_BASE_D)) 
			-/* CORRECAO BAIXADA PARCIALMENTE */ ISNULL((SELECT SUM (VALOR)FROM FLANBAIXAINTEGRACAO 
			INNER JOIN FLANBAIXA (NOLOCK) ON (FLANBAIXA.IDBAIXA = FLANBAIXAINTEGRACAO.IDBAIXA AND FLANBAIXA.IDLAN = FLANBAIXAINTEGRACAO.IDLAN AND FLANBAIXA.CODCOLIGADA = FLANBAIXAINTEGRACAO.CODCOLIGADA)
			WHERE FLANBAIXA.STATUS <> 1 AND FLANBAIXAINTEGRACAO.IDLAN = FLAN.IDLAN AND FLANBAIXAINTEGRACAO.CODCOLIGADA = FLAN.CODCOLIGADA AND FLANBAIXAINTEGRACAO.IDCAMPO IN (select IDCAMPO from dbo.RETORNA_IDCAMPO_JUROS(FLAN.CODCOLIGADA,'CM'))),0)
			-/* JUROS BAIXADO PARCIALMENTE */ ISNULL((SELECT SUM (VALOR)FROM FLANBAIXAINTEGRACAO 
			INNER JOIN FLANBAIXA (NOLOCK) ON (FLANBAIXA.IDBAIXA = FLANBAIXAINTEGRACAO.IDBAIXA AND FLANBAIXA.IDLAN = FLANBAIXAINTEGRACAO.IDLAN AND FLANBAIXA.CODCOLIGADA = FLANBAIXAINTEGRACAO.CODCOLIGADA)
			WHERE FLANBAIXA.STATUS <> 1 AND FLANBAIXAINTEGRACAO.IDLAN = FLAN.IDLAN AND FLANBAIXAINTEGRACAO.CODCOLIGADA = FLAN.CODCOLIGADA AND FLANBAIXAINTEGRACAO.IDCAMPO IN (select IDCAMPO from dbo.RETORNA_IDCAMPO_JUROS(FLAN.CODCOLIGADA,'JUROS'))),0)
			-VALORDESCONTO AS money)
			,XSITUACAOVENDA.DSC_SIT_VENDA
			,'ENDEREÇO' = FCFO.RUA + ', Nº: ' + FCFO.NUMERO + ', BAIRRO: '+ FCFO.BAIRRO + ', CIDADE: ' +GMUNICIPIO.NOMEMUNICIPIO + ', UF: ' + FCFO.CODETD
			,'TELEFONE' = ISNULL(FCFO.TELEFONE,FCFO.TELEX)
			,FCFO.EMAIL


FROM			    XVENDA (NOLOCK)
					LEFT JOIN XVENDAPARCELA (NOLOCK)  ON (XVENDAPARCELA.NUMVENDA=XVENDA.NUM_VENDA)
					LEFT JOIN XEMPREENDIMENTO (NOLOCK)   ON (XEMPREENDIMENTO.COD_PESS_EMPR=XVENDA.COD_PESS_EMPR)
					LEFT JOIN FCFO (NOLOCK)   ON (FCFO.CODCOLIGADA=XVENDA.CODCOLCFO AND FCFO.CODCFO=XVENDA.CODCFO)
					LEFT JOIN XTIPOPARCELA (NOLOCK)   ON (XVENDAPARCELA.CODTIPOPARC=XTIPOPARCELA.COD_TIPO_PARC)
					LEFT JOIN FLAN (NOLOCK)   ON (XVENDAPARCELA.CODCOLLAN=FLAN.CODCOLIGADA AND XVENDAPARCELA.IDLAN=FLAN.IDLAN)
					LEFT JOIN XMODALIDADEVENDA (NOLOCK)   ON (XMODALIDADEVENDA.COD_MOD_VENDA=XVENDA.COD_MOD_VENDA)
					LEFT JOIN XSITUACAOVENDA (NOLOCK) ON (XVENDA.COD_SIT_VENDA = XSITUACAOVENDA.COD_SIT_VENDA)
					LEFT JOIN XITEMVENDA (NOLOCK)   ON (XITEMVENDA.NUM_VENDA=XVENDA.NUM_VENDA)
				    LEFT JOIN GMUNICIPIO (NOLOCK) ON (FCFO.CODMUNICIPIO = GMUNICIPIO.CODMUNICIPIO AND FCFO.CODETD = GMUNICIPIO.CODETDMUNICIPIO)
					LEFT JOIN GCOLIGADA (NOLOCK) ON (GCOLIGADA.CODCOLIGADA = XVENDA.CODCOLIGADA)
					LEFT JOIN XEMPREENDIMENTOCOMPL (NOLOCK) ON (XEMPREENDIMENTOCOMPL.CODCOLIGADA = XEMPREENDIMENTO.CODCOLIGADA AND XEMPREENDIMENTOCOMPL.CODPESSEMPR = XEMPREENDIMENTO.COD_PESS_EMPR) 
WHERE				
					XTIPOPARCELA.COD_TIPO_PARC NOT IN (26,101,106,13,60,90)
					AND XVENDA.COD_SIT_VENDA NOT IN (60,61,62,10)
					AND FLAN.STATUSLAN IN (0,4)
					AND DBO.QTD_PARCELA_MAIOR_180_DIAS(XVENDA.NUM_VENDA,XVENDA.CODCOLIGADA) > 0
					AND XEMPREENDIMENTOCOMPL.INTEGRACAOAPI = @ESCRITORIO
     
order by FCFO.NOME    