SELECT

GCOLIGADA.CODCOLIGADA,
(CONVERT(VARCHAR(3),GCOLIGADA.CODCOLIGADA) + ' - ' + GCOLIGADA.NOME) AS COLIGADA

FROM GCOLIGADA
WHERE (CODCOLIGADA =1 OR CODCOLIGADA >=10 AND CODCOLIGADA  <> 54 AND CODCOLIGADA <>61) 