SELECT 
					FLAN.CODCOLIGADA,
					GFILIAL.NOMEFANTASIA AS NOME_FILIAL,
					XEMPREENDIMENTO.NOME AS NOME_EMPREENDIMENTO, 
					FLAN.IDLAN AS IDLAN,
					FLANBAIXA.IDBAIXA AS REF_DE_BAIXA,
					FCFO.CGCCFO AS CNPJCPF,
					GFILIAL.CGC AS CNPJ_EMPREENDIMENTO,
					FCFO.NOMEFANTASIA AS NOME_CLIENTE,
					XTIPOPARCELA.DSC_TIPO_PARC AS TIPO_PARCELA,
					FORMAT(FLAN.DATAVENCIMENTO, 'dd/MM/yyyy') AS DATA_VENCIMENTO,
					FORMAT(FLANBAIXA.DATABAIXA, 'dd/MM/yyyy') AS DATA_BAIXA,
					CONVERT(DECIMAL(10,2), FLANBAIXA.VALORORIGINAL) AS VALOR_ORIGINAL,
					CONVERT (DECIMAL(10,2), FLANBAIXA.VALORJUROS) AS VALORJUROS,
					CONVERT (DECIMAL(10,2), FLANBAIXA.VALORMULTA) AS VALORMULTA,
					CONVERT (DECIMAL(10,2), FLANBAIXA.VALORDESCONTO) AS VALORDESCONTO, 
					CONVERT (DECIMAL(10,2), FLANBAIXA.VALOROP8) AS HONORARIOS,
					CONVERT (DECIMAL(10,2), FLANBAIXA.VALORBAIXA)AS VALOR_BAIXADO,
						CONVERT(DECIMAL(10,2), (FLANBAIXA.VALORORIGINAL  
								+ (SELECT SUM(FLANINTEGRACAO.VALOR) 
								FROM FLANINTEGRACAO 
								WHERE FLANINTEGRACAO.IDLAN = FLAN.IDLAN 
								AND FLANINTEGRACAO.CODCOLIGADA = FLAN.CODCOLIGADA 
								AND FLANINTEGRACAO.IDCAMPO NOT IN (10, 40))
								+ FLANBAIXA.VALOROP8 
								+ FLANBAIXA.VALORJUROS 
								+ FLANBAIXA.VALORMULTA 
								- FLANBAIXA.VALORDESCONTO 
								/* LANÇAMENTOS DE DESCONTO VIA ADITIVO
								- CONVERT(DECIMAL(10,2), 
									(SELECT SUM(FLANINTEGRACAO.VALOR) 
									 FROM FLANINTEGRACAO 
									WHERE FLANINTEGRACAO.IDLAN = FLAN.IDLAN 
									AND FLANINTEGRACAO.CODCOLIGADA = FLAN.CODCOLIGADA 
									AND FLANINTEGRACAO.IDCAMPO  = 61)*/))	AS VALOR_SOMADO,
					CONVERT(VARCHAR(MAX),FLANCOMPL.COBRANCA) AS COBRANCA
 
			 FROM FLAN (NOLOCK)
 
		    LEFT JOIN XVENDAPARCELA							(NOLOCK) ON (XVENDAPARCELA.IDLAN = FLAN.IDLAN AND XVENDAPARCELA.CODCOLLAN = FLAN.CODCOLIGADA)
			LEFT JOIN XTIPOPARCELA								(NOLOCK) ON (XTIPOPARCELA.COD_TIPO_PARC = XVENDAPARCELA.CODTIPOPARC)
			LEFT JOIN XVENDA											(NOLOCK) ON (XVENDAPARCELA.NUMVENDA = XVENDA.NUM_VENDA)
			LEFT JOIN XEMPREENDIMENTO						(NOLOCK) ON (XEMPREENDIMENTO.COD_PESS_EMPR = XVENDA.COD_PESS_EMPR)				
			LEFT JOIN GFILIAL											(NOLOCK) ON (XEMPREENDIMENTO.CODFILIAL = GFILIAL.CODFILIAL AND XEMPREENDIMENTO.CODCOLIGADA = GFILIAL.CODCOLIGADA)
			LEFT JOIN FCFO												(NOLOCK) ON (FLAN.CODCFO = FCFO.CODCFO AND FLAN.CODCOLCFO = FCFO.CODCOLIGADA)
			INNER JOIN FLANBAIXA									(NOLOCK) ON (FLANBAIXA.IDLAN = FLAN.IDLAN AND FLANBAIXA.CODCOLIGADA = FLAN.CODCOLIGADA)
			--LEFT JOIN FLANINTEGRACAO						(NOLOCK) ON (FLANINTEGRACAO.IDLAN = FLAN.IDLAN AND FLANINTEGRACAO.CODCOLIGADA = FLAN.CODCOLIGADA)
			--LEFT JOIN FLANINTEGRACAODEF				(NOLOCK) ON (FLANINTEGRACAO.IDCAMPO = FLANINTEGRACAODEF.IDCAMPO AND FLANINTEGRACAO.CODCOLIGADA = FLANINTEGRACAODEF.CODCOLIGADA)
			LEFT JOIN FLANCOMPL									(NOLOCK) ON (FLANCOMPL.IDLAN = FLAN.IDLAN AND FLANCOMPL.CODCOLIGADA = FLAN.CODCOLIGADA )

			WHERE FLAN.CODCOLIGADA IN (@CODCOLIGADA) 
			AND FLANBAIXA.DATABAIXA BETWEEN @DATA_INI  AND @DATA_FIM
			AND CONVERT(VARCHAR,FLANCOMPL.COBRANCA) IN (@COBRANCA)
			/*AND FLANINTEGRACAODEF.DESCRICAO NOT IN ('CM APOS ENTREGA', 'CM ANTES ENTREGA', 'TAXA JUROS APOS ENTREGA', 'Taxa Juros Apos Entrega-106', 'Taxa Juros Antes Entrega')
			AND FLAN.IDLAN = '49296'*/

/*WHERE --GCOLIGADA.CODCOLIGADA IN (@CODCOLIGADA) AND 
FLANBAIXA.DATABAIXA BETWEEN @DATA_INI  AND @DATA_FIM
CONVERT(VARCHAR,FLANCOMPL.COBRANCA) IN ('C1023')
AND FLANINTEGRACAODEF.DESCRICAO NOT IN ('CM APOS ENTREGA', 'CM ANTES ENTREGA', 'TAXA JUROS APOS ENTREGA', 'Taxa Juros Apos Entrega-106', 'Taxa Juros Antes Entrega')
AND FLANBAIXA.IDBAIXA = '31545'
AND FLAN.CODCOLIGADA = 35
 
GROUP BY 
     FLAN.CODCOLIGADA
	,XEMPREENDIMENTO.NOME
	,GFILIAL.NOMEFANTASIA
	,FCFO.NOMEFANTASIA
	,FCFO.CGCCFO
    ,FLANBAIXA.IDBAIXA
	,XTIPOPARCELA.DSC_TIPO_PARC
	,FLANBAIXA.DATABAIXA
	,FLAN.DATAVENCIMENTO
    ,FLANBAIXA.VALORJUROS
    ,FLANBAIXA.VALORMULTA
    ,FLANBAIXA.VALORDESCONTO
    ,FLANBAIXA.VALOROP8
    ,FLANBAIXA.VALORBAIXA
    ,CONVERT(VARCHAR(MAX),FLANCOMPL.COBRANCA)
	,GFILIAL.CGC
 
ORDER BY Subquery.NOME_CLIENTE DESC
 */